### ISSUE TITLE
Feature: Work based slicing.

### ISSUE THREAD

**Issue by flower1024** [c00w/bitHopper#103]
hi,

what would you think about (optional) multiple pool workers and an additional scheduler which is like your slicing one (pretty nice looking, but did not work for me, quitted with an error no pool selected. but mtred was hot [not sure if it got the share count already]) but just moves some of the miners there - means less hopping as they could stay?

**Comment by c00w** [comment]
That would be awesome.

**Comment by c00w** [comment]
Implemented in bleeding edge.
