### ISSUE TITLE
lp broken

### ISSUE THREAD

**Issue by flower1024** [c00w/bitHopper#105]
diablominer windows: sometimes drops to 0mhash
poclbm (linux; p2pool fastlongpoll patch) did work before two days. now it sometimes spits out an exception:

localhost:8000 03/08/2011 10:40:49, long poll: new block 0000057982e3176b
localhost:8000 [248.870 MH/s (~221 MH/s)] [Rej: 0/43 (0.00%)]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/flower/miner/fastlongpoll/poclbm/HttpTransport.py", line 165, in long_poll_thread
    say_line('long poll: new block %s%s', (result['result']['data'][56:64], result['result']['data'][48:56]))
TypeError: 'NoneType' object is not subscriptable

-> i had the same issue with an really old version of bithopper. i guess its your commit:c80a2ba1446c0a8eee7b
"Should fix our Lp problems and give us new interesting ones"

and: why is there no lp when bithopper selects a new server?

**Comment by c00w** [comment]
We reroute works requests on the server side. So emptying the client side buffers is no longer needed.

**Comment by c00w** [comment]
I think some LP responses are returning None... I'll fix it/

**Comment by c00w** [comment]
It should no longer kill the clients. Is this error still appearing?

**Comment by flower1024** [comment]
just updated.
i'll tell you when it happens again.

thank you

**Comment by flower1024** [comment]
it works; thanks
