### ISSUE TITLE
Requests by EskimoBob

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#121]
1) Please add a thousand separators to stat page (Shares, User shares etc)
2) Please add a button to force mining in selected  pool and hop away only when another pool starts a new block
3) Remove  "api_disable"  after N seconds and return the pool back to its previous status (mine etc)
4) Move backup pool to the end of the mining pools list and before disabled pools (pool sorting)

**Comment by paraipan** [comment]
4) added by c00w

**Comment by c00w** [comment]
Sort of.

**Comment by paraipan** [comment]
hehe but if it works... I will test it in a moment

**Comment by c00w** [comment]
3) Is done by the new api_angel plugin.

**Comment by c00w** [comment]
1) Is added.

**Comment by c00w** [comment]
All of these have been implemented except for the force mining issue. I'm closing this issue as it has its own separate feature request.
