### ISSUE TITLE
Small request by djex

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#122]
Independent worker color status. Ex: After 10 min if shares have not changed for x worker then color name red else color green.

**Comment by bitcoindaddy** [comment]
Instead of using a color - you could just show the same graph for the miners that you do for the pools. At a glance you could see if they were incrementing or not.

**Comment by djex** [comment]
Personally I don't find the graphs much of a help. Color would stand out more.

**Comment by c00w** [comment]
Well I added the lastseen info to the data page and updated index-altslice to display it. Its not in user form however. If someone wants to take the intiative and get the coloring working, sweet. Otherwise I'll do it when I have time.

**Comment by djex** [comment]
Awesome I'll take a look a bit later. The key thing way getting that lastseen in there so I can work with that. Thanks. :D

**Comment by c00w** [comment]
Heads up its in seconds since 1960 (The core computer time) so well its going to be awkward. I could have it pass a time piece in the payload as well and you can just have it current_time - lastseen > 5*60 etc...
