### ISSUE TITLE
Suggestion: Create {USER} variable

### ISSUE THREAD

**Issue by Gnaget** [c00w/bitHopper#129]
If we could use {USER} as a variable in user.cfg to replace with the current worker username.

So,
I have worker "alice" who requests work from bH.  bH decides that bitclockers is the pool to use.  If the user in the cfg is gnaget_{user}, it would request the work on behalf of the user gnaget_alice.

**Comment by c00w** [comment]
Hmmm. That could work and would probably solve the bitclockers issue. I'll add it to the list.

**Comment by dadittoz** [comment]
I vote for this. I have 83.98% rejects on slush pool.

**Comment by c00w** [comment]
Um, your rollntime implementation is probably different from what slush is using. I get like 2% rejects.

**Comment by dadittoz** [comment]
It's not about rollntime. Rollntime works fine. I have  1.12% rejects on deepbit and 2.42% on eligius. It's slush who cannot handle 46 miners with -q 2 on one worker account. He clearly states on his site "Register your workers. !!!Every instance of your miner needs its own worker account!!!". So this option is vital.

**Comment by c00w** [comment]
Okay.

**Comment by c00w** [comment]
So I added {USER} and {PASSWORD} in. Have at it.

**Comment by dadittoz** [comment]
How do I pull this change? Couldn't find any commits regarding it.

**Comment by c00w** [comment]
Just pushed it.

**Comment by dadittoz** [comment]
Could you please merge to v0.2.4.4? I don't want to loose rollntime :)

**Comment by c00w** [comment]
Um, both these changes are in the latest non tagged version.

**Comment by dadittoz** [comment]
Sorry, I am dumb :)

**Comment by dadittoz** [comment]
Got this:

```
[05:05:30] Server change to slush
[05:05:30] DEBUG: Caught, jsonrpc_call insides
[05:05:30] DEBUG: expected a character buffer object
[05:05:30] DEBUG: Caught, jsonrpc_call insides
[05:05:30] DEBUG: expected a character buffer object
[05:05:30] Lagging. :slush
```

user variable for slush pool set to:

```
user: myusernamehere.{USER}
```

**Comment by dadittoz** [comment]
Line 149 of work.py should be changed to

```
work, server_headers = self.jsonrpc_call(server, data, headers, username, password)
```

In other case username and password variables get passed as None

**Comment by dadittoz** [comment]
jsonrpc_lpcall function should also have username and password replaced. Maybe it makes sense moving this code to another function

**Comment by c00w** [comment]
Fixed now.

**Comment by dadittoz** [comment]
There's also a copy-paste issue on line 83:

```
if '{USER}' in info['pass'] and password == None:
```

should be

```
if '{PASSWORD}' in info['pass'] and password == None:
```

**Comment by c00w** [comment]
Fixed.

**Comment by c00w** [comment]
Hmmm. jsonrpc_lpcall. That is an issue. We'll have to deal with it.

**Comment by dadittoz** [comment]
And looks like 
`password == None` 
makes it not work. In this case we want the password to be set, rather than empty.

And such authorization replacement should also happen in jsonrpc_lpcall

**Comment by dadittoz** [comment]
I suggest something like this

```
    def replace_credentials(self, server, worker_username, worker_password):
        pool_info = self.bitHopper.pool.get_entry(server)
        if '{USER}' in pool_info['user'] and worker_username is not None:
            user = pool_info['user'].replace('{USER}', worker_username)
        else:
            user = pool_info['user']
        if '{PASSWORD}' in pool_info['pass'] and worker_username is not None:
            passw = pool_info['pass'].replace('{PASSWORD}', worker_password)
        else:
            passw = pool_info['pass']
        return user, passw

```

**Comment by dadittoz** [comment]
Maybe we can introduce lp_user variable in user.cfg to handle long polls? In case it's not set we can fallback to 'user'

**Comment by dadittoz** [comment]
Looks like I cannot test slush now. For some reason it returns HTTP/1.1 400 BAD REQUEST for me even without bit hopper.

**Comment by c00w** [comment]
Hm.... I just thought I got it working. I'll take a look.

**Comment by c00w** [comment]
Oh. Even without bitHopper? Thats wierd.

**Comment by dadittoz** [comment]
I fixed 400 bad requests, not all workers were registered. But I still cannot test it with hopper. If I set percent: 20 to slush it lags out. Though user name and password is passed correctly

**Comment by dadittoz** [comment]
I'll pull the latest and try again.

**Comment by c00w** [comment]
Huh.

**Comment by dadittoz** [comment]
With all latest commits I have pools lagging out fast. I cannot get slush working :) Have three lagged and not coming back out now BitcoinPool.com, DeepBit.com and Bitcoin.cz. They are red and not going back. I see "DEBUG: Not delagging". Probably something got broken in latest commits.

**Comment by c00w** [comment]
Hmmm. I'll take a look.

**Comment by dadittoz** [comment]
Current debug log is really a mess... It would be nice to have a function that logs current request to server with headers and the server reply with headers. And the output to log should be only triggered if something is wrong. If the request was successful it shouldn't write to log. It could be possible to get rid of these "192.168.5.1 - - [31/Aug/2011 08:57:05] "POST / HTTP/1.1" 200 727 0.094483" in the logs. Doesn't look like useful information anyway.

**Comment by dadittoz** [comment]
There could be a timer say every 30 seconds that counts all successful and unsuccessful connections attempts in that time, and this information could be logged.

**Comment by c00w** [comment]
Um. I fixed the wsgi logs to not automatically appear in debug mode.

**Comment by c00w** [comment]
Okay. I'm closing this issue because it works.
That lagging issue has also been fixed.
