### ISSUE TITLE
sys.stdout.flush()

### ISSUE THREAD

**Issue by flower1024** [c00w/bitHopper#13]
please add sys.stdout.flush() to your log_msg () function
it makes debugging much easier

i don't know howto flush your logger

**Comment by c00w** [comment]
Are you talking about debug mode or normal mode?  
I understand that flush would speed up the writing a little bit but I can't add it it in non debug mode since its not really needed.
In debug mode we are using twisted logging which doesn't have a flush.

**Comment by flower1024** [comment]
ok, i think i should check your debug flag then.
thanks

**Comment by c00w** [comment]
Actually I thought there was an issue with the log_dbg not getting written sometimes. I think I ironed it out though. But yeah if you want to debug running python bitHopper.py --debug makes it a lot easier.
