### ISSUE TITLE
Stats Modules is broken/vestigial

### ISSUE THREAD

**Issue by mykohsu** [c00w/bitHopper#139]
In stats.py the update shares and update payout are using the wrong variable names. I tried to fix it but in db class not sure where to get user to update shares. Or was this intended to be removed?

**Comment by c00w** [comment]
Um, Stats.py is extremely vestigial. It is meant to be rewritten to use the new config system and automatically scrape stats for shares from pools which supply them. For now I'm just going to disable it until someone can give it the love it needs.

**Comment by c00w** [comment]
Deleted.
