### ISSUE TITLE
get mhash with:

### ISSUE THREAD

**Issue by flower1024** [c00w/bitHopper#14]
def main():
   [...]
    mhash_call = LoopingCall(update_mash)
    mhash_call.start(60 \* 10)
   [...]

global var:
totalshares = 0
totalmhash = 0

def update_mash():
    global totalshares
    global totalmhash
    log_msg("bitHopper Calculating MHash")
    # called every ten minutes
    totalmhash = int(((float(totalshares)) \* (2**32)) / (60 \* 10 \* 1000000))
    totalshares = 0
        log_msg("MHash" + totalmhash)

def bitHopper_Post(request):
    [...]
   global totalshares
    if data:
        totalshales = totalshares + 1
    [...]

**Comment by c00w** [comment]
Nice addon. I'll add it at somepoin as a command line option

**Comment by c00w** [comment]
Its added and merged in. Its not a command line option.
