### ISSUE TITLE
No way, still, to donate one percent to author

### ISSUE THREAD

**Issue by joulesbeef** [c00w/bitHopper#142]
yeah I could donate what i wish but I am bitcoin poor and my donations would be micro in size, I'd rather have a way to do 1%, to show my appreciation. Maybe keep it in a hopper wallet, so you can share a bit with some of the other coders when they help out.

**Comment by c00w** [comment]
Um. It should be pretty easy to add a role called donation which feeds to an eligius account. Hmmm.

**Comment by joulesbeef** [comment]
it would be wise cow.. you see they are selling cherry picker and you see how pop your thread is. Not sure if you care or are too bitcoin rich But I am def more than happy with the results of your work so far. Without the hopper I probably would have quit due to difficulty.

**Comment by c00w** [comment]
Hmmm. Well I have the donation address up for a reason but I'll add in a donation roll on eligius.

**Comment by joulesbeef** [comment]
I will be glad to add simply donate to your addy. I just doubt you will see as much.
