### ISSUE TITLE
Request by creativex

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#144]
If you have a slice assigned to a pool and the pool gets disabled your slicer gets "trapped" and switches to backup when all other slices are emptied. Switching the offending pool to disable or info briefly and then back on releases the trapped slices. We need a way to free those slices without user intervention when slices are assigned to a pool that goes down.

**Comment by c00w** [comment]
Um this only happens with AltSlicescheduler. The default scheduler has no issues.

**Comment by paraipan** [comment]
I've seen that too

**Comment by c00w** [comment]
It does happen with the default scheduler?

**Comment by paraipan** [comment]
yep

**Comment by c00w** [comment]
Um. Default scheduler doesn't empty slices. it just builds up. What exactly happened?

**Comment by timonex** [comment]
No. Default scheduler does not get trapped this way. It's probably the biggest problem with AltSlicer however.

**Comment by paraipan** [comment]
just checked, you're right timonex, my bad

**Comment by timonex** [comment]
Possible to add a simple lag check after threshold check on AltSliceScheduler? Seems like that's all it'd take to prevent these traps...but I'm still reading python for dummies...

**Comment by c00w** [comment]
Um, I know how to fix it, but well getting LP working and my job are bigger priorities.

**Comment by timonex** [comment]
Understood. Your efforts are very much appreciated.
