### ISSUE TITLE
Request by UrbanAdventurer

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#145]
Can bithopper be set to send bcp 1 single share every so often, like every 30 minutes, to avoid hopping penalties?

**Comment by c00w** [comment]
Um... Probably. I'm going to add a donation role which could also be used for this purpose.

**Comment by paraipan** [comment]
This could be an useful feature, would be like emulating a cpu miner, useful for donations too

**Comment by paraipan** [comment]
coded by c00w with [donation]

**Comment by c00w** [comment]
To be clear its actually the percent: 1 which does the magic. Donation role is a dummy role so we don't try and mine or poll the donation server.

**Comment by paraipan** [comment]
ack added to user.cfg.def
