### ISSUE TITLE
Request from organofcorti

### ISSUE THREAD

**Issue by organofcorti** [c00w/bitHopper#149]
in a post here: https://bitcointalk.org/index.php?topic=26866.msg439864#msg439864 I showed that for multiple pools the 43% rule isn't applicable. Is it possible to have a role:mine setting to set the hop point to any desired  fraction of difficulty?

**Comment by paraipan** [comment]
you can actually launch bH with --threshold = Override difficulty threshold (default 0.43), and have that

**Comment by timonex** [comment]
Float(penalty) will also do this on the fly.

```
  if 'penalty' in current_pool:
     difficulty = self.bh.difficulty.get_difficulty() / float(current_pool['penalty'])
```

**Comment by paraipan** [comment]
can be closed I guess
