### ISSUE TITLE
Format Share-Count

### ISSUE THREAD

**Issue by floeti** [c00w/bitHopper#15]
It is hard to read the Share-Counts at the console-output, especially the difference between houndred-thousands and millions.

I would suggest something like that:

``` python
def formatShares(shares):
    return str.format('{0:,}', int(shares))
```

and then include `formatShares(round_shares)` instead of `str(round_shares)` in `*_sharesResponse`

**Comment by c00w** [comment]
Done. well sort of. I just modified the functions directly. I should add the formatShares function but well I didn't becuase I read you suggestion promptly ignored the code and then came up with a worse solution...

**Comment by c00w** [comment]
And its done properly. I'm closing this issue.

**Comment by c00w** [comment]
Closing
