### ISSUE TITLE
Favor slush over other pools if hoppable with DefaultScheduler

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#157]
Ideally (and what has just been added to altslicer) we want it to switch to slush as soon as it turns to zero, and stay on slush (ignoring everything else) until 11%. (simonk83)

**Comment by c00w** [comment]
Public domain or transfer copyright to me?

**Comment by paraipan** [comment]
hehe it's a request c00w

**Comment by c00w** [comment]
Oops.

**Comment by simonk83** [comment]
What about having slush (or the mine_slush role even) just not accrue any slice figure at all?  That seems to be what deepbit is doing, and that doesn't switch away.   Is that an easier quick fix?

**Comment by c00w** [comment]
Well thats not what it does anymore. And I need to redo the scheduler to have three tiers of priority.
