### ISSUE TITLE
Request.finish called on a request after its connection was lost

### ISSUE THREAD

**Issue by yomismo22** [c00w/bitHopper#16]
RPC request [] submitted to bitclockers.com
caught, Final response/writing
Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
caught, Final response/writing
Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
[18:31:51] RPC request [] submitted to bitclockers.com

why i get this ?

**Comment by c00w** [comment]
Your miner quit the connection early. Its not a big deal. If you get that your miner is starved of work then it becomes a bigger deal and you should tell me your miner so I can play with it.

Or this is related to LP issues which I hopefully just fixed. If these keep showing up attach a log and tell me.

**Comment by yomismo22** [comment]
RPC request [] submitted to mtred
caught, Final response/writing
Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
[21:27:01] RPC request [] submitted to mtred

seams to show up after a restart

**Comment by c00w** [comment]
A miner restart? Then yeah its fine nothing is breaking badly. I need to modify it to not show these errors so its still a bug.

**Comment by c00w** [comment]
This should be fixed now. I'm closing the issue. If it reappears reopen it or make a new issue.
