### ISSUE TITLE
Shares estimation not working for deepbit

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#160]
Dunno what happened but yesterday was working fine and with last update just stopped working for unknown reason

**Comment by paraipan** [comment]
it works now, seems like were getting filtered or something by user-agent in too many places

**Comment by R5fan** [comment]
Its not working for me now. Deepbit shares are estimated and reduced from time to time, but they never reset to zero, so after half a day its giving me a 33M share block estimate. Works fine for all other pools. Role is set to mine_lp

**Comment by paraipan** [comment]
Can you access the http://localhost:8337/lpworkbench ? Just take a look at the results and see what pool always gets ahead of DeepBit then try putting an LP penalty on it or even disabling it temporarily until you make DB work. Try fiddling with the penalties until you get some good results, cheers

**Comment by R5fan** [comment]
I dont think I understand what Im doing here :(
lpworkbench was disabled, I enabled it and now deepbit shares do reset to zero, but on a block found by Eclipse. WTH?

Im confused to how this deepbit LP guessing works.  Why not grab the data from here:
http://blockchain.info/
To see when deepbit finds a block?

**Comment by Locky7** [comment]
http://blockchain.info/ is not as accurate as bH and Db is way to fast for you to manually do it.  Follow Paraipan's instructions until bH finds them as it should.

**Comment by R5fan** [comment]
Is there some documentation on this that im missing, because I have absolutely no clue what Im doing. 
I dont even know what LP penalties are or what this lp workbench is really showing me.

**Comment by Locky7** [comment]
Try to do a search for "LP_penalty" here https://bitcointalk.org/index.php?topic=26866.4040 

http://en.wikipedia.org/wiki/Push_technology on LP - Long Polling

That is what I did, however,  more documentation would be helpful...

**Comment by R5fan** [comment]
Thx, Ill check it out.
But are you sure blockchain info is too inaccurate? I just compared todays data from blockchain with Db's delayed statistics, and afaict, its a 100% match and the timing is within 1 minute - if you correct for timezone obviously.

I also compared data for the 13th of this month (blockchain.info has been down for ~2 days) and the match is like 99%. Only a single block it missed so far I checked. Id say thats pretty damn good. Are you getting better results with LP guessing?

**Comment by Locky7** [comment]
I agree, scratch "http://blockchain.info/ is not as accurate as bH."

**Comment by R5fan** [comment]
SHould be easy to implement this, if you can code. I dont know any python and Im a rubbish coder anyhway, so I hope someone else will pick up the ball and run with it.

Basically, on each LP, check
http://blockchain.info/blocks/deepbit?format=json
(you might need a delay, dont know how fast it is).
If its a new block from deepbit, hop there and be happy.

Speaking of hopping deepbit. I read they ban hoppers with >6GH. Is it enough to create multiple accounts, or do you need separate IPs too?
