### ISSUE TITLE
AltSliceScheduler / mine_deepbit

### ISSUE THREAD

**Issue by rkozola** [c00w/bitHopper#162]
The AltSliceScheduler does not appear to be switching to mine_deebit.

I believe this is because of missing mine_deepbit on line 427 and 453 for shares calculation.

```
            if info['role'] in ['mine']:
               shares = info['shares']
```

should be

```
            if info['role'] in ['mine', 'mine_deepbit']:
               shares = info['shares']
```

**Comment by c00w** [comment]
Yeah we need to consolidate a bunch of this stuff to be default scheduler methods...

**Comment by c00w** [comment]
Its done. The fix not the consolidation.
