### ISSUE TITLE
error with api scraping

### ISSUE THREAD

**Issue by bigbeerjr** [c00w/bitHopper#17]
I get something like the following when every pool api is scraped:

[13:05:06] Error in pool api for btcg
"[Failure instance: Traceback: <type 'exceptions.ValueError'>: zero length field name in format\n/usr/lib64/python2.6/site-packages/twisted/internet/defer.py:1076:gotResult\n/usr/lib64/python2.6/site-packages/twisted/internet/defer.py:1063:_inlineCallbacks\n/usr/lib64/python2.6/site-packages/twisted/internet/defer.py:361:callback\n/usr/lib64/python2.6/site-packages/twisted/internet/defer.py:455:_startRunCallbacks\n--- <exception caught here> ---\n/usr/lib64/python2.6/site-packages/twisted/internet/defer.py:542:_runCallbacks\n/home/multipool/bitHopper/pool.py:168:selectsharesResponse\n/home/multipool/bitHopper/pool.py:120:btcguild_sharesResponse\n]"

**Comment by c00w** [comment]
Hmmm. I commited a fix. Can you update and check if it works?

**Comment by bigbeerjr** [comment]
pretty sure I'm up to date....

~/bitHopper $ git pull
Already up-to-date.

~/bitHopper $ git status

# On branch master

# Changed but not updated:

# (use "git add <file>..." to update what will be committed)

# (use "git checkout -- <file>..." to discard changes in working directory)

#

# modified:   bitHopper.py

# modified:   password.py

#

# Untracked files:

# (use "git add <file>..." to include in what will be committed)

#

# _newclient.pyc

# bitHopper.pyc

# client.pyc

# diff.pyc

# lp.pyc

# password.pyc

# pool.pyc

# stats.pyc

# work.pyc

no changes added to commit (use "git add" and/or "git commit -a")
~/bitHopper $ git diff bitHopper.py
diff --git a/bitHopper.py b/bitHopper.py
old mode 100644
new mode 100755

**Comment by c00w** [comment]
I forgot to push it. Sorry. Try again?

**Comment by bigbeerjr** [comment]
still the same behavior. It's not limited to btcg... it's all api hits that produce the error.

**Comment by c00w** [comment]
And I commited another fix. Does that work?

**Comment by bigbeerjr** [comment]
new error:

[Failure instance: Traceback: <type 'exceptions.ValueError'>: Invalid conversion specification\n/usr/lib64/python2.6/site-packages/twisted/internet/defer.py:1076:gotResult\n/usr/lib64/python2.6/site-packages/twisted/internet/defer.py:1063:_inlineCallbacks\n/usr/lib64/python2.6/site-packages/twisted/internet/defer.py:361:callback\n/usr/lib64/python2.6/site-packages/twisted/internet/defer.py:455:_startRunCallbacks\n--- <exception caught here> ---\n/usr/lib64/python2.6/site-packages/twisted/internet/defer.py:542:_runCallbacks\n/home/multipool/bitHopper/pool.py:171:selectsharesResponse\n/home/multipool/bitHopper/pool.py:123:btcguild_sharesResponse\n/home/multipool/bitHopper/pool.py:86:FormatShares\n]"

**Comment by c00w** [comment]
Hmmm. it looks like your format function is sort of broken. I commited a new patch which will hide the errors. Does it work?

**Comment by bigbeerjr** [comment]
~/bitHopper $ ./bitHopper.py 
'Error formatting'
Unhandled Error
Traceback (most recent call last):
Failure: exceptions.ValueError: Invalid conversion specification
[13:40:17] btcguild :1458044
[13:40:17] Server change to arsbitcoin, telling client with LP
'Error formatting'
Unhandled Error
Traceback (most recent call last):
Failure: exceptions.ValueError: Invalid conversion specification

**Comment by c00w** [comment]
Yeah thats what is supposed to happen. If you don't run with a debug log it should dissapear. The issue appears to be your version of python not liking my format specification. I would say try updating python if it bugs you a lot.

**Comment by c00w** [comment]
except you are not running in debug mode...
Uhoh.

**Comment by c00w** [comment]
Should be fixed now

**Comment by bigbeerjr** [comment]
I'm in the middle of an upgrade to python 2.7
It will be a little bit before I can test again, 57 more modules to recompile.

**Comment by bigbeerjr** [comment]
well, IDK if it was your fix or the upgrade, but I'm on python 2.7 now and no more errors. I'm going to close the issue.

Thanks!
