### ISSUE TITLE
Feature: Be able to force LP mining.

### ISSUE THREAD

**Issue by Clipseza** [c00w/bitHopper#178]
I would like to have mine_deepbit option renamed to mine_lp and also bring in a new method named mine_lp_force so that in the case of pools like deepbit we could use mine_lp_force so that once deepbit is trigger it would remain at deepbit until atleast threshold is reached which goes by quickly on fast delayed stats pools like deepbit(and probably btcguild)

This method of mine_lp_force would work similar to the force method on deepbit used by ryo's fork except ryos fork doesnt count predicted rate of shares, it only forces a specific time to stay mining at deepbit.

Also could you add lp support for btcmp.com since they have delayed stats, this would work well considering right now external ap is required to pull the java stats thus more people could start hopping there.

btcmp.com fix and deepbit force method under ryo hopperexp fork and

**Comment by c00w** [comment]
mine_deepbit to mine_lp is what we need to do.

**Comment by c00w** [comment]
We now have a mine_lp_force which forces the default scheduler to mine at the pool until it receives another long poll. This is to allow people to manually correct the LP's. mine_deepbit still needs to go to mine_lp.

**Comment by c00w** [comment]
And I changed mine_deepbit to mine_lp. Should be fixed now.
