### ISSUE TITLE
'Error formatting'

### ISSUE THREAD

**Issue by yomismo22** [c00w/bitHopper#18]
'Error formatting'
Traceback (most recent call last):
Failure: exceptions.ValueError: Invalid conversion specification
[21:00:00] mining.mainframe.nl :3687866
'Error formatting'
Traceback (most recent call last):
Failure: exceptions.ValueError: Invalid conversion specification
[21:00:01] mineco :1172659
'Error formatting'
Traceback (most recent call last):
Failure: exceptions.ValueError: Invalid conversion specification
[21:00:01] bitcoin.lc :7221654
'Error formatting'
Traceback (most recent call last):
Failure: exceptions.ValueError: Invalid conversion specification
[21:00:01] mtred :193040
'Error formatting'
Traceback (most recent call last):
Failure: exceptions.ValueError: Invalid conversion specification
[21:00:01] bitclockers :45001
'Error formatting'
Traceback (most recent call last):
Failure: exceptions.ValueError: Invalid conversion specification
[21:00:01] pool.bitp.it :1512303
'Error formatting'
Traceback (most recent call last):
Failure: exceptions.ValueError: Invalid conversion specification

**Comment by c00w** [comment]
Fixed.

**Comment by yomismo22** [comment]
i still get this i made a git clone 5 min ago

**Comment by c00w** [comment]
Huh try it now.

**Comment by c00w** [comment]
Oh and upgrading to python 2.7 is probably a good idea.

**Comment by yomismo22** [comment]
i do have 2.7 and 2.6

**Comment by c00w** [comment]
Is it fixed though? And are you running it with 2.7 or 2.6/5

**Comment by yomismo22** [comment]
2.6 in 2.7  wont run

python2.7 bitHopper.py
Traceback (most recent call last):
  File "bitHopper.py", line 7, in <module>
    import work
  File "/home/x/bitHopper/work.py", line 12, in <module>
    from bitHopper import *
  File "/home/x/bitHopper/bitHopper.py", line 15, in <module>
    import lp
  File "/home/x/bitHopper/lp.py", line 11, in <module>
    from twisted.internet import reactor, defer
ImportError: No module named twisted.internet

**Comment by c00w** [comment]
You need to install twisted python in 2.7

**Comment by yomismo22** [comment]
give a link to a how to ....

**Comment by c00w** [comment]
What operating system are using?

**Comment by c00w** [comment]
Oh and is it fixed in the 2.6 version?

**Comment by yomismo22** [comment]
ubuntu 10.10

**Comment by c00w** [comment]
sudo apt-get install python-twisted

**Comment by yomismo22** [comment]
i got it already but it get installed on 2.6 not 2.7

**Comment by c00w** [comment]
Okay. Don't bother then. Is the bug currently fixed on 2.6?

**Comment by yomismo22** [comment]
nope, 

edit wait i will get last update

edit2  i dont get that anymore

**Comment by c00w** [comment]
So its fixed? I'm closing this issue if it isn't comment again/reopen.
