### ISSUE TITLE
Allow IP-based authentication

### ISSUE THREAD

**Issue by alinnow** [c00w/bitHopper#184]
I have found that the auth change is more annoying than useful to me, as access to bitHopper is protected via a local firewall and a NAT. I suggest that a list of IPs, either with wildcards, netmasks or CIDR masks should be used as a whitelist, e.g. `--allowIP=10.0.0.0/8`. Futhermore, if `--auth` is given, this should combine both restrictions as an AND. If only one is given, use that alone.

**Comment by c00w** [comment]
Sweet. Um if you have a local firewall and a NAT (Which I do as well) then don't use auth. Its very basic authentication for those who expose their bitHopper to the internet.

**Comment by c00w** [comment]
But a --allowIP would be nice.

**Comment by alinnow** [comment]
So you're planning for `--auth` to be optional? Because currently the web interface requires it — I assumed this was a deliberate change

**Comment by c00w** [comment]
You can run without --auth.

**Comment by c00w** [comment]
Actually you can't. I'll fix it.

**Comment by c00w** [comment]
Fixed. Closing the issue.
