### ISSUE TITLE
Some pools doesn't show correct information

### ISSUE THREAD

**Issue by CooleRnax** [c00w/bitHopper#193]
NoFeeMining.com - always 1888786 100.00%
OzCo.in - always 1888786 100.00%
MtRed.com - always 1888786 100.00%
BitcoinMonkey.com - always 1888786 100.00%

**Comment by Endeavour79** [comment]
All above updating okay for me. Version 1.7.2

**Comment by annawaw** [comment]
Make sure you have installed OpenSSL.
see https://bitcointalk.org/index.php?topic=26866.msg414510#msg414510.

**Comment by CooleRnax** [comment]
i installed scripts with C:\Python27\Scripts\easy_install 2.7.exe and now everything is ok
installing scripts with C:\Python27\Scripts\easy_install.exe didn't work for me
