### ISSUE TITLE
fix stats from bitcoin pool

### ISSUE THREAD

**Issue by annawaw** [c00w/bitHopper#201]
Bitcoinpool added another fake data to their website. Round stats are now present twice in the page source.
1) Fake and commented out.
2) Real one.

BH currently pulls the fake ones.

**Comment by sdogi** [comment]
Could fix it but I'm not sure if it is worth it.. this guy is obviously monitoring this project really closely and is trying to scheme hoppers for better network speed.

**Comment by annawaw** [comment]
You are right. BH has open source so most likely if we fix it here, he will adjust and break us again.
Maybe disabling this pool by default and letting anyone who is interested to adjust their local pools.cfg file is the best option for now.

**Comment by annawaw** [comment]
Closing as "won't fix"
