### ISSUE TITLE
BH stopped to increasing number of shares for deepbit pool.

### ISSUE THREAD

**Issue by annawaw** [c00w/bitHopper#205]
BH stopper increasing number of shares for deepbit pool (set to mine_deepbit). The number was constantly at 0 shares (it seems like the number of shares stalled even before being set to 0)
Screenshot: http://imageshack.us/f/35/deepbit.png/.

BH did not recover when receiving LP.
BH is using DefaultScheduler and --p2pLP  option. Version 0.1.7.2-14.

**Comment by c00w** [comment]
Ok. I'll look into it.

**Comment by c00w** [comment]
Should be fixed. If its not in 0.1.9 reopen the issue or open a new one.
