### ISSUE TITLE
Proper round shares reset by GenTarkin

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#207]
Round shares reset based on LP (mine_deepbit role) should be put to diff or reverted to pre LP share count after a non LP pool claims ownership of the block (ex. slush)

(GenTarkin_> thats because the block owner was originally to be thought db....based on LP
GenTarkin_> but later slush api updated which made it actually slush the owner
GenTarkin_> the problem is what your seeing
GenTarkin_> db stats dont reset properly to PRE LP ...
GenTarkin_> they just stay "reset" to 0 acting like its a new block...
GenTarkin_> which causes improper hopping
GenTarkin_> it just improperly kept mining bitclockers once again btw)

**Comment by sdogi** [comment]
I can confirm that this is happening

**Comment by c00w** [comment]
Looking into it.

**Comment by c00w** [comment]
I think its fixed in the latest version 0.1.9. If its not reopen this or make a new issue.
