### ISSUE TITLE
Auth broken with bleeding edge version

### ISSUE THREAD

**Issue by Endeavour79** [c00w/bitHopper#209]
Auth is broken again. Miners can't get work from BH. Error 401

**Comment by sdogi** [comment]
Miners require --auth user,password too now

If you check my fork then I added multi-user support so you can add all your workers and your web interface credentials like:

--auth user1:pass1,user2:pass2

**Comment by Endeavour79** [comment]
thx

**Comment by c00w** [comment]
Fixed
