### ISSUE TITLE
better handling if blockexplorer is down

### ISSUE THREAD

**Issue by bigbeerjr** [c00w/bitHopper#21]
If you can't reach blockexplorer and you try to start bithooper fails bad :(

urllib2.HTTPError: HTTP Error 503: Service Unavailable

Hitting the url by hand give us the following returned from blockexplorer.
ERROR: unknown (probably I'm messing with the code)ERROR: Could not connect to JSON-RPC. Try again in a few minutes. Tell me if it still doesn't work in 30 minutes.

If blockexplorer isn't available then it would be nice to failover to the backup pools and exponentially backoff and retry.

**Comment by c00w** [comment]
Yeah. I just hit this myself. backup pools shouldn't work. I'll hardcode a default difficulty I think for now and fix it later.

**Comment by bigbeerjr** [comment]
workaround == good.

**Comment by c00w** [comment]
well it should try multiple sources. Also on a related note the program doesn't poll for difficulty changes ever... I should fix that as well.

**Comment by c00w** [comment]
Now it actually checks for difficulty changes and handles failure gracefully. Closing the issue.
