### ISSUE TITLE
Make Stats page sort by most recently mined

### ISSUE THREAD

**Issue by hawks5999** [c00w/bitHopper#213]
So current mined pool would be on top of table, most recently mined before current would be next and so on. 
I don't know how the fnsort is being used to sort the pools or I'd take a crack at it...

**Comment by c00w** [comment]
I didn't realize we had any sorting...

**Comment by hawks5999** [comment]
Maybe we don't (it would appear as such :D)

What I was looking at was:
function buildTable(id, items, payload, columns, fnSort, tableCss) 

and 

```
            if(fnSort != undefined) {
                row = rows.sort(fnSort);
```

Ryouiki had in his old html (now in his exp code) the following which sorts by type. But it's a completely different construction of the page:

var sortedKeys = [];
                    for(v in data["servers"]) {
                        if (data["servers"][v]["role"]=="backup")
                        {
                            sortedKeys.push("1:" + v );
                        }
                        else if (data["servers"][v]["cointype"]=="nmc")
                        {
                            sortedKeys.push("5:" + v );
                        }
                        else if (data["servers"][v]["cointype"]=="i0c")
                        {
                            sortedKeys.push("6:" + v );
                        }
                        else if (data["servers"][v]["cointype"]=="ixc")
                        {
                            sortedKeys.push("7:" + v );
                        }
                        else
                        {
                            if (data["servers"][v]["role"]=="disable")
                            {
                                sortedKeys.push("3:" + v );
                            }
                            else
                            {
                                sortedKeys.push("2:" + v );
                            }
                        }
                    }
                    sortedKeys.sort();

```
                for(i in sortedKeys) {
                    var v = sortedKeys[i].split(":")[1];
                    h += "<tr>";
                    var srv = data["servers"][v]

                    var disabled = (srv["role"] == "disable");
```

**Comment by c00w** [comment]
Sweet. So someone needs to define fnSort.

**Comment by c00w** [comment]
Someone defined sort by username. Not sure what the answer should be to this. But... It is now sorted.

**Comment by c00w** [comment]
And sort by time actually sounds like a bad idea since they would be moving around a lot. So we are going to go with sort nby name. I'm closing this issue.
