### ISSUE TITLE
Feature: Hide Inactive and Old users

### ISSUE THREAD

**Issue by hawks5999** [c00w/bitHopper#214]
The User table should hide users not seen in a set time. With recent auth changes i've gone from 10 users to 1 but the old 10 users are still visible in the table even though they were last seen on Thu, 01 Jan 1970 00:00:00 GMT. Would prefer the option or default setting of hiding inactive workers after a time like 8 hours.

**Comment by c00w** [comment]
Ok.

**Comment by c00w** [comment]
Done.
