### ISSUE TITLE
Unhandled exception in thread started by Traceback (most recent call last):

### ISSUE THREAD

**Issue by itstooez** [c00w/bitHopper#215]
http://pastebin.com/cBKYW9v0

**Comment by itstooez** [comment]
I have btcmonkey commented out in my user.cfg, if that makes any difference or helps.

**Comment by sdogi** [comment]
You have that p2p irc thing enabled right? Because I think c00w warned about threading errors yesterday. It needs to be rewritten using twisted

**Comment by itstooez** [comment]
Yes, that's with p2pLP.  Note the tallying of votes.  If this is expected, it can be closed.  Just wanted to post, just in case :)

**Comment by sdogi** [comment]
Well I guess it can be still left open since it is an actual issue, but c00w and probably Gnaget too are aware of this

**Comment by c00w** [comment]
No this is an ircbot issue. I'll fix it.

**Comment by c00w** [comment]
It should be fixed. I'm closing the issue. If it appears again reopen or tell me about it.
