### ISSUE TITLE
Possible method for improving LP based hopping

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#220]
After two days monkeying around with bH just had an idea. Hope it gets tested
at least.
Every time bH subscribes to a pool's LP it reserves a place
in some kind of a list, making the LP calls from pools have, almost, the same lag time
because this "list" is processed at the same velocity by the server with very
little speed changes. For ex. if the initial speed in LP announce from pool would be
5 seconds from the list start you would maintain that lag in server processing
until bH subscribes again to the list, making you reach the maximum lag in
case of announce because you are at the end of the list.
The idea would be to have implemented an internal penalty based on the time from the first
LP announce of a block (penalty 0), after bH already subscribed to all pools, until the last pool's
announce with various seconds of penalty, and sum that to the network lag.

stuff done manually atm

10 pings average to pools (almost stable [variable])
calculate penalty

   pool1_avg_ping/slowest_pool_avg_ping = lp_penalty of pool1
   poolx_avg_ping/slow_pool_avg_ping = lp_penalty of poolx
   slow_pool = lp_penalty:0

put lp_penalty in user.cfg

"internal_lp_penalty" + "lp_penalty" = overall pool LP penalty

**Comment by c00w** [comment]
Definetly would be usefull And a pident based system for changing the penalty as well.

**Comment by paraipan** [comment]
thanks c00w, would hope this one works for the purpose :)
