### ISSUE TITLE
mining deepbit then switched to bclc even without enough votes ?

### ISSUE THREAD

**Issue by itstooez** [c00w/bitHopper#227]
http://pastebin.com/uqdLwwNG

**Comment by c00w** [comment]
You recieved the LP from bclc. So it reset bclc.

**Comment by itstooez** [comment]
But I had both deepbit and bclc on "mine_deepbit" role.  Why would it switch to bclc if there's not enough votes ?  Or am I not understanding the mine_deepbit role properly with --p2pLP enabled ?

**Comment by c00w** [comment]
It switched to bclc because it received the LP from them first and then it didn't switch to deepbit because a majority consensus was not reached. Maybe we should remove the majority consensus requirement but this is expected behavior.
