### ISSUE TITLE
Request by dadittox

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#235]
c00w, 

Please check netstat/tcpdump for persistent connections. Connections are not being reused at all. It's not the problem of if there are lots/few miners. OldConnectionSystem helps, but actually reusing connections would be great. Twisted-11.0.0.

**Comment by c00w** [comment]
Version 2.1 should have this fixed.

**Comment by c00w** [comment]
Wait... Old Connection System makes things better? Thats wrong. The current connection system uses persistent connections. With OldConnectionSystem we were having connections counts of over 100 causing issues on windows...

Either way we are swapping to eventlet to solve these issues.
