### ISSUE TITLE
api disable option

### ISSUE THREAD

**Issue by Clipseza** [c00w/bitHopper#240]
Can we please remove auto api disable or atleast an option to disable it.

Having alot of issues where api's actually update but for some reason goes to disable randomly, quite hard to figure out exactly why so if there is an option just to disable the api_disable feature and just let the api lag and recover on its own.

**Comment by c00w** [comment]
api_disable has nothing to do with lag. Its because of unchanging stats.

**Comment by Clipseza** [comment]
Think you misunderstood me.

I would prefer that if the stats doesnt update it would rather LAG out and try recover eventually rather than api_disable kick in.

Some pools have random update delays at times and api_disable kicks in on these pools and doesnt change back from api_disable
