### ISSUE TITLE
after block reassignment, no new votes being tally'd or seen

### ISSUE THREAD

**Issue by itstooez** [c00w/bitHopper#245]
It appears that...once deepbit is switched to, via p2pLP votes...but then the block is re-assigned to a different pool at some point.  Any new block announces, cause a spam of 1x "unknown work" then multiple "old work".  I'm seeing the tally's for p2pLP on the first announce, but never again after a block is re-assigned.  I noticed in this instance, a deepbit block was re-assigned to Eligius after an API stats call and then after an announce, fail.  Logs below show what I'm seeing in console, but this was after the damage was already done.  Appears to happen with 0.2.1 as well and in the latest commit https://github.com/c00w/bitHopper/commit/066ee5e23c2af1626a5821e8f8c0945854f8919f

bitHopper.py --auth user,pass --p2pLP --scheduler OldDefaultScheduler --threshold 0.90

http://pastebin.com/2UzztuxU

**Comment by simonk83** [comment]
I'm seeing something similar.   Deep is missing a lot of rounds, and I see a lot of "old works" as well.   Logs when I can get them.

**Comment by simonk83** [comment]
Here you go:

http://pastebin.com/tZswFuZL

**Comment by c00w** [comment]
Hmmmm. I'll take a look.

**Comment by c00w** [comment]
I rewrote the LPBot system last night. Is it working better now?

**Comment by itstooez** [comment]
I think this was caused by my dropping of LP polls that we discussed about last night. Tcp timeout stuff.

----- Reply message -----
From: "c00w" reply@reply.github.com
Date: Mon, Aug 22, 2011 12:32 pm
Subject: [bitHopper] after block reassignment, no new votes being tally'd or seen (#245)
To: itstooez@yahoo.com

I rewrote the LPBot system last night. Is it working better now?

##

**Comment by c00w** [comment]
We found an issue with locking. This should be fixed in v2.3
