### ISSUE TITLE
Error in user api for btcg

### ISSUE THREAD

**Issue by yomismo22** [c00w/bitHopper#25]
[21:24:09] Error in user api for btcg
"[Failure instance: Traceback: <type 'exceptions.ValueError'>: Expecting , delimiter: line 1 column 446 (char 446)\n/usr/lib/python2.6/dist-packages/twisted/internet/defer.py:949:gotResult\n/usr/lib/python2.6/dist-packages/twisted/internet/defer.py:936:_inlineCallbacks\n/usr/lib/python2.6/dist-packages/twisted/internet/defer.py:318:callback\n/usr/lib/python2.6/dist-packages/twisted/internet/defer.py:424:_startRunCallbacks\n--- <exception caught here> ---\n/usr/lib/python2.6/dist-packages/twisted/internet/defer.py:441:_runCallbacks\n/home/yo/bitHopper/stats.py:81:selectsharesResponse\n/home/yo/bitHopper/stats.py:13:parse_btcguild\n/usr/lib/python2.6/json/__init__.py:307:loads\n/usr/lib/python2.6/json/decoder.py:319:decode\n/usr/lib/python2.6/json/decoder.py:336:raw_decode\n/usr/lib/python2.6/json/scanner.py:55:iterscan\n/usr/lib/python2.6/json/decoder.py:183:JSONObject\n/usr/lib/python2.6/json/scanner.py:55:iterscan\n/usr/lib/python2.6/json/decoder.py:193:JSONObject\n]"

**Comment by c00w** [comment]
Yeah its broken. I'm going to remove it from the callbacks until it works.

**Comment by c00w** [comment]
btcg dropped all of their stats its disabled in the current version so I am closing the issue.
