### ISSUE TITLE
patch for time sliced based pool selection

### ISSUE THREAD

**Issue by flower1024** [c00w/bitHopper#26]
atm it selects new server when a new block is found or after 20 minutes
with btcguild gone i think 20 minutes is a good time - but it can be changed (keep it bigger to reduce stales)

patch is here:
http://www.k1024.de/diff

(can anybody tell me howto make pull requests? i am really new to this)
this is based on current master

**Comment by c00w** [comment]
Hi,

Its late and I read your post on the forum. What does this do though? Its hard to gain comprehension from diffs and an executive summary would really help

Also did you disable all the shareresponses on purpose?

Oh and this is sort of rambling but I'm doing a crazy class rewrite hopefully tonight. You modifications shouldn't be affected though.

**Comment by c00w** [comment]
http://help.github.com/send-pull-requests/

**Comment by flower1024** [comment]
atm i am at work. but a short note:

i try to archive this:
i want to switch pools on random base after a miner submits a share. i think thats better if two pools found a block very close to each other

i archvieved this:
every time a time-window ends (currently ten minutes) or a new block is found all pools are sharing a "slice" in a ten minute time frame (please see the version with the small web-interface in the forums: www.k1024.de/dev.7z).
so shares are evenly distributed if two pools are e.g. at 25%

missing is this:
it doesnt count pool hashrate - which is important for time slicing
i does not begin with the biggest slice. atm it starts from the beginning.
i need better backup pool handling (atm it slowly goes to the backup pool if any of the normal pools goes to 30% (or greater). 30% means: round_shares / difficulty \* 100

i'll come back to you this evening with a push request. and it will fix some of the things above.
next is patching bitcoin itself to detect btcguild rounds :)

**Comment by c00w** [comment]
Ah. That makes sense. I did just rebuild the code structure though so it'll be interesting for you to merge you changes upstream. If you get a pull request up either release your code into the public domain or give me the copyright so I don't have to worry about permission when I change the license.

**Comment by flower1024** [comment]
you can do with the code whatever you want.
i'll make a push request this evening (maybe with a few changes regarding pool-hashrate and backup-pools)

**Comment by streblo** [comment]
Hello,

If I understand this correctly, I think your addition will lower the variance of returns slightly, but not have any affect on the expected returns. I'm at work right now, but I would like to discuss it further either in here or on the forums (I still don't have proper non-newbie privledges necessary to post in the thread).

IMO, it adds unnecessary complexity for a small decrease in variance. Can we please add it with a switch, such as --time-slicing=[yes|no] ?

If two pools are both at X% and both are standard proportional pools, the expected return on shares is equal. Due to time-lag in pulling stats, one should choose the pool with a lower hashrate for highest return (although if hoppers are a large portion of the hashrate, this is unstable and will cause the hashrate, #workers, and optimal pool to oscillate unstably). 

Cheers

**Comment by flower1024** [comment]
Hello,

Am 18.07.2011 19:15, schrieb streblo:

> Hello,
> 
> If I understand this correctly, I think your addition will lower the variance of returns slightly, but not have any affect on the expected returns.

I think it will have an affect.

example 1: two pools found a block next to each other with the same 
speed. original bithopper will stick with the one with the lower shares. 
that could be good or worse.

if it's good you earn much more; if its bad you loose the half.

example 2:
a pool with a very high hashrate finds a block righte before a small pool.

original bithopper will switch to the small one. it would be better to 
try to submit shares to the fast pool and - after that - continue with 
the small one.

^^ thats my impression. please correct me if i am wrong

I'm at work right now, but I would like to discuss it further either in 
here or on the forums (I still don't have proper non-newbie privledges 
necessary to post in the thread).

> IMO, it adds unnecessary complexity for a small decrease in variance. Can we please add it with a switch, such as --time-slicing=[yes|no] ?

^^ bithopper itself is not from me.
so if you don't want that slicing right now, just stick with the 
original version.

if it gets merged (i hope so), i prefer a switch too (i would even 
suggest pluggable modules through c00w's planned website - so if you're 
watching you can change the strategy on the fly)

> If two pools are both at X% and both are standard proportional pools, the expected return on shares is equal. Due to time-lag in pulling stats, one should choose the pool with a lower hashrate for highest return (although if hoppers are a large portion of the hashrate, this is unstable and will cause the hashrate, #workers, and optimal pool to oscillate unstably).

my recent version (see attachment; as i got ill i was not able to 
publish it right now. especially the "ghash pool bonus" is not well 
tested (i should write a program to simulate pool stats)) has a few 
improvements:
- bonus for BIG pools (i now; you don't like that. but big pools goes 
  to 40% diff very fast, so i think its a good idea to catch up)
- tries to stay longer at one pool (means: if after a ten minute round 
  the same pool got a new time slice it stays there)
- tries to start the longest (means most profitable) slice as soon as 
  a new block is found, a pool lags or another slice finished

thank you for you thoughts. i just think we need a long-time sim here - 
and i am still planning to work on a bitcoin patch to better detect btc 
guild / deepbit blocks

> Cheers

**Comment by c00w** [comment]
I like the idea of slicing between pools. I am worried about higher reject rates and LP issues. Assuming we get the code into a decent merge state it will be merged, probably as a command line switch. If flower doesn't do the merge himself I probably will at some point anyway although with a different technique.

**Comment by flower1024** [comment]
my reject rate is at 1-3% (after 10hours; but i restarted the proxy a few times).

i use it with three miners:
350mh / diablo (old version, lp does not seem to work at all [miner; not proxy])
2x80mh guiminer (lp working flawlessly)

my diablominer sometimes gets stuck (after 6h-20h). but i think its more a diablo problem (i really hate my main card. this old diablo is the only miner working with it with more than 350mh)

stuck means: hashrate goes down to zero (which is a good thing sd my failover throws in - also pointed to this hopper)

**Comment by c00w** [comment]
Cool.

**Comment by flower1024** [comment]
YOU are cool.
tried this in c# and my miner lost 20mhash and got WAY more rejects. just love your lp/getwork code :)

**Comment by c00w** [comment]
Well thanks. I think its a giant disaster and needs to be rewritten again. But its a lot better than it was a week ago. A lot of it is twisted being completely amazing though.

I'm sort of eager to see your pull request though. I like the idea of mining two pools at once.

**Comment by c00w** [comment]
I never got a pull request but I'll move the diff in manually. I am assuming that saying I can do what I want is equivalent to you realising the work into the public domain. I'm sending you a pm on the forums as well. If that is not the case please tell me.

**Comment by echiu64** [comment]
Merged into ryouiki's fork in my tree for now: https://github.com/echiu64/bitHopper

**Comment by c00w** [comment]
A similar system is finally merged in. Closing the issue now.

**Comment by echiu64** [comment]
Thanks, I was working out the final bugs on my version, looks pretty similar, I'll have a look at your implementation!
