### ISSUE TITLE
Error new version by EskimoBob

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#260]
any ideas what causes this error (new version) http://pastebin.com/Kx00Jdy8

**Comment by c00w** [comment]
Pipes are getting broken. not sure why. Is this being displayed in non debug mode?

**Comment by paraipan** [comment]
will ask EskimoBob, dunno if it checks git

**Comment by c00w** [comment]
This is an issue with the wsgi server. I have filed a bug report.
