### ISSUE TITLE
UnboundLocalError: local variable 'username' referenced before assignment

### ISSUE THREAD

**Issue by sdogi** [c00w/bitHopper#261]
18:10 < Clipse> Traceback (most recent call last):
18:10 < Clipse> File "C:\bitHopper\eventlet\wsgi.py", line 336, in handle_one_response
18:10 < Clipse> result = self.application(self.environ, start_response)
18:10 < Clipse> File "C:\bitHopper\website.py", line 168, in handle_start
18:10 < Clipse> return site.handle(env,start_response)
18:10 < Clipse> File "C:\bitHopper\website.py", line 139, in handle
18:10 < Clipse> return self.bitHopper.work.handle_LP(env, start_response)
18:10 < Clipse> File "C:\bitHopper\work.py", line 186, in handle_LP
18:10 < Clipse> self.bitHopper.log_msg('LP Callback for miner: '+ username)
18:10 < Clipse> UnboundLocalError: local variable 'username' referenced before assignment

**Comment by Clipseza** [comment]
I should note, this is after moving latest bithopper over to windows machine(which had none of the issues Ive had on ubuntu) and then this problem caused bithopper to simply die.

**Comment by sdogi** [comment]
This seems to be fixed now. Could you confirm Clipseza?

**Comment by c00w** [comment]
I fixed it this morning.
