### ISSUE TITLE
BUG: UPSTREAM: WSGI server tries to finish closed connections.

### ISSUE THREAD

**Issue by itstooez** [c00w/bitHopper#262]
Looks like this happens on the LP Callback for miner

http://pastebin.com/LaSMRK2h

error: [Errno 10053] An established connection was aborted by the software in your host machine

**Comment by c00w** [comment]
Yeah, I need to doublecheck that this doesn't leak connections but it should be fine.

**Comment by c00w** [comment]
This is an issue with the wsgi server. I have filed a bug report.

**Comment by Transisto** [comment]
I got the exact same thing (line 80 ... ... 269) about 6 time in one minute. 

(usually less frequent)

**Comment by c00w** [comment]
What miner are you using?

**Comment by Transisto** [comment]
I'm using BAMT's phoenix, and a few cgminer

**Comment by c00w** [comment]
Should be fixed as we moved to gevent.
