### ISSUE TITLE
    if self.blocks[block]['_owner'] == None or self.blocks[block][server] < self.blocks[block][self.blocks[block]['_owner']]: KeyError: 'deepbit'

### ISSUE THREAD

**Issue by itstooez** [c00w/bitHopper#275]
Was running pretty well...

http://pastebin.com/wQxh4fKw

**Comment by c00w** [comment]
I don't know why this appeared. lpbot might have broken something. I'll see if I can make it reappear.

**Comment by itstooez** [comment]
Looks to have happened again...with btcpool24, which I have commented out of user.cfg

http://pastebin.com/FFdVXwPU

**Comment by c00w** [comment]
Oh shoot. I bet this has something to do with dynamically reloading configuration files...

**Comment by c00w** [comment]
I'm closing this issue because we now have sanity checks.
