### ISSUE TITLE
donation pool forced?

### ISSUE THREAD

**Issue by flower1024** [c00w/bitHopper#279]
hi c00w,

i really like you donation pool idea.
i already mined for you at eligius a few weeks ago.

thatfor i have disabled it right now. but my bithopper is still submitting shares to it. i have 112 shares submitted since the last 5 hours....

please make donations by choice - and not forced

btw: is donation possible through ars? i dont like eligius anymore since i know they put prayers in the coinbase.

**Comment by c00w** [comment]
Change the field:
percent: 1 to percent: 0.

Thats the magic ticket. I'll add in a check for a disabled pool soon.

**Comment by c00w** [comment]
Yeah donation is possible through ars. You can use the eligius address or I could set up an account which uses the address. I'm overloaded now but I can set it up soon.

**Comment by flower1024** [comment]
ok, thanks for the clarification.

**Comment by c00w** [comment]
I fixed the code so the disable role for donations disables donations.

**Comment by c00w** [comment]
I just created an ars username for donations with username c00w.donation and password donation. I'll update the pool.cfg to include it as an option in a comment.

**Comment by c00w** [comment]
Added.
