### ISSUE TITLE
Ideea by zoomer

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#284]
how about refactoring the way bH treats roles so that the type of coin is independent of the pool's role? it'll allow sc as backup, etc

**Comment by c00w** [comment]
Definetly possible and the right way to do it. We just haven't written it like that.

**Comment by paraipan** [comment]
the type of coin is set by the pools you mine and you already can use "backup", "backup_latehop", "mine_charity" with those because these roles don't mind about difficulty or the coin you use them for. The only roles that would have to be implemented would be "mine_slush" and "mine_deepbit" to work for other coins (chains)

**Comment by c00w** [comment]
Good point. Backup, and backup_latehop are pool independent.

**Comment by paraipan** [comment]
thanks, yesterday i was hacking away bH to implement this and just realized it was pointless for the backup roles
