### ISSUE TITLE
New role backup_slice

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#288]
How a new role backup_slice would be to slice equally, or user adjustable, between backup pools ?
We could use various pools in different blockchains and slice between them as backup. Just realised we lock one pool at a time for this purpose. I would surely like to slice for ex. 25% to scc, 50% to eligius and 25% to some other pplns pool. My coding skills can't help me with this so I hope someone picks it up if it seems viable

**Comment by c00w** [comment]
We can do it. Its a low priority however.

**Comment by paraipan** [comment]
ack thanks

**Comment by c00w** [comment]
I'm closing this issue and moving it into the backup hopping issue.
