### ISSUE TITLE
Support for rollntime

### ISSUE THREAD

**Issue by dadittoz** [c00w/bitHopper#291]
It would be nice to add support for rollntime, so this miner modification could work: https://bitcointalk.org/index.php?topic=38629.0

I've seen commented code at line 152 of work.py. I assume you already thought of this. Maybe this can be implemented.

**Comment by c00w** [comment]
Support is easy. I'm not sure if it would change the merkle root though. Need to investigate it so we don't get thrashed shares.

**Comment by dadittoz** [comment]
This could be pushed as an option disabled by default. If you add some debug log to check if shares get thrashed because of this I will be happy to provide you logs.

**Comment by c00w** [comment]
I double checked and it doesn't disable anything. I'll set it up.

**Comment by c00w** [comment]
I think I just added it. Can you test it?

**Comment by dadittoz** [comment]
I am sorry, I see no commits pushed that contain anything about it. Or is there some specific branch/fork?

**Comment by dadittoz** [comment]
I am sorry, it's in v0.2.4.4, not master. Trying it now.

**Comment by dadittoz** [comment]
Looks like I get a lot of rejects when server switches. How does bithopper know to what server should it submit the shares to when miner with rollntime submits?

**Comment by c00w** [comment]
It does it based on the merkle root. Which shouldn't actually be affected by rollntime. I can turn on getwork debugging if you want to try and figure out what happened? I can also turn on reject reason debugging.

**Comment by dadittoz** [comment]
Debugging and knowing reason would be nice.

BTW, I see now this. My account at bcpool was temporary bannded (low efficiency somehow). I am seeing this in logs

[21:09:01] DEBUG: Error in json decoding, Server probably down
[21:09:01] DEBUG: bcpool
[21:09:01] DEBUG: [html>[title>401: Unauthorized[/title>[body>401: Unauthorized[/body>[/html>
[21:09:01] DEBUG: Error in json decoding, Server probably down
[21:09:01] DEBUG: bcpool
[21:09:01] DEBUG: [html>[title>401: Unauthorized[/title>[body>401: Unauthorized[/body>[/html>
[21:09:01] DEBUG: Error in json decoding, Server probably down
[21:09:01] DEBUG: bcpool
[21:09:01] DEBUG: [html>[title>401: Unauthorized[/title>[body>401: Unauthorized[/body>[/html>
[21:09:01] Lagging. :bcpool
[21:09:01] DEBUG: Error in json decoding, Server probably down
[21:09:01] DEBUG: bcpool
[21:09:01] DEBUG: [html>[title>401: Unauthorized[/title>[body>401: Unauthorized[/body>[/html>
[21:09:01] DEBUG: Error in json decoding, Server probably down
[21:09:01] DEBUG: bcpool
[21:09:01] DEBUG: [html>[title>401: Unauthorized[/title>[body>401: Unauthorized[/body>[/html>
[21:09:01] DEBUG: Error in json decoding, Server probably down
[21:09:01] DEBUG: bcpool

But bitHopper won't switch to another pool and continously sits bcpool @0MHash. There no other slices though, it just won't switch to backup.

I replaced < with [. It won't be displayed the other way.

**Comment by c00w** [comment]
Um thats bad... I'll take a look.

**Comment by dadittoz** [comment]
I invsetigated the problem with rejects. It may happen that bitHopper is fine. It's just "Flexible mining proxy" considers the share to be rejected if the "result" field of reply is set to "false". I see no rejects on miners, they seem to be fine with result set to false. It's only in Flexible mining proxy interface. 

Could you please advise me what server reply should be considered as a real "reject"?

**Comment by dadittoz** [comment]
Shouldn't this line

```
    if header.lower() not in ['x-roll-ntime']:
```

be changed to

```
    if header.lower() not in ['x-roll-ntime','nonce-range']:
```

by the way?

**Comment by c00w** [comment]
nonce-range is not a header. Its an extra field in the supplied json data. I'll double check though.

**Comment by c00w** [comment]
And real rejects are a response from the server in the http body as FALSE. BitHopper records those as does your miner.

**Comment by dadittoz** [comment]
so it's just

```
false
```

And say this result

``````
{"id": 1, "result": false, "error": null}
``` is an accepted message?
``````

**Comment by dadittoz** [comment]
I made a test, and can answer myself :) Yes, it's exactly how it works. At least for phoenix miner. So, rollntime works fine on bitHopper end. I guess this commit can be pushed and issue closed. 

Switching to backup pool in case the only one pool that has been sliced lags out would be nice, but I guess it's off the topic here.

**Comment by c00w** [comment]
Okay.
