### ISSUE TITLE
mine_deepbit different coin stat reset on new block found

### ISSUE THREAD

**Issue by Clipseza** [c00w/bitHopper#295]
Can we please have a change made so that one coin wont reset stats on another.

For example: Im mining mining with mine_deepbit and deepbit hits a block then after a few percentage mining a solidcoin pool hits a block and then the mine_deepbit pool gets its shares reset as if it was a wrong block prediction.

Since the coins are seperate networks, clearly they should not interfere with each other since mine_deepbit should just be used for bitcoins atm.

Perhaps have seperate naming scheme if people want to use the LP prediction on any of the forks without interfering with each other, something like lp_btc , lp_ixc , lp_scc could work just as well .

**Comment by c00w** [comment]
Yes. You are correct. Currently we should only be using LP for btc pools. I'm not sure why its triggering on other pools.

**Comment by paraipan** [comment]
eh, i think what clipse wants to say is that mine_deepbit works well for btc's and also the pool that put it's name but when some other normal api resets, different blockchain pools too, the deepbit shares revert to where they were before. This is a feature but it should not account mine_xxx pools i guess

**Comment by Clipseza** [comment]
thats correct parainanakos, the resets should only affect pools within same lp_ role so if people do want to use lp_ for a different coin the resets for that particular coin would only reset based on another pool with same coin.

**Comment by c00w** [comment]
Oh... I'll see if I can fix that.

**Comment by c00w** [comment]
I added the cointypes.

**Comment by c00w** [comment]
And after looking over my changes I realized I correctly handled LP's from different servers.

**Comment by c00w** [comment]
So it should work now. For all cointypes.

**Comment by paraipan** [comment]
thanks c00w
