### ISSUE TITLE
numpy

### ISSUE THREAD

**Issue by hpcgam** [c00w/bitHopper#311]
please add in readme: "install numpy"

or in sha256.py 
try:
  import numpy
except ImportError:
  raise ImportError

**Comment by c00w** [comment]
Um. Its a plugin error. On my machine it smoothly fails to load the poclbm plugin. Is it different on your machine?

**Comment by hpcgam** [comment]
On Wed, Aug 31, 2011 at 11:35 PM, c00w
reply@reply.github.com
wrote:

**Comment by c00w** [comment]
Okay. The numpy error shouldn't have effected anything. I did just fix a huge bug with getworks being corrupted.

**Comment by c00w** [comment]
I'll close this issue. I also added some instructions to the readme for ubuntu users.

**Comment by hpcgam** [comment]
On Wed, Aug 31, 2011 at 11:45 PM, c00w
reply@reply.github.com
wrote:

> Okay. The numpy error shouldn't have effected anything. I did just fix a huge bug with getworks being corrupted.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/c00w/bitHopper/issues/311#issuecomment-1957927

ok, thanks )
