### ISSUE TITLE
Feature: Switch Coins based on profitability.

### ISSUE THREAD

**Issue by EskimoBob** [c00w/bitHopper#322]
Feature request: 
Can you please add a profitability calculation before switching to alternative coin. Please make switch threshold configurable. 
No point in switching and mining the coin X, if it's at 0.70 of profitability.  BTC is always 1.   

Thank you

**Comment by c00w** [comment]
Yes. We want to do this.

**Comment by c00w** [comment]
This is now implemented in bleeding edge. I'm closing the issue.
