### ISSUE TITLE
problem switching between roles

### ISSUE THREAD

**Issue by Clipseza** [c00w/bitHopper#332]
With more recent changes it doesnt switch to different roles when they have lowest shares.

It would stay at mine_scc and switch between lowest shares within the specific role until there is no <threshold shares then only will it move from the role to another role with <threshold shares.

I think this is since the new coin changes.

**Comment by sdogi** [comment]
May be fixed now, there was certain bug that probably caused all sorts of weird issues while getting difficulty for various coins/switching between pools.

Please pull my latest or wait when c00w gets back and merges my patches and then write in here if you still have issues.

**Comment by c00w** [comment]
This should be working now.
