### ISSUE TITLE
Error on first start of BH - latest version

### ISSUE THREAD

**Issue by simonk83** [c00w/bitHopper#341]
G:\Handies\bitHopper\bitHopper\peak__init__.py:1: UserWarning: Module eventlet
was already imported from G:\Handies\bitHopper\bitHopper\eventlet__init__.pyc,
but c:\users\simon\appdata\roaming\python\python27\site-packages is being added
to sys.path
  **import**('pkg_resources').declare_namespace(**name**)
G:\Handies\bitHopper\bitHopper\peak__init__.py:1: UserWarning: Module webob was
 already imported from G:\Handies\bitHopper\bitHopper\webob__init__.pyc, but c:
\users\simon\appdata\roaming\python\python27\site-packages is being added to sys
.path
  **import**('pkg_resources').declare_namespace(**name**)

**Comment by Endeavour79** [comment]
C:\bithopper\peak__init__.py:1: UserWarning: Module eventlet was already impor
ed from C:\bithopper\eventlet__init__.py, but c:\users\admin\appdata\roaming\p
thon\python27\site-packages is being added to sys.path

same for me

**Comment by c00w** [comment]
Yes. Peak does something very bizarre. I'm trying to debug it now. It doesn't break anything though.

**Comment by c00w** [comment]
I fixed it. Should be hidden now.
