### ISSUE TITLE
SimpleSlicer & Lesser pool shares

### ISSUE THREAD

**Issue by itstooez** [c00w/bitHopper#342]
Currently with the SimpleSlicer...it appears that it looks primarily only at pools with the smallest slice time.  My issue lies when multiple pools can be sliced.  It appears that the pool's share count are not taken into account when choosing what pool to slice at and also that when multiple pools exist they are always sliced in the same order.

When I have 5 pools to slice, they slice the same 5 pools, in the same order, everytime...when a new block apears from deepbit (mine_deepbit).  The only problem is, the slice time resets to 0 on all pools (good) and then it starts slicing that same order again...but doesn't get to deepbit until last (or nearly 18%, this is bad).

Can there be a check within slicing, so that from the available pools to slice from, it will choose the pool with smallest slice time && smallest shares ?

**Comment by c00w** [comment]
Um. Its actually not supposed to reset. I'll doublecheck it. But the best thing to do is to use the more advanced altslicer if you want slicing behavior.

**Comment by itstooez** [comment]
Resetting to 0 is fine for slicing; it just needs to slice between time and shares, not just time.

**Comment by c00w** [comment]
If it didn't reset to zero deepbit would get the most slicing.

**Comment by c00w** [comment]
This should be fixed currently.
