### ISSUE TITLE
Feature: Fancy Logging Plugin

### ISSUE THREAD

**Issue by echiu64** [c00w/bitHopper#351]
Either we enhance or adopt a logging framework.

Use "cat" keyword in various loggers, such as LP, getwork, etc.
In log_msg/log_dbg/log_trace, we check bh.cfg for any categories that should be "suppressed"

e.g. if we had log_msg("get work [hash]", cat="getwork")

We could then do something like:

``` python
def log_msg(msg, **kwargs):
    items = config.items("log.categories.suppress")
    for k in items:
        if k[0] = kwargs.get('cat'): 
        # suppress message
        return
    # proceed as usual

```

Thoughts? Would make it easier to suppress messages in a generic manner vs one off configurations

**Comment by c00w** [comment]
We want to write a logging.py module. Someone was talking about doing it and I haven't heard much since.

**Comment by echiu64** [comment]
I probably mentioned that. The builtin logging module looks pretty complete, may as well leverage that:
http://docs.python.org/library/logging.html

**Comment by c00w** [comment]
That looks usefull. We also want to move the share information out into a seperate function not in work.py

**Comment by echiu64** [comment]
Can maybe add a hook like rpc.request.data and then do a notify(data,server)
and then a new plugin could manage the display, the plugin can be turned
on/off and have it's own "logger" under the python logging system.

**Comment by c00w** [comment]
Yes. We want to add hooks for everything.

**Comment by simonk83** [comment]
Has this got anything to do with why stuff isn't shown in the console anymore (getworks/submits etc)?  I'd really like to renable that stuff if anyone can tell me how :D

**Comment by echiu64** [comment]
No, for rpcwork logging, it was moved into the rpcworklog plugin, so make sure that's enabled if you want to show any rpcwork output. Should be enabled by default, perhaps your bh.cfg has plugin mode = manual, so you need to explicity enable rpcworklog plugin.

e.g.

``` python
[plugins]
test = True
backdoor = True
apiangel = True
poclbm = False
rpcworklog = True

# Probably need the one below in the future
lpbot = False
```

**Comment by simonk83** [comment]
Thanks mate.  rpcworklog was missing from my config (and the default it seems)....

**Comment by c00w** [comment]
We've transitioned over to logging.py. So we have less fine grained detail but since it prints the source you can filter the log items pretty well. I'm going to close this issue.
