### ISSUE TITLE
Feature: Backup Pool Hopping

### ISSUE THREAD

**Issue by organofcorti** [c00w/bitHopper#358]
I'd like to hop backup pools to reduce variance. Could we get a backup role that hops to the backup with the lowest total shares?

**Comment by paraipan** [comment]
hey organof dunno if this applies https://github.com/c00w/bitHopper/issues/288 , care to take a look... ?

**Comment by organofcorti** [comment]
Not sure, para similar i guess. I haven't modelled XXPPS hopping yet, but from what I've read hopping at the start of a round will reduce variance. I don't know what the hop off point is or even if it makes sense to define one. If you sliced you have to have a hop off in mind. What I'd like is to mine back up at the pool with the smallest number of shares.

**Comment by paraipan** [comment]
ah k the exact opposite of backup_latehop

**Comment by c00w** [comment]
We can do it.

**Comment by organofcorti** [comment]
sweet, thanks guys.

**Comment by c00w** [comment]
Um It's now implemented. Huzaaah! earlyhop is probably what you want although slice will probably reduce variance most.

**Comment by organofcorti** [comment]
Great! Will try next time i can update.
