### ISSUE TITLE
bithopper.py line 379,380

### ISSUE THREAD

**Issue by rkozola** [c00w/bitHopper#36]
I think the below lines are causing a problem that you are trying to track down.

for k in bithopper_global.pool.get_servers():
bithopper_global.pool.get_servers()[k]['user_shares'] = 0

**Comment by c00w** [comment]
Yep. I'm an idiot.

**Comment by c00w** [comment]
And its committed. Thank you very much.

**Comment by c00w** [comment]
Its fixed and it works. Thank you very much.
