### ISSUE TITLE
Feature: Autoupdate pools.cfg

### ISSUE THREAD

**Issue by dadittoz** [c00w/bitHopper#361]
Seeing all minor changes and fixes to pools I would like to suggest to autoupdate pools.cfg file. We could download it by HTTP from github. I suggest following features:
1) Configure writable temporary directory "autoupdate_dir" in bh.cfg. Default is /tmp or whatever path is in windows for temporary files.
2) Configure refresh time for pools.cfg. Set default to 0, in case use has modified pools.cfg and we don't want it overridden
3) When loading configuration first check for for the pools.cfg in autoupdate_dir
4) md5 check file before downloading and after. In case the file changed reload config.
5) This could be done with new plugin system to further enhance it abilities.

**Comment by c00w** [comment]
We can do this.

**Comment by c00w** [comment]
Or at the very least we can print a warning if it is different from github's. I can add a plugin pretty easily.

**Comment by c00w** [comment]
Its added. difficulty.py autoupdates its config files and everything else will be moved over soon. However we're moving to new config file system so its a good but different solution.
