### ISSUE TITLE
Feature: Extend plugin framework

### ISSUE THREAD

**Issue by echiu64** [c00w/bitHopper#368]
1) Create base Plugin class for all plugins to extend
2) Base class will have methods:

``` python
    def isReloadable:
        return True/False
    def isStoppable:
        return True/False
    def start:
        hook('plugin.x.start')
        # start plugin
    def stop:
        hook('plugin.x.stop')
        # stop plugin
    def reload:
        hook('plugin.x.reload')
        # reload plugin configuration
```

Hooks are added in so that any dependent plugin/system can be notified when a plugin starts/stops.

**Comment by echiu64** [comment]
Delagger and lpbot are candidates to be moved into plugins

**Comment by c00w** [comment]
I like moving lpbot to be a plugin. Moving the delagger to be a plugin sounds like a bad idea since someone might disable it.

**Comment by c00w** [comment]
lpbot is moved.

**Comment by echiu64** [comment]
That was quick!

**Comment by c00w** [comment]
I'm actually getting rid of plugins. Not a lot of people wrote them and they tended to be much to complicated. Plus the callback hooks were quite hard to debug.
