### ISSUE TITLE
wrong code?

### ISSUE THREAD

**Issue by hpcgam** [c00w/bitHopper#373]
in sheduler.py:

```
def mine_lp_force(self, lp, body, server, block):
    for server in self.bitHopper.pool.get_servers():
```

may be: ?
    def mine_lp_force(self, lp, body, server, block):
         servers=self.bitHopper.pool.get_servers()
         for server in servers:

**Comment by c00w** [comment]
The above code should work. The second way is probably a little more readable.

**Comment by hpcgam** [comment]
in last commit tgis fixed
