### ISSUE TITLE
Mhps on stats webpage decimal place error

### ISSUE THREAD

**Issue by organofcorti** [c00w/bitHopper#38]
The Mhps on the stats webpage (currently bitclockers) is reading one tenth what it should - 100 Mhps instead of 1000 Mhps. I've done the sums based on the shares obtained per unit time, and I'm def still at 1000 Mhps.

Even so c00w - awesome work.

**Comment by c00w** [comment]
Yeah. I'll fix it.

**Comment by c00w** [comment]
Its fixed. Hopefully.
