### ISSUE TITLE
New role for mine_slush

### ISSUE THREAD

**Issue by organofcorti** [c00w/bitHopper#390]
Hey guys,

since 0.147x is no longer applicable, is there anyway we can change the role to:

```
     mine_slush   = 0.435 - 503131/(1173666 + c*hashrate)
```

c is the only variable (300 for slush, 550 for btcmine) and hashrate = moving average hashrate from pool stats (see this: http://hoppersden.info/entries/19-How-to-hop-4)

cheers
ooc

**Comment by c00w** [comment]
Is this independent of difficulty?

**Comment by organofcorti** [comment]
Short answer: Yes.

Long answer: the only time the function would be affected by difficulty is if it changes mid-round, and only because of the amount of extra shares it took to find the block, and only then if block finding happens before shares decay completely. It's negligable :)

**Comment by c00w** [comment]
ok. I'll change mine_slush to mine_c and have a c variable using that formula.

**Comment by organofcorti** [comment]
Great! I know it only affects a couple of  pools, but it affects the efficiency of them quite a bit.

**Comment by c00w** [comment]
This is hopoff percent? Or shares.

**Comment by c00w** [comment]
I assumed it was percent and pushed the result. Hopefully it works.

**Comment by organofcorti** [comment]
hopoff percent. output is a fraction of difficulty.

**Comment by c00w** [comment]
This has been merged. mine_c is the new role. mine_slush is usable for backwards compatability.
