### ISSUE TITLE
mine_c

### ISSUE THREAD

**Issue by organofcorti** [c00w/bitHopper#394]
actually, not a %, sorry if I confused you. The function outputs a number between 0 and .435 and is a fraction of difficulty of total shares submitted to pool. Eg if function output is 0.2, hop off is at 0.2*difficulty. I think what I wrote might have indicated the output was a number between 0 and 43.5, which it doesn't.

Also, hashrate has to be based on either a rolling average for the pool in Ghps, or total pool shares/total duration in seconds converted to a hashrate in Ghps. Sorry if I wasn't clear.

**Comment by c00w** [comment]
Um. Thats what we do now:

``` python
    if info['role'] == 'mine_c':
            #Checks if shares are to high and if so sends it through the roof
            #So we don't mine it.
            c = int(info['c'])
            hashrate = float(info['ghash'])
            hopoff = difficulty * (self.difficultyThreshold - 503131/(1173666 + c*hashrate))
            if shares > hopoff:
                shares = 2*difficulty
```

**Comment by organofcorti** [comment]
```
        hopoff = difficulty * (self.difficultyThreshold - 503131/(1173666 + c*hashrate))
```

should be

```
        hopoff = difficulty * (0.435 - 503131/(1173666 + c*hashrate))
```

with other chosen values the hop point will will either be too high or too low or even negative.

For 

```
        hashrate = float(info['ghash'])
```

ghash should be an average since start of round. Is there an easy way to store a rolling mean for 'ghash' is the average since start of round? If not it's only going to be a problem for pools where hashrate varies by a large % in the round, so it's probably negligable.

**Comment by c00w** [comment]
Okay. I'll change the diff threshold to 0.435. ghash should be a rolling average. I think.
