### ISSUE TITLE
Pool Share/GHash/Duration Indentation

### ISSUE THREAD

**Issue by itstooez** [c00w/bitHopper#397]
http://pastebin.com/TpFAn4gG

Indentation is still off a bit, appears for rfc and mmf in above pastebin.

**Comment by paraipan** [comment]
i see that too, little annoying thing
don't know if this is related but could happen because rfc json is wrapped in a unusual way ?

{"poolstats":{"hashrate_unit":"GH/s"...

our  api_key: poolstats,round_shares

**Comment by itstooez** [comment]
http://pastebin.com/k1kMKr25

Still occurring.

**Comment by c00w** [comment]
Should be fixed.

**Comment by paraipan** [comment]
ack
