### ISSUE TITLE
still update disabled server

### ISSUE THREAD

**Issue by ryouiki** [c00w/bitHopper#4]
still update disabled, not interested server
how about

``` python
if options.disable != None:
    for k in options.disable:
        if k == 'eligius':
            print "You just disabled the backup pool. I hope you know what you are doing"
        if k in servers:
            del servers[k]
        else:
            print k + " Not a valid server"
```

instead of using 'info' flag?
this modification will make things easier

**Comment by c00w** [comment]
Hmm. Maybe. The idea was to disable them from being hopped to because of high latency, opertator prerence etc..

Oh and yeah the info tag is a hack. It is supposed to be a role tag with roles as hop, info, backup.
I'll add this to my pending rewrite of everything for clarity.

**Comment by c00w** [comment]
Well I cleaned up the code a fair amount. I'll do it some more and soon this should actually disable. I'll probably need a role setter command as well.

**Comment by c00w** [comment]
Currently it should actually be disabled.

**Comment by c00w** [comment]
I'm going to close this issue.
