### ISSUE TITLE
pools.cfg and regex

### ISSUE THREAD

**Issue by organofcorti** [c00w/bitHopper#40]
How do you do 'replace',eg:

 def polmine_sharesResponse(self, response):
        round_shares = int(re.search(r"stkich:</th><td>[ 0-9]*</td>", response).group(0)[16:-5].replace(' ',''))
        self.UpdateShares('polmine',round_shares)

in the new system? I don't have either the regex or python chops to figure out how to get the 'replace' in to either pools.cfg or pools.py.

If you can add an option for that in to config file - and I think replacing spaces with commas etc is going to get to be a common short term solution for prop pools to reduce hopping.

**Comment by c00w** [comment]
Sure. I'll ad a api_strip method for re. So you can go: api_method:re
api_key:stkich:[ 0-9]*
api_index 16,-5
api_strip:' '

**Comment by c00w** [comment]
Meant to hit comment. My bad.

**Comment by c00w** [comment]
And its added. 
api_strip: ' '
It has to be in single or double quotes. Its used for triple right now and if you get polmine working please post it with a copyright release.

**Comment by c00w** [comment]
Oh and polmine is in pool.cfg.default

**Comment by organofcorti** [comment]
both work now - just as you had them in pool.cfg.default (with my passwords though). There's no need for a copyright release - it's not my code by ryouiki's, and you already have an arrangement with him.

cheerss

ooc
