### ISSUE TITLE
Blank stats page with latest v0.2.5.2-45-gd7bdc98

### ISSUE THREAD

**Issue by simonk83** [c00w/bitHopper#407]
BH Version:  v0.2.5.2-45-gd7bdc98

OS:  Win 7 x64

Miner:  Cgminer 2.0.4

Python:  2.7.2 (Activestate, not sure if that overrides the version or anything)

Stats page only shows the currently mined pool at the top, the disabled/enable stuff, and the config buttons.  Nothing else.

I'm don't have any extra coin types enabled anywhere (due to cgminer crapping out if I do), not sure if that matters.

**Comment by c00w** [comment]
This is fixed for most people. We still haven't figured out what went wrong with simonk83...

**Comment by simonk83** [comment]
OK, seems a couple more people are seeing this now (ewbit and heinz).  Someone suggested to open the Firefox error console (ctrl-shift-j) and that reveals the following:

reference to undefined property data.servers[v].name
http://localhost:8337/stats#

(sometimes the [v] is a [b] if that matters.  Mostly [v] though.)

**Comment by simonk83** [comment]
It's not Firefox specific though.  It occurs in both IE and Chrome.   Also while I'm on Windows, ewbit is on Ubuntu so it's not OS specific either.

**Comment by simonk83** [comment]
Ok, got to the bottom of it (sort of).  Seems to be index.html related.  I replaced the stock index.html with the Contrast version and now it all works fine.  Must be something in the html code of the stock version.

**Comment by simonk83** [comment]
Para suggested it might be this commit:

https://github.com/c00w/bitHopper/commit/5bcd00e0f4070fc7205dc9ec02e899bb0b4c9165#website.py

**Comment by c00w** [comment]
Okay. I added another check when creating pools to make sure that we always have a name for the pools.

**Comment by c00w** [comment]
I'm closing this as it appears to be solved.
