### ISSUE TITLE
use output = output.group(1) instead of output = output.group(0)

### ISSUE THREAD

**Issue by littleant** [c00w/bitHopper#41]
it would be a lot easier to use regex if you just use groups.
e.g. for triplemining:
in pool.cfg:
api_key:-->([ 0-9]+)</td>
(notice the brakets)
and in pool.py just use:
elif server['api_method'] == 're':
            output = re.search(server['api_key'],response)
            output = output.group(1)
...

you just enclose the desired output in your regex with brakets and it will get returned by output.group(1)

**Comment by c00w** [comment]
Really.... I may be quite silly. Let me doublecheck the specs then move stuff over.

**Comment by c00w** [comment]
Yeah. That makes sense. I'll use group(1) by default and change a bunch of regex matching.

**Comment by c00w** [comment]
And Its been commited. And the output has to be enclosed by parenthesis I think.

**Comment by c00w** [comment]
I'm going to close this issue. If I did something wrong reopen or open a new one.
