### ISSUE TITLE
BUG: mine_c role error v0.2.5.3

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#411]
paraipanakos: c00w you there
paraipanakos: i think i found the bug in las ver
paraipanakos: it spits out when we don't have a mine_c pool in cfg
paraipanakos: i was trying all combinations here when it hit me
paraipanakos: it worked great with the default cfg
paraipanakos: but not mine
paraipanakos: i dont have slush in there
paraipanakos: hope there's and easy fix

**Comment by c00w** [comment]
Can you post the error output?
Because I'm not seeing anything when I disable slush.

**Comment by paraipan** [comment]
pff nope, sorry c00w, made some changes and i wiped my logs somehow, works now on last ver. without slush, i'm closing the issue
