### ISSUE TITLE
Wrong backup pool selection

### ISSUE THREAD

**Issue by itstooez** [c00w/bitHopper#416]
I currently have ABCPool and Ars set to backup, both set to 1 thr penalty.  ABC has 1.65% stale rate, Ars has 2.82%, neither are red; yet it mines on Ars.

In scheduler.py     def select_backup_server(self,):                  should there be the , all by itself after (self ?

It appears that backup pool selection is wrong.

v0.2.5.3-6-gd1679c0

**Comment by c00w** [comment]
I'll take a look.

**Comment by c00w** [comment]
I think I found a bug. I wasn't casting shares to float and so it was getting chopped.

**Comment by c00w** [comment]
Should be fixed now for backup and backup_latehop.
