### ISSUE TITLE
LP Callback on Setting New Block Owner

### ISSUE THREAD

**Issue by itstooez** [c00w/bitHopper#436]
Currently when using a mine_lp role on Deepbit, when an LP comes in the block gets assigned to them, and an LP Callback is sent to the miners.  In return, the miners gather new work.

When a pool's shares drop, the block gets reassigned to the new pool, but it may be quite some time before new work is pulled.  Potentially missing a short round (primarily slush).

Can you add code to have an additional LP Callback, if the block gets reassigned to a pool set to a mine role (not info, donation, backup, etc)

Thanks

**Comment by c00w** [comment]
Sure.

**Comment by c00w** [comment]
Its pushed.
