### ISSUE TITLE
re_rateduration in api.py

### ISSUE THREAD

**Issue by rkozola** [c00w/bitHopper#443]
old_duration always equals duration after first call to selectsharesResponse.  so the share count will never reset when duration does.

**Comment by rkozola** [comment]
i think this may be because the pool uses api_key_duration_day_hour_min and not api_key_duration

**Comment by rkozola** [comment]
ignore comment about api_key_duration_day_hour_min, I do not know whats going on

**Comment by c00w** [comment]
Hmmm. I'll take a look

**Comment by c00w** [comment]
old_duration equals the last duration. It allow us to detect if the duration has dropped. I don't see a problem and am closing the issue.
