### ISSUE TITLE
BUG: Issues with poclbm (by amazingrando)

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#458]
any ideas on what this issue is with poclbm

Traceback (most recent call last):
  File "/home/miner/poclbm/HttpTransport.py", line 50, in loop
    rv = self.send(result)
  File "/home/miner/poclbm/Transport.py", line 88, in send
    is_block = belowOrEquals(h[:7], self.true_target[:7])
TypeError: 'NoneType' object is not subscriptable

**Comment by c00w** [comment]
For some reason its having a network error and continuing... Are you seeing a lot of them?

**Comment by amrando** [comment]
Yes, but after restarting the process a couple of times it has gone away.  No problem if it is continuing.

**Comment by c00w** [comment]
This may be coming from longpolls with incorrect work. Sadly if we've tried 5 times and not gotten any work we can't do much about it.

**Comment by paraipan** [comment]
closing issue...
