### ISSUE TITLE
Database locked in Windows

### ISSUE THREAD

**Issue by macboy80** [c00w/bitHopper#46]
This is probably a dumb question. Is it possible to close bH in Win7 without leaving the database locked. I don't have this problem with the ryouiki fork. Sorry to post an issue about this, but maybe an update to the readme if there is a recommended procedure.

Thanks,

**Comment by c00w** [comment]
Um. It shouldn't be possible. If you close bitHopper the database unlocks. If you fail to close bitHopper however and think you closed it then it will remain locked. Are you having issues or just wondering?

**Comment by c00w** [comment]
I broke my windows partition and haven't checked it but check for python using system monitor and just kill the process running bitHopper.

**Comment by macboy80** [comment]
Wow. I feel like a moron. Killing task in task manager solves problem. Is there a way to "close" the program other than killing it?

**Comment by c00w** [comment]
If you run it in command prompt then when you kill it it dies. running it through the python editor is trickier. I think there should be a stop debugging button or something.

**Comment by macboy80** [comment]
Sweet. I can live with either method. Thanks.
