### ISSUE TITLE
Mining Stats showing NMC shares and not BTC shares

### ISSUE THREAD

**Issue by Locky7** [c00w/bitHopper#461]
This was working, but now the stats reset when a NMC block is solved.  I'm mining  NMCBit.com  (MergeM-Prop) configured worker via NMCBit.com dashboard.

**Comment by c00w** [comment]
Thats on purpose with dual nmcbtc pools. There's no easy way to show the correct share and while we could show both its a low priority. Plus since you mine those pools for the nmc it makes more sense to show and hop nmc than btc.

**Comment by Locky7** [comment]
Masterpool, simplecoin, eligius, and slush are configured to display btc share count, so I was expecting displaying btc share count as the precedent in merged mining. 

[nmcbit]
coin:btc
name: NMCBit.com (MergeM-PPS)
mine_address: nmcbit.com:8332
api_address: http://www.nmcbit.com/statistics
api_method: re
api_key: Valid\s+shares\s+for\s+current\s+round:</th><td>([,0-9]+)</td>
api_strip: ','
url: http://nmcbit.com/dashboard

Also, there is a MergeM-Prop pool at NMCBit.com, shouldn't that pool be the default  for Bithopper?  (MergeM-PPS) should be mined as "backup."

Seems inconsistent to me, since the coin is listed as btc, not to have the btc share count displayed on the stats page.  Hope you reconsider the priority.  Thank you.

**Comment by Locky7** [comment]
could the api_key: be fixed to scrape the second instance of "Valid shares for current round" on the right cell of the table which would be for "BTC"?

**Comment by c00w** [comment]
Wait it says coin:btc and its displaying nmc shares? Thats wrong.

**Comment by paraipan** [comment]
yeah, dunno what's best, change coin type or scrape btc shares... hmm
changed coin type though, temp fix

**Comment by Locky7** [comment]
What does changing the coin type fix? The most profitable way to mine nmcbit is the MergeM-Prop pool, which is default. Changing the coin type to nmc was just cosmetic and did not fix this issue.   Bithopper mines simplecoin, slush, eligius, and masterpool (all merged mining pools) for btc not nmc, why be inconsistent with nmcbit?  Why does that make sense, just asking for some clarity.  Thanks all!

**Comment by paraipan** [comment]
indeed, until a good way for scraping btc shares is found there is no other option i guess

**Comment by Locky7** [comment]
Ok, i can understand that.  Thanks Bro!
