### ISSUE TITLE
BitChomp Closed

### ISSUE THREAD

**Issue by Locky7** [c00w/bitHopper#462]
NOTICE:
Hey everyone, some of you may have noticed, I've overpaid every one 5 times. Due to this, I'm going to have to shut down the pool till further notice. Obviously the payment system wasn't as robust as I thought, so I'm not really left with a choice.
Sorry about this, hopefully the extra bitcoins is compensation enough.
- XertroV
  
  may be back in the future, but I've a lot on my plate in RL, so don't count on too much.
  Again, my deepest apologies.

http://www.bitchomp.info/

**Comment by paraipan** [comment]
ack

**Comment by c00w** [comment]
This has been indicated in the config files.
