### ISSUE TITLE
wrong port for yourbtc.net

### ISSUE THREAD

**Issue by iongchun** [c00w/bitHopper#471]
The mining port for yourbtc.net is wrong, it should be 8999 instead of 8332.

diff --git a/pools.cfg b/pools.cfg
index f13c4b0..1f03058 100644
--- a/pools.cfg
+++ b/pools.cfg
@@ -603,7 +603,7 @@ url: https://guildminers.com/account
 [yourbtc]
 coin:btc
 name: YourBtc.net (DGPM)
-mine_address: yourbtc.net:8332
+mine_address: yourbtc.net:8999
 api_address: http://yourbtc.net
 api_method:re
 api_key: Round Shares:</strong> ([,0-9]+)

**Comment by c00w** [comment]
Fixed.
