### ISSUE TITLE
LP Callback Rejects...Info and backup pools

### ISSUE THREAD

**Issue by itstooez** [c00w/bitHopper#473]
Still seeing LP callbacks being sent to miners when the block is reassigned to a pool, also the work being submitted is rejected.  This also happened to btcg when a block is reassigned, work being submitted is rejected.  Showing 3 / 3 100.00% for Eligius which is on info (shouldn't even have shares...) and 4 / 4 100.00% for Ars which is on backup.  Rejects only occur on reassignment, regular LP pushing has no issues.

http://pastebin.com/sNwU5dGQ

**Comment by c00w** [comment]
I think I just fixed this.

**Comment by itstooez** [comment]
Deleting stats.db, git pull'ing and re-running.

**Comment by c00w** [comment]
I'm going to close this as it appears to be resolved.
