### ISSUE TITLE
Bug: nmcbit not working

### ISSUE THREAD

**Issue by amrando** [c00w/bitHopper#479]
Issues:
1) nmcbit is prop unless you select your workers to be pps, thus it should be in the regular list of prop pools

2) Can't mine nmcbit

bh stats page was showing nmcbit was:
NMCBit.com (MergeM-PPS) 130,486
 8.89%

but it was mining deepbit:
DeepBit.com (Prop)  420,877
 28.67%

nmcbit was not lagging

3) nmcbit is showing on the bh stats page the shares for nmc not btc

4) BH won't let me run 'mine_force' to force mining on nmcbit

**Comment by paraipan** [comment]
ack

1) They state PPS  http://dot-bit.org/forum/viewtopic.php?f=6&t=268

2) bH has a profitability algo. implemented for alternate coins that could be the cause not letting you mine even with those lowest shares

3) It's supposed to show NMC shares

4) That could be a problem yeah, when you force it's supposed to let you override no matter what. Hope c00w looks into it :)

**Comment by c00w** [comment]
coin profitability over rules everything. I should have it start as disabled. It even overrules mine_force.

**Comment by c00w** [comment]
I'll switch the default bh.cfg.default

**Comment by amrando** [comment]
Parai-

They're definitely prop-capable.  1) you can see it on the first bullet point here:https://bitcointalk.org/index.php?topic=33612.msg419958;topicseen#msg419958 2) if you have a nmcbit account you can see where you choose your workers are to be prop or pps and 3) i managed a 25 btc payout over the weekend when they had good luck - definitely not what we'd get paid pps.

For merged pools, shouldn't the hop point depend on the mining role?  e.g. if you have 'mine' it should hop based on btc shares, but if you had mine_nmc, wouldn't it hop on nmc shares?

**Comment by c00w** [comment]
mine_nmc is an alias to mine with coin: nmc. We probably should have two regexp's based on coin. I'll add it as an issue. I don't see a good clear way to do it however.

**Comment by amrando** [comment]
Could we in the meantime, have nmcbit be a prop and pps pool (two entries) like we have with mtred?  I would like to hop nmcbit with my prop workers and have set up pps workers so i can use nmcbit as a backup

**Comment by paraipan** [comment]
you can create a "pools-custom.cfg" file with a identical pool entry only with different [nmcbit] name, amazingrando

like this http://pastebin.com/FqAHnEQa

bH would read the file and add the pool right away and you don't have to mess around pools.cfg if you do this

**Comment by Locky7** [comment]
How are you going to hop nmcbit prop?  Amrando, I am in the same boat as you...but gave up on the issue since I understand it to be difficult to scrape BTC valid shares...  Tried to hop with mine_lp and added this to poolblock cfg:

[nmcbit]
url = http://www.nmcbit.com/statistics
search = href="http://blockexplorer.com/tx/([0-9a-f]+)"
mode = g

But it doesn't work.. obviously I don't know what I am doing :)

**Comment by organofcorti** [comment]
just don't use a hyphen in the name you use for the new nmcbit config or you'll crash the db. Like I did using [nbit-pps]. Worked fine when I deleted the db and changed the name to [nmbitpps].
