### ISSUE TITLE
LP Workbench not displaying

### ISSUE THREAD

**Issue by MobiusL** [c00w/bitHopper#484]
LPWB not updating or displaying LP data

**Comment by rkozola** [comment]
I think there is a problem with lp.py.  Recent changes seem to break receiving and recording LP announces.  It appears line 161 is broken in lp.py.

for now I replaced the following to get it to work again until this gets addressed:

if info['role'] in ['disable', 'info'] + ['mine_' + coin for coin, diff in self.bitHopper.difficulty.iteritems()

with

if info['role'] in ['mine_nmc', 'disable', 'mine_ixc', 'mine_i0c', 'mine_scc', 'info']:

**Comment by c00w** [comment]
Fixed.
