### ISSUE TITLE
BUG: user_drop_time still not working

### ISSUE THREAD

**Issue by sdogi** [c00w/bitHopper#490]
I think the problem is that data.prune() will get rid of all data.users[user]['shares_time'] elements and because of this the part that should use user_drop_time in data.get_users() stops working after 5 minutes or maybe a bit more.

I might have a workaround though so I'm throwing it out here c00w. Basically in data.prune() there is such check:

if time.time() - share_time > 60 \* 5:

If this is true then it will remove shares_time elements which make the users disappear. I changed it to:

if time.time() - share_time > int(self.user_drop_time):

This seems to work however now the hashrate calculation is wrong. One 200 mhash miner shows 10279 and the title bar hashrate stays 0.

If this is right approach but I just need to rewrite hashrate calculation then let me know but maybe I'm missing something else.

Any ideas?

**Comment by sdogi** [comment]
Ok I think I fixed this

in data.prune() when it wants to do:

self.users[user]['shares_time'].remove(share_time)

I added a check:
if len(self.users[user]['shares_time']) > 1:

Currently it seems to work just fine. Would this solution mess anything up or it is perfect?

**Comment by c00w** [comment]
That should work fine.

**Comment by sdogi** [comment]
Yup.. been testing this quite a while now and see no issues except that speed calculation is done a bit wrong. Which is no biggie. But if you know where to add a small check that will spit out 0 or doesn't do speed calculation with one data.users[user]['shares_time'] item then please add it in. Didn't seem to find anything straightforward while giving it a quick glance.
