### ISSUE TITLE
BUG: LP Workbench data not displaying after pull 492

### ISSUE THREAD

**Issue by MobiusL** [c00w/bitHopper#493]
Does not display when lpdump = True in bh.cfg

When lpdump = False collected LP data is displayed

**Comment by c00w** [comment]
Huh... I wonder if you can't overload hooks in peak.util.

**Comment by c00w** [comment]
You can. I'll investigate more.

**Comment by c00w** [comment]
I think I found the bug involving incorrect file opening modes. I'm going to close this issue as it is working on my machine.
