### ISSUE TITLE
Error in pool api for eclipsemc

### ISSUE THREAD

**Issue by yomismo22** [c00w/bitHopper#5]
[14:20:57] Error in pool api for eclipsemc
[14:20:57] [Failure instance: Traceback: <type 'exceptions.ValueError'>: No JSON object could be decoded
/usr/lib/python2.6/dist-packages/twisted/internet/defer.py:949:gotResult
/usr/lib/python2.6/dist-packages/twisted/internet/defer.py:936:_inlineCallbacks
/usr/lib/python2.6/dist-packages/twisted/internet/defer.py:318:callback
/usr/lib/python2.6/dist-packages/twisted/internet/defer.py:424:_startRunCallbacks
--- <exception caught here> ---
/usr/lib/python2.6/dist-packages/twisted/internet/defer.py:441:_runCallbacks
pool.py:309:selectsharesResponse
pool.py:250:eclipsemc_sharesResponse
/usr/lib/python2.6/json/__init__.py:307:loads
/usr/lib/python2.6/json/decoder.py:319:decode
/usr/lib/python2.6/json/decoder.py:338:raw_decode

**Comment by c00w** [comment]
Hi. That is a normal error if the api for a pool isn't working. Nothing to worry about.
