### ISSUE TITLE
mine_slush acting as backup

### ISSUE THREAD

**Issue by organofcorti** [c00w/bitHopper#50]
the mine_slush is working just as backup> It is coming in at any time - not when a round starts and then hopping off after 0.1*diff into the round.

**Comment by organofcorti** [comment]
ok, mine_slush _is_ giving preference to the pool when it starts a round, but it's still being chosen as a backup when nothing else available.

**Comment by organofcorti** [comment]
Also didn't hop off early - just stayed for whole round.

**Comment by c00w** [comment]
Shoot. I'll look at it again.

**Comment by c00w** [comment]
Oh and if the backup is down it can still be chosen...

**Comment by c00w** [comment]
Should be fixed now.

**Comment by organofcorti** [comment]
slush on mine_slush stayed on until I noticed it at 18% just now. Should it stop at 10%?

**Comment by organofcorti** [comment]
also, i like the way it's considered as sort of a higher priority backup - good move there.

**Comment by c00w** [comment]
It quits once it breaks 10%. It just has a slow refresh rate server side.

**Comment by c00w** [comment]
But there was a bug with mine_slush which was fixed.

**Comment by c00w** [comment]
You might have an older version

**Comment by c00w** [comment]
I'm closing this unless you have a specific complaint.
