### ISSUE TITLE
BUG: Can't get {user} to work - user: in user.cfg

### ISSUE THREAD

**Issue by MobiusL** [c00w/bitHopper#502]
I tried both variations and it did not work.

i.e. user.cfg  - miner is using 1 as login name to bh
normal: mobius.1 - works

mobius,{user} - not working

mobius.{USER} - not working

according to wiki:

mobius.{bHworker}  - not working

**Comment by c00w** [comment]
Is you miner connecting to bitHopper as 1:something?

**Comment by itstooez** [comment]
He stated that the bH worker's username was "1" when I was trying to help him in IRC.

work.py shows that {USER} should work, but maybe the implementation is incorrect.

**Comment by MobiusL** [comment]
my worker is logging in as http://1:x@192.168.1.190:8337 (from the miner to bH)

in user.cfg if I have (this works)
user: mobius.1
pass: x

when it's (does not work)
user: mobius.{USER}
pass: x

**Comment by c00w** [comment]
{USER} is working for me.

**Comment by c00w** [comment]
Are all of your users logging in as 1? That might be your problem otherwise. If its really tripping you up I have a web version of bitHopper with multiple workers per pool if you want to test it.

**Comment by MobiusL** [comment]
they are each numbered 1 to 18

**Comment by c00w** [comment]
This is fixed. See the new worker interface.
