### ISSUE TITLE
please add BTCSERV.net

### ISSUE THREAD

**Issue by trasul** [c00w/bitHopper#51]
Hi, please Add BTCSERV.net

**Comment by c00w** [comment]
[btcserv]
mine_address: btcserv.net:8335
api_address:view-source:http://btcserv.net/pool/round-stats/
api_method:re
api_key:`<td>`([0-9,]+)`</td>`
api_strip','
user:usename
pass:pass

**Comment by c00w** [comment]
Add that to your pool.cfg

**Comment by littleant** [comment]
here's a fixed version:
[btcserv]
mine_address: btcserv.net:8335
api_address:http://btcserv.net/pool/round-stats/
api_method:re
api_key:&lt;td&gt;([\d,]+)&lt;
api_strip: ','
role: mine
user: workername
pass: workerpassword

**Comment by trasul** [comment]
Thanks c00w and littleant
