### ISSUE TITLE
Possible deepbit hopping method

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#52]
Just had an idea (mining a little blindfolded though):
- subscribe to deepbit Long Pool and get new blocks announce like all the rest while hopping other pools
- get average block time from their stat page every once in a while
- mine on every LP announce 40% of average time announced (that would be ~6 minutes worth of shares at current time)

this could be applied on every pool with delayed stats

**Comment by c00w** [comment]
Yeah. That is probably what we are going to do.

**Comment by paraipan** [comment]
Would be awesome :)

**Comment by paraipan** [comment]
how is this going ?

**Comment by c00w** [comment]
Um its not? I need to rewrite the LP module to poll all servers where role != disable. I did clean up the work functions a bit though.

**Comment by paraipan** [comment]
It's gonna be the best feature, not for hopping deepbit cause they are big already but to avoid obfuscation methods.
Aexoden has something similar for poclbm wich I don't use, phoenix for me :)
