### ISSUE TITLE
Purge 0 Share Users

### ISSUE THREAD

**Issue by itstooez** [c00w/bitHopper#520]
sdogi asked me to write some code that can be incorporated into database.py to clear out all rows from all tables that have 0 shares.  The code below should be able to be added just about anywhere.  Just wanted the function is there, when and how it will be used will be decided later.

```
def purgeOldUsers():
    sql = "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;"
    curs.execute(sql)

    serverlist = []
    for item in curs.fetchall():
        serverlist.append(item[0])

    for server in serverlist:
        sql = "DELETE FROM " + str(server) + " WHERE shares='0'"
        curs.execute(sql)
```

**Comment by c00w** [comment]
The trick is we have some magic zero share users which record rejects and some other things. I'll double-check with the actual database structure to make sure this won't mess anything up.

**Comment by c00w** [comment]
Closing the issue as we redid the whole system.
