### ISSUE TITLE
Current mHash isn't accurate

### ISSUE THREAD

**Issue by TimLinton** [c00w/bitHopper#528]
The current mHash being displayed on the top is not the same as when you add up all of the users' mHash's on the bottom of the page. And, none of them are correct in the first place.
Even if I add up the combined mHash's of the users down below, the top still isn't right. Usually the numbers are in the general ballpark..but barely.
I'll be going at a solid 300 for a while, and it says i'm going at 380, or 200, or something that isn't even close to the real mHash.

To replicate it, just use the server

**Comment by c00w** [comment]
Okay. we currently run a running average of shares and use that for the top of the page. we use a running average of a different length for the users. We can change both of them to be the same length. They will still be slightly desynced as they are two different systems.

**Comment by c00w** [comment]
They have both been changed to be have the same time increments. I'm closing this issue.
