### ISSUE TITLE
BUG: Coinotron re_rateduration api

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#530]
As reported by itstooez, coinotron api doesn't seem to work lately. We both tried doing some regex tricks without success.

The error is:

"coinotron api error:'NoneType' object has no attribute 'group' "

Last api that worked is (pools.cfg api wasn't up to date): 

api_address: http://coinotron.com/coinotron/AccountServlet?action=home
api_method: re_rateduration
api_key_ghashrate: BTC</td>\s._>\s_([0-9]+)[.]
api_key_duration_hour_min: BTC</td>\s._\s._\s.*>([0-9]+) h ?([0-9]+)? ?m?</td>

**Comment by itstooez** [comment]
api_key_ghashrate: BTC</td>\s._>\s_([.0-9]+) GH

That's the ghashrate key I'm using.

Doesn't work.

**Comment by Locky7** [comment]
https://github.com/c00w/bitHopper/pull/531

**Comment by itstooez** [comment]
^ Works.

**Comment by Locky7** [comment]
haha, I was wondering where the raise in hashrate came from ;-)

**Comment by paraipan** [comment]
nice, thanks Marty

**Comment by c00w** [comment]
I'll take a look.

The relevant line is:

BTC</td>
<td style="text-align: right;">   17.29 GH</td>

so ([0-9.]+) GH</td> might work. You may need to specify a different group number.

**Comment by paraipan** [comment]
sup c00w, i was starting to think they've done something on the pool's end :P

**Comment by c00w** [comment]
So it works now and I can close this issue?

**Comment by Locky7** [comment]
Pool op has removed minutes, even for the first 24hrs.  Reopen issue?

Anyone notice that a new block was found today?

**Comment by Locky7** [comment]
So today, the m under 24hrs is back but still the valid shares are way off.  Also,  I found the 1/7 update and tried that too.  But the shares are way off, 4.5k after 7hrs with no duration display which tells me it is broken.  Anyone else having similar results?

**Comment by c00w** [comment]
Closing this issue as the codebase has been rewritten
