### ISSUE TITLE
Diff halts updating

### ISSUE THREAD

**Issue by itstooez** [c00w/bitHopper#552]
A few months ago...there was an issue with the API calls halting when an exception occurred, it wasn't being handled right for certain roles.  When the exception hit, the pool would no longer update it's shares.

This appears to now be happening with updating of difficulty.

00:40:54|diff: Updating Difficulty of Bitcoin
00:40:54|diff: Updating Difficulty of Namecoin
00:40:54|diff: Updating Difficulty of IXcoin
00:41:59|diff: Updating Difficulty of I0coin
00:42:12|diff: Updating Difficulty of SolidCoin
00:42:13|diff: Updating Difficulty of Geist Geld
00:52:13|diff: Updating Difficulty of Bitcoin
00:52:14|diff: Updating Difficulty of Namecoin
00:52:14|diff: Updating Difficulty of IXcoin
00:52:23|diff: Updating Difficulty of I0coin
00:53:21|diff: Updating Difficulty of SolidCoin
00:53:22|diff: Updating Difficulty of Geist Geld
01:03:22|diff: Updating Difficulty of Bitcoin
01:03:22|diff: Updating Difficulty of Namecoin
~/bitHopper$ date
Tue Jan 17 02:08:51 UTC 2012

I believe once it tried IXcoin and it failed, no more difficulty updates.  Please look into this =]

**Comment by c00w** [comment]
Can you get me a debug output? I'm looking at the code and while I'm not happy with it I don't see anything obviously wrong.

**Comment by itstooez** [comment]
It fails randomly...I can try and get a debug output, but it appears to happen after the update attempt fails.  Maybe it's not with an exception, but somewhere else, but it's strangely similar to the API call updates.

**Comment by itstooez** [comment]
https://github.com/c00w/bitHopper/commit/61ffe1d3b2157003988ccbd4bf9f75e2c0d485ef

Should fix it.
