### ISSUE TITLE
bH Stalls while updating info from GPUTECH

### ISSUE THREAD

**Issue by MobiusL** [c00w/bitHopper#553]
I edited poolblock,cfg and commented out GPUTECH entry - stall problem is not occurring now

**Comment by Locky7** [comment]
Pool is closed?

**Comment by MobiusL** [comment]
stalls on https://imgur.com/L1Lt4

**Comment by Locky7** [comment]
Thanks Bro! https://github.com/c00w/bitHopper/pull/554

**Comment by c00w** [comment]
Should be fixed. Added a timeout back to diff.py.
