### ISSUE TITLE
req:enable/disable via web page

### ISSUE THREAD

**Issue by hawks5999** [c00w/bitHopper#56]
similar to ryouiki's web interface with the enable/disable, add option to enable, disable a pool on the fly without changing cfg and restarting

**Comment by c00w** [comment]
Flower is working on it.

**Comment by c00w** [comment]
Merged in now. Not sure if enable works however...

**Comment by hawks5999** [comment]
works in initial testing!

**Comment by c00w** [comment]
Does a pool going from disable to info or update change its API roundshare values though?

**Comment by hawks5999** [comment]
quick test I run:

enabled state:
bitcoinmonkey.com   2550712 150.85%          mine   

disabled state:
bitcoinmonkey.com   N/A          disable

enabled again
bitcoinmonkey.com   2550735 150.85%          mine

is that  what you are asking?

**Comment by hawks5999** [comment]
next test:
first state:

bitp.it N/A backup  

next state (change to mine):

bitp.it 1690906 100.00%          mine 

next state (change to backup):

bitp.it N/A backup  

next state (change to junk):
bitp.it N/A          junk   

Next state (click Green back to mine):

bitp.it 1690906 100.00%          mine

**Comment by c00w** [comment]
Yeah. I don't think bitp.it's api counter will ever change from difficulty.

**Comment by c00w** [comment]
I fixed it. Closing the issue.

**Comment by hawks5999** [comment]
thanks. works great.
