### ISSUE TITLE
Too Many Open Files

### ISSUE THREAD

**Issue by Transisto** [c00w/bitHopper#563]
"Exception in wsgi server loop, restarting wsgi in 60 seconds
[Errno 24] Too many open files"

I get this error msg every minute (exactly)

I have all plugin to auto but at boot I have these errors
21:55:19|plugin: ERROR LOADING PLUGIN: hookexample
21:55:19|plugin: BitHopper instance has no attribute 'log_dbg'
21:55:20|plugin: ERROR LOADING PLUGIN: poclbm
21:55:20|plugin: No module named pyopencl

I also have the problem than my ubuntu VM can't be accessed via WAN after some time.
But It may be my router,

21:55:58|poolblocks: Error btcg : [Errno socket error] [Errno 8] _ssl.c:503: EOF occurred in violation of protocol

So many error message I can't tell which one is related to my troubles,
Thank-you

**Comment by Transisto** [comment]
This one is also very common. :

Traceback (most recent call last):
  File "/home/btc/c00w-bitHopper-5fd0970/eventlet/greenpool.py", line 80, in _spawn_n_impl
    func(_args, *_kwargs)
  File "/home/btc/c00w-bitHopper-5fd0970/eventlet/wsgi.py", line 514, in process_request
    proto = self.protocol(socket, address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 641, in __init__
    self.finish()
  File "/home/btc/c00w-bitHopper-5fd0970/eventlet/wsgi.py", line 456, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "/usr/lib/python2.7/SocketServer.py", line 694, in finish
    self.wfile.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "/home/btc/c00w-bitHopper-5fd0970/eventlet/greenio.py", line 283, in sendall
    tail = self.send(data, flags)
  File "/home/btc/c00w-bitHopper-5fd0970/eventlet/greenio.py", line 269, in send
    total_sent += fd.send(data[total_sent:], flags)
error: [Errno 32] Broken pipe

**Comment by c00w** [comment]
1st. Turn off all plugins you don't explicitly want. Some of those don't work some of them are quite old. In fact there is a full miner included in there.

Namely:
21:55:20|plugin: ERROR LOADING PLUGIN: poclbm
21:55:20|plugin: No module named pyopencl

**Comment by c00w** [comment]
error: [Errno 32] Broken pipe
21:55:58|poolblocks: Error btcg : [Errno socket error] [Errno 8] _ssl.c:503: EOF occurred in violation of protocol

The EOF issues and the broken pipe issues probably have to do with your router timing out connections after 5ish minutes. If you can fix that do so. If you can't don't worry about it.

**Comment by Transisto** [comment]
ubuntu, the 2nd addition is from most plugin disabled,

**Comment by c00w** [comment]
21:55:19|plugin: ERROR LOADING PLUGIN: hookexample
21:55:19|plugin: BitHopper instance has no attribute 'log_dbg'

Also I fixed the hookexample plugin so that error should stop popping up.

**Comment by c00w** [comment]
"Exception in wsgi server loop, restarting wsgi in 60 seconds
[Errno 24] Too many open files"

This error is an issue. It means that you are for some reason opening oodles of files or the vm limit is set extremely low. Are you running this on a ubuntu vm inside of windows?

**Comment by Transisto** [comment]
yes as a VM

**Comment by Transisto** [comment]
This look high already : /proc/sys/fs/file-max = 49355

**Comment by c00w** [comment]
It's probably related to how your network connection's are set up. Windows limits them to 1024 and I'm not sure if a VM can emulate more than that if the host os is limited. What type of network settings do you have in the vm?

Also what VM are you using? I might be able to give you more precise instructions.

**Comment by Transisto** [comment]
Vmware ubuntu,  I'm pretty sure windows doesn't limit the VM,  My network setting = bridging my NIC,

I've done what's written there http://linux-quirks.blogspot.com/2011/02/too-many-open-files.html

increased my open limit to 16000+ instead of 1024, 

Thanks for your help ,  hope it's solved for good.

**Comment by Transisto** [comment]
seems to have fixed it, still I don't understand how BH can open more than 1000 files
