### ISSUE TITLE
hang for ~1min while ...  "database: DB: writing to database"

### ISSUE THREAD

**Issue by Transisto** [c00w/bitHopper#564]
01:24:00|database: DB: writing to database

then when it start back to normal it receive a buch of shares very fast.

Is this normal ?

(running on a VM stored on a fast SSD)

**Comment by c00w** [comment]
No. It should be running the database in a separate thread so file I/O isn't blocking it. Was this the first time you started it up? I'll take a look and see if I can set up multiqueries to speed things up.

**Comment by Transisto** [comment]
No it was not the first time I had started it.

Do you recommend to restart BH after a length of time ?

**Comment by c00w** [comment]
No. Something is rotten in the database module.

**Comment by c00w** [comment]
Ok, so it looks like this is an sqlite issue. I'm going to swap to berkelyDB for higher file i/o performance.

**Comment by c00w** [comment]
Actually I'm not. That adds another dependancy. However I added the vacuum command to our sqlite database handling which should solve a bunch of issues. Try rerunning with the latest version.

**Comment by Transisto** [comment]
Thanks / will update

**Comment by c00w** [comment]
Update to the latest. I moved us to gevent and fixed sqlite to work properly. I wasn't having it run in another thread due to a bug.

**Comment by c00w** [comment]
I'm closing this issue as it is fixed in the latest version.

**Comment by Transisto** [comment]
I have not been able to find a working BH since this issue was suposedly resolved, 

I'm still at 2.6.6 and now suffer from having an outdated pool config

AND hang for ~1min while ... "database: DB: writing to database" 

BUT at least I can have more than 6ghs on it without it refusing more work.

**Comment by c00w** [comment]
This bug is fixed in the current version. What is broken in the very latest commits is long polling. Specifically it is dieing somewhere and causing massive share breakage. We are working on it.
