### ISSUE TITLE
30% invalid shares

### ISSUE THREAD

**Issue by elitak** [c00w/bitHopper#57]
I'm getting this with & without long-polling enabled with all of my miners through a remote-running proxy (hence higher latency). I have only a couple percent on the same miners if I switch them to report directly to the pools.

Any ideas on what's causing this? It's difficult to trace the lifetime of one connection and determine what's wrong with the work a miner is getting or the shares its' trying to submit.

**Comment by c00w** [comment]
Um. How well does your proxy handle new connections? JSON-RPC is badly designed and likes a new connection for literally every request. If there is some overhead on that then it can get messy. I'm going to make a latency sweep through bitHopper at some point and switch a lot of stuff with regards to the database to a new deffered so the getworks are faster.

**Comment by elitak** [comment]
I do have an intermediate proxy for some miners, but even for others where I don't, they still get a high reject rate. I'm connecting directly to port 8337 with them, so only the latency that exists between the publicly routeable addresses should be present. 

I thought long-polling reused the connection for subsequent requests?

**Comment by elitak** [comment]
I think it's to do with high load. What's the highest number of miners you've tested with? I had a couple dozen amounting to ~10 Ghash/sec and I think that's what was causing the problem. I don't think it's anything to do with latency.

Can you explain for me what the conditions are for rejected work submissions? Is it:
A. Only when the upstream server sends a "reject".
B. Whenever bitHopper itself thinks the result is bad
C. The client itself (phoenix-miner in my case) gets no response for its submission
D. Some other combination of conditions.

**Comment by c00w** [comment]
Um. I don't have that much hashing power. At high load its probably the database intergration slowing things down. I'll fix it.

Its mostly A with a bit of C. In the case of C the server will keep trying ot submit it but the client may give up and mark it as rejected. that wouldn't effect the bitHopper stats though.

**Comment by c00w** [comment]
The database does an update for every request. Which is slow. I'll change it to do one update a minute.

**Comment by c00w** [comment]
Its changed now. Tell me if that speeds things up.

**Comment by c00w** [comment]
I think the reason you are getting high shares is sending work lags out the database which causes it to take while for the share to make it upstream which makes the server mark it as stale and reject it.

**Comment by c00w** [comment]
or even worse it doesn't remember giving you the getwork and rejects it for that reason.

**Comment by elitak** [comment]
Wilco. Thanks for the fast response :)

**Comment by elitak** [comment]
That seems to have fixed it. I'm below 2% rejects now. Thanks a lot. 2BTC donation sent to 1HEmzeuVEKxBQkEenysV1yM8oAddQ4o2TX ;)

Please keep larger setups like mine in mind for future changes. I may try to develop some scalability tests myself to contribute.

**Comment by c00w** [comment]
Yeah. Scalability tests would be awesome.
