### ISSUE TITLE
a1 no longer reporting time since last block

### ISSUE THREAD

**Issue by joulesbeef** [c00w/bitHopper#575]
it breaks the way we do it so people probably shouldnt mine it for now.,

edit: It sounds like he is just having technical issues in the forums.. he is talking about having problems with the reporting of lifetime shares which is different but if he is having problems there I wouldnt be surprised if this is just a technical issue. Any ways dont mine there until it is fixed.

**Comment by Locky7** [comment]
He hasn't found a block yet, so I agree with you. Once a block is found, the estimated share count will be more stable.

**Comment by Locky7** [comment]
please close

**Comment by c00w** [comment]
For reference the pool is down and we deleted it.
