### ISSUE TITLE
stats.db rogue diff entries 

### ISSUE THREAD

**Issue by Clipseza** [c00w/bitHopper#579]
Seems to be something strange with stats.db imports

Randomly shares would get dumped into this difficulty: 1159947.196

Then it would continue to dump shares to the correct difficulty only to repeat random shares to said difficulty.

Its quite hard to keep track of efficiency of my payout wallets when the difficulties dont match the shares.

**Comment by c00w** [comment]
I have no idea where that difficulty comes from. I made the diff module thread safe.

**Comment by Clipseza** [comment]
you could test it yourself, ive clean db and resubmit shares and everytime it occurs so should be easy to reproduce

**Comment by c00w** [comment]
I will. I just got the lagging pool issues. So I'm going to try and fix them first.

**Comment by Clipseza** [comment]
great will check for an update :)

**Comment by c00w** [comment]
Looks like gevent 1.0b1 and 1.0dev are broken. Using 0.13.6 works well on linux. I'm going to try and find a good source for windows.

**Comment by Clipseza** [comment]
nice ill try that windows build

On Mon, Feb 6, 2012 at 2:51 AM, Colin Rice <
reply@reply.github.com

**Comment by Clipseza** [comment]
cool will try that windows build

**Comment by c00w** [comment]
Okay, the readme has a link for 0.13.6 for windows. It might work. It does require libevent and I'm not sure if it is bundled.

**Comment by Clipseza** [comment]
tough to find windows binaries for libevent but ill check to see if its maybe packaged with gevent but cant test right now :/

**Comment by c00w** [comment]
The link in the readme is working correctly for me. It has libevent bundled. So that should work for you. I've submitted a bug report with gevent.

**Comment by Clipseza** [comment]
great, about to test it on my dev vm

**Comment by Clipseza** [comment]
even with that gevent 0.13.6 its all lags out and bithopper just dies

**Comment by c00w** [comment]
Does this issue still occur?

**Comment by c00w** [comment]
0.3.2 has a propper wsgi callable. I'll post a guide on how to use uwsgi with bitHopper.
