### ISSUE TITLE
Various issues with latest pull

### ISSUE THREAD

**Issue by simonk83** [c00w/bitHopper#580]
Can't tell you exactly which commit has started this, but I assume it's to do with the gevent stuff.

Since upgrading BH is giving me:

(8:57:39 AM) simonk83: 08:29:06|database: DB: writing to database
(8:57:39 AM) simonk83: 08:30:06|database: DB: writing to database
(8:57:39 AM) simonk83: 08:31:06|database: DB: writing to database
(8:57:39 AM) simonk83: 08:32:06|database: DB: writing to database
(8:57:39 AM) simonk83: 08:33:06|database: DB: writing to database
(8:57:39 AM) simonk83: 08:34:06|database: DB: writing to database
(8:57:39 AM) simonk83: 08:35:06|database: DB: writing to database
(8:57:39 AM) simonk83: 08:36:06|database: DB: writing to database

and cgminer is giving me:

(7:32:52 AM) simonk83: [2012-02-06 07:32:49] JSON inval data
(7:32:52 AM) simonk83: [2012-02-06 07:32:49] JSON key 'data' not found
(7:32:52 AM) simonk83: [2012-02-06 07:32:49] JSON inval data
(7:32:52 AM) simonk83: [2012-02-06 07:32:49] JSON key 'data' not found
(7:32:52 AM) simonk83: [2012-02-06 07:32:49] JSON inval data
(7:32:52 AM) simonk83: [2012-02-06 07:32:49] JSON key 'data' not found
(7:32:52 AM) simonk83: [2012-02-06 07:32:49] JSON inval data
(7:32:52 AM) simonk83: [2012-02-06 07:32:49] JSON key 'data' not found
(7:32:52 AM) simonk83: [2012-02-06 07:32:49] JSON inval data
(7:32:52 AM) simonk83: [2012-02-06 07:32:49] JSON key 'data' not found
(7:32:52 AM) simonk83: [2012-02-06 07:32:49] JSON inval data
(7:32:52 AM) simonk83: [2012-02-06 07:32:49] JSON key 'data' not found

I've installed gevent (BH wouldn't load without it).

Going to roll back to before all the new stuff was added to get things working again.

**Comment by simonk83** [comment]
Confirming commit https://github.com/c00w/bitHopper/commit/5cc1c6029ad216e447b9d5811633849f3ad1ce14 works fine again.

**Comment by c00w** [comment]
This occurs with gevent 1.0dev on linux and windows.

**Comment by c00w** [comment]
I can confirm it does not occur with gevent 0.13.6 on linux. I'm trying to see if it appears with gevent 0.13.6 on windows.

**Comment by c00w** [comment]
This is confirmed as fixed if you use gevent 13.6. New installation instructions are in the readme.
