### ISSUE TITLE
submitted shares leaking

### ISSUE THREAD

**Issue by Clipseza** [c00w/bitHopper#581]
I notice another issue, not sure if it only comes out of the closet due to pushing high hashrate but I have a ton of shares being double submitted ie. I would have 98% stalerate to kiwipool(or any other pool) due to bitclockers shares (or any other pool) being submitted to kiwi partially and then also some to bitclockers (this is just example, it could be any pool)

Anyone else notice this behaviour with about 20pools listed and doing ~15-20GH of traffic.

**Comment by c00w** [comment]
Something is broken in gevent 1.0. If you can get gevent 0.13.6 working it should be stable.

**Comment by c00w** [comment]
nvm incorrect source... Is this still happening?

**Comment by Clipseza** [comment]
the shares leaking was with version before switching to gevent, I will look at the latest version with gevent if it still happens.

Will report back in a bit, testing latest pull.

**Comment by Clipseza** [comment]
Submitting work to wrong pools, I am mining at slush for instance and it submits a ton back to slush but then also a bunch to kiwipool or arsbitcoin etc. leaving them at 99.99% stale/reject counting until they actually get mined and then their accepted shares would obviously increase.

From what I can see from my previous logs, it occurred since before the move to gevent afaik.

Is there any way to fix the share leaking or are you aware of it atleast?

**Comment by c00w** [comment]
I'll take a look. It may be that merkle roots are not unique per pool or we are looking at the wrong section. Or there is some other bug.

**Comment by Clipseza** [comment]
Would be good to get this fixed, wasting alot of my submits on non-contenders :P

**Comment by Clipseza** [comment]
Any idea yet around the shares leaking/submitting to wrong pool?

**Comment by c00w** [comment]
Merkle code might be right. The code display code might be wrong. I'm adding the new worker interface then going to go bug fix.

**Comment by c00w** [comment]
Fixed in 0.3.2
