### ISSUE TITLE
problem installing on new ubuntu following README

### ISSUE THREAD

**Issue by Transisto** [c00w/bitHopper#584]
sudo apt-get install python git python-dev python-setuptools
sudo pip install gevent importlib
git clone git://github.com/c00w/bitHopper.git
cd bitHopper
python bitHopper.py

on new ubuntu 10.04 =  Fail

Output = http://pastebin.com/uTyLMiXE

given the readme instruction there need to be added a "apt-get install python-pip" somewhere 

...

**Comment by c00w** [comment]
My apologies. Python-setuptools installs python-pip on 11.10. However you also need to pip install setuptools not importlib. The readme has been corrected.
