### ISSUE TITLE
Latest pull on ubuntu

### ISSUE THREAD

**Issue by Clipseza** [c00w/bitHopper#585]
Seems the lag issue with latest even on linux give same lagger issue.

I suppose its because you havnt fixed the timing yet ? So it wasnt a window specific issue, its actually happening on linux aswell .

**Comment by c00w** [comment]
... Uh oh. What specifically is happening are all the pools just lagging out? I redid work.py to use resourcepools and not actually have greenlets closing other greenlets sockets etc..

**Comment by Clipseza** [comment]
Acts the same, I only pushed 2gh at it. It would lag the same Im sure as it did on windows when i tested with 10gh+

What it did now is at 2gh it would lag the pool over and over, all the pools aint lagging but behaviour wise it probably would if I pushed more hashing over it.

**Comment by c00w** [comment]
Which commit did you test with?

**Comment by Clipseza** [comment]
Hi

I used this commit: https://github.com/c00w/bitHopper/commit/f8127a147239bcf0fbae5c5ed21d6720c6c3cd2a

Will test latest again.

**Comment by Clipseza** [comment]
Bit off topic, how does bithopper count rejects and stales ? Does the
rejects in bithopper take into account both of these, or does it ignore
stale shares?

On Mon, Feb 6, 2012 at 7:35 PM, Colin Rice <
reply@reply.github.com

**Comment by Clipseza** [comment]
I redid all the python installations with absolute latest git pull, so far database isnt getting stuck at writing, will let you know if it does fail at some point during testing, this is weird :P

**Comment by Clipseza** [comment]
My msg wasnt even send yet and the hopper crash, most likely due to database writing that locks. Sigh

**Comment by c00w** [comment]
What is the specific crash? I might be missing some race conditions which is probably why it is so wierd.
The reject counter was covered in a previous issue. I'll take a look when I'm less busy and write up a blog post.

**Comment by vcaxx** [comment]
I think I have the same or similar problem:
btlc starts lagging, and than eligius and finally when bitHopper issues LP Callback for all miners:

00:14:52|work: LP Callback for miner: M3_sap5830
00:15:10|database: DB: writing to database
00:16:10|database: DB: writing to database
00:17:10|database: DB: writing to database
. . . repeats each minute

**Comment by Clipseza** [comment]
its got nothing to do with the actual pool, if db writes to many cached shares it pretty much locks up. Thats all I know, hopper doesnt actually crash just becomes unresponsive until you forcibly kill it.

**Comment by c00w** [comment]
k. I have a race condition in the code.

**Comment by c00w** [comment]
I think I found the race condition. Can you verify it is not locking anymore?

**Comment by Clipseza** [comment]
Getting alot of json cant decode while running latest, db lock issue is resolved it seems.

Also getting random pool lagging out issues which isnt occuring with an older BH version running alongside to compare.

**Comment by vcaxx** [comment]
I have constantly lagging eligius and few others for eligius here is the error msg:

02:10:13|api: eligius api error:'NoneType' object has no attribute 'group'
02:10:14|rpcworklog: RPC request [getwork] submitted to deepbit
02:10:14|lp: Long Poll Call http://btcproxy.net:80/LP

For the others it is one of the two:
02:11:11|api: bitparking api error:'api_key'
or
02:11:12|api: mmf api error:No JSON object could be decoded (more often)

I reconfirm that DB locking issue seems to be fixed - my hopper is still hopping

**Comment by Clipseza** [comment]
All your errors is normal, except for the json decode issue that seems to be related to the latest versions.

Eligius is down, so it wont be able to update stats.

**Comment by Clipseza** [comment]
Colin, I am running the latest pull through the night on linux host and if nothing stuffs up then I would assume we need to focus only on windows hosts causing the remaining issue.

**Comment by Clipseza** [comment]
Ran 5GH on linux and after about 800 shares the DB seem to have locked again. Will post log output if it indeeds write anything since it doesnt actually crash the hopper.

**Comment by c00w** [comment]
Did bitHopper freeze? Or did the database writing just stop showing up.

**Comment by Clipseza** [comment]
No crash yet since I restarted it with logging, so now I wait. Its good that it didnt lockup yet though, but not sure what that means for windows o_0

**Comment by Clipseza** [comment]
Absolutely no database locks or other issues with latest pull on linux so I will bit later today have a couple of hours run on windows with exact same setup and see if it still foobars.

**Comment by Clipseza** [comment]
Ok so results:

Linux no issues at all, humming along. 

Windows it initially runs but quickly every pool it tries to submit shares to simply LAG out and it keeps moving to next pool and LAG out etc.

**Comment by vcaxx** [comment]
Clipseza, thanks for heads up on Eligius being down. Other that it, all other pools were running fine, without lagging, for me few hours last night. 
However bithopper froze after few hours, and now it froze again after I restarted it. This time I don't see database write messages, it just stays there not printing anything after submitting last work to a pool.

I have Debian, so it seems that lagging is solved in Linux. Do you guys want me to comment in this thread or in the another one I opened about the blocking? It seems that those might be two different issues?

**Comment by Clipseza** [comment]
Finally it output some sort of error msg, this is on linux:

[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error from accept() call: Too many open files
[warn] Error fr

**Comment by c00w** [comment]
vcaxx, you can comment in your own thread if you want.I think I know where the freezing is coming from.

**Comment by c00w** [comment]
Clipse: Raise the open file limit:
http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/
http://linux-yogi.blogspot.com/2010/04/increase-socketfile-open-limit-in-linux.html

**Comment by Clipseza** [comment]
Ye I sorted file limit (even though it was allready set to 10000) cant imagine bithopper use that many open file limit allocation.

I still had lockups though, thats my main concern which makes me think its not a windows issue but a issue that could either not show itself for a couple of hours or immediately or after 5minutes.

**Comment by Clipseza** [comment]
Colin I dont know how this would work or if its related in any way to gevent but have you considered making use of epoll ?

http://scotdoyle.com/python-epoll-howto.html

I see various comments about it being very very efficient in keeping a mass amount of connections open.

**Comment by c00w** [comment]
Thats what gevent uses on linux with gevent 0.13.6.

So there still are deadlocks? I'll rewrite the db section again.

**Comment by c00w** [comment]
I rewrote the section and all locks are logged. If you get a deadlock, scroll up until you see the lock acquried and tell me what the line says.

**Comment by c00w** [comment]
Also I updated the timeouts in work.py. You need to change the line in your bh.cfg for work_timeout from 2.5 to 5 or recopy it from bh.cfg.default.

**Comment by c00w** [comment]
Are there still dealocks? Or can I close this issue?

**Comment by Clipseza** [comment]
No db locks and working on linux except I just have an issue with open file limit, I even set the file limit to 10 000 000 and it still got hit o_0 

Its a definite no go on windows all together, LAG out remains.

**Comment by c00w** [comment]
Hmmm. I have an idea of where the file limit bug is coming from.

**Comment by c00w** [comment]
Looks like poolblocks is leaking filehandles and doing file io. So its bad on two different levels. If you are doing high performance bitHopping do not turn it on. I'll add a bug and clean it up.

**Comment by Clipseza** [comment]
Cool, cant wait.

**Comment by c00w** [comment]
It should be cleaned up. If you still see leaking files  on linux run

ps aux | grep bitHopper
there should be a number in the top left.

Example output:

colin    24020 22.8  0.4  93740 37376 pts/6    S+   13:05   0:01 python bitHopper.py
colin    24046  0.0  0.0  13448   900 pts/9    S+   13:05   0:00 grep --color=auto bitHopper

number is 24020
then type
cd /proc/NUMBER/fd/

example
cd /proc/24020/fd/

then run ls -lh and tell me what the output is.

**Comment by Clipseza** [comment]
I resolved the open files problem, just kept hammering the wrong limit function.

**Comment by c00w** [comment]
Are there any other current problems besides pools lagging out?

**Comment by Clipseza** [comment]
All I can think is pool lag issue on windows hosts and then the shares leaking(not sure if you updated anything regarding that) on both hosts.

**Comment by c00w** [comment]
Pools are only lagging out on windows? I thought they were lagging on windows and linux? Either way I'll open new issues and close this one.
