### ISSUE TITLE
BH get to a crawl after ~4hrs, require rebooting the OS

### ISSUE THREAD

**Issue by Transisto** [c00w/bitHopper#586]
I reverted to d3b002d 2.6.7...  (ubuntu 10.10)

When I woke up BH was very very slow , would not respong.

I had to reboot the OS for it to work again,  took about 4 hours before it broke again 

Last lines after 4hrs,,,, http://pastebin.com/KDTqn8kh

Then when I restart BH :  http://pastebin.com/7hiqN3Ni (still broken)

**Comment by Transisto** [comment]
Edit : error, rebooting the OS does not fix the problem ,,,

http://pastebin.com/rdmDugjh

**Comment by c00w** [comment]
Either go to 0.2.6.6 or the latest. Both of those issues are fixed. 2.6.7 has a bug.

**Comment by Transisto** [comment]
Thanks I'll be going to 0.2.6.6

Has the latest been tested with 20+ ghs ?

**Comment by c00w** [comment]
Yes, and its dieing. Its more wounded and less missing its heart. We're working on it.

**Comment by c00w** [comment]
Its working mostly now. There are some ancillary issues with it being too fast and some shares going to the wrong pools.
