### ISSUE TITLE
bitHopper blocks on New Block from lpbot

### ISSUE THREAD

**Issue by vcaxx** [c00w/bitHopper#587]
When hopping with lpbot plugin turn on bitHopper blocks after the first registred new block:

00:28:05|lpbot: New Block: {deepbit} - 00000000000005710c2f7efbbd495d74851a959d325639a76bd695da72687134
00:28:05|lp: New Block: 00000000000005710c2f7efbbd495d74851a959d325639a76bd695da72687134
00:28:05|lp: Block Owner deepbit
00:28:05|lp: Setting Block Owner deepbit:00000000000005710c2f7efbbd495d74851a959d325639a76bd695da72687134
00:28:05|work: LP Callback for miner: M2_xfx5850
00:28:05|work: LP Callback for miner: M3_sap5830
00:28:05|work: LP Callback for miner: M2_xfx5850
00:28:05|work: LP Callback for miner: M3_GygPol5870
00:28:05|work: LP Callback for miner: M2_xfx5850
00:28:05|work: LP Callback for miner: M3_sap5830
00:28:05|work: LP Callback for miner: M2_ref5870
00:28:05|work: LP Callback for miner: M2_ref5870
00:28:05|work: LP Callback for miner: M2_ref5870
00:28:05|work: LP Callback for miner: M2_xfx5850
00:28:05|work: LP Callback for miner: M3_sap5830
00:28:45|database: DB: writing to database

... than it repeats writing to database line each minute and it does not react to Ctrl-C

OS is Debian, python 2.7.2

**Comment by c00w** [comment]
How many miners do you have? Also what miner are you using? It looks like the main thread is locking up.

**Comment by c00w** [comment]
I think I found the lockup. Can you update to the latest version and recheck?

**Comment by vcaxx** [comment]
OK, it does not block on a new block anymore, I confirmed through three blocks. 
However the first time I started the updated version it became unresponsive immediately after the first getwork. The second run went smoothly and it is still running.

Second problem, maybe unrelated, I noticed that after the new block is found and new target pool is set the same getwork result is repeatedly sent to the new pool such as:

1:42:22|rpcworklog: RPC request [873bb000] submitted to bclc
01:42:22|api: deepbit:  99314           3548.0gh/s 
01:42:22|diff: Updating Difficulty of SolidCoin
01:42:23|api: namebit api error:namebit - unable to extract shares from response using regexp
01:42:23|api: bitclockers:      1146982         207.8gh/s 
01:42:23|rpcworklog: RPC request [873bb000] submitted to bclc
01:42:24|diff: Updating Difficulty of Geist Geld
01:42:24|rpcworklog: RPC request [getwork] submitted to deepbit
01:42:25|rpcworklog: RPC request [873bb000] submitted to bclc
01:42:25|api: bitparking api error:'api_key'
01:42:26|rpcworklog: RPC request [getwork] submitted to deepbit
01:42:27|rpcworklog: RPC request [4f81e000] submitted to deepbit
01:42:27|rpcworklog: RPC request [getwork] submitted to deepbit

873bb000 was sent to bclc two more times before this, only I didn't manage to get it in time.

In any case it is operational for me at the moment.
Thanks for fixing the issue!

**Comment by vcaxx** [comment]
It is locking up again.
Now it happened 3 times so on work submit. Once it was immediately on the first work submit, the second time it worked for 2 hours, and now it blocked after aprox 30mins of operation.

Output:

08:53:01|rpcworklog: RPC request [getwork] submitted to mtred
08:53:01|api: eligius api error:'NoneType' object has no attribute 'group'
08:53:02|lp: Long Poll Call http://btcproxy.net:80/LP
08:53:03|rpcworklog: RPC request [4243e000] submitted to mtred
08:53:03|rpcworklog: RPC request [e24b1000] submitted to mtred
08:53:04|rpcworklog: RPC request [getwork] submitted to mtred
08:53:05|database: DB: writing to database
08:53:05|rpcworklog: RPC request [getwork] submitted to mtred
08:53:06|rpcworklog: RPC request [ed587000] submitted to mtred

It just hangs there, does not accept Ctrl-C, no web interface - it has to be manually kill-ed.

And if it helps, I have 8 miners all of them using phoenix 1.7.5, total close to 3GHsh

**Comment by c00w** [comment]
I think I am still having some deadlocks in the database locks. I'll update them.

**Comment by c00w** [comment]
I updated the locks. Can you fix rerun it and tell me if this issue still exists?

**Comment by vcaxx** [comment]
No lockups during 24h. I close the issue.
