### ISSUE TITLE
Bitcoinpool.com stats wrong

### ISSUE THREAD

**Issue by Endeavour79** [c00w/bitHopper#589]
bitcoinpool stats are wrong again.

**Comment by Locky7** [comment]
Share count, speed?

**Comment by Endeavour79** [comment]
Shares/Round.. so all work is send to bitcoinpool again.. we had this in the past already.

**Comment by Locky7** [comment]
I have been looking at this, and I noticed that my share count was not resetting after finding a block.  So, my issue looks different from https://github.com/c00w/bitHopper/issues/619.  However, your description looks similar to 619?

Round shares are estimated from the current round stats page, looking to see if that has changed

**Comment by macboy80** [comment]
Using rateduration again, everything is working again... Just updated.

**Comment by c00w** [comment]
So i should close the issue?

**Comment by Locky7** [comment]
It works, so close.
