### ISSUE TITLE
We serve too many getworks. Write a limiting function.

### ISSUE THREAD

**Issue by Endeavour79** [c00w/bitHopper#590]
when using Bh newest version, all pools are shown as lagging. 2.xx versions work fine.

(using gevent x.13.6xx)

**Comment by c00w** [comment]
The tip is working. Its not perfect however. Once we resolve the latest issues I'll tag 0.3.1 as stable. everything after 2.6.6 is not stable.

**Comment by c00w** [comment]
Tip is even better. All pools lagging is a function of too many getworks. I'll write a limiter.

**Comment by Clipseza** [comment]
Wouldnt it just be better to have rollntime support within bithopper ? That would solve all getwork spam issues aswell as network wastage.

**Comment by c00w** [comment]
We do support rollntime if the pool supports it.

**Comment by Clipseza** [comment]
ah thought bithopper as a metapool could enforce it on its own wether the actual pool supports it or not.

**Comment by c00w** [comment]
Done with this.
