### ISSUE TITLE
Latest pull high rejects

### ISSUE THREAD

**Issue by Clipseza** [c00w/bitHopper#592]
Well not sure how to test for the culprit however it seems there is excessive rejects occurring due to requested shares not being submittied to the proper share owner(pool).

Ive open other issues thread regarding this however wondered if there is users who have high rejects but the shares is being submitted to the correct pools at all times?

**Comment by c00w** [comment]
Is this still an issue with the latest version?

**Comment by c00w** [comment]
After emailing Clipseza I'm closing this issue. while LP is broken the rejects are fixed.
