### ISSUE TITLE
Request for inclusion of GPUMAX as a pool

### ISSUE THREAD

**Issue by Transisto** [c00w/bitHopper#593]
https://gpumax.com/dashboard
http://gpumax.com:8332
passwords are abc123 by default

I think default role could be backup with a sub 1 penalty.

Heard about pools-custom.cfg ,  could there be a blank pools-custom.cfg file , not sure if it even work since it's not documented.

**Comment by c00w** [comment]
It works. We are moving to a new system though so its going to vanish soon.

**Comment by Locky7** [comment]
I'll do this if I get an invite...  Requested it today

**Comment by Transisto** [comment]
no care actually

**Comment by Transisto** [comment]
I'd need this,

**Comment by Locky7** [comment]
I did get an invite, but just sat on it until today.  I looked at the site and the OP, however, I am not completely clear on what to do.  

Also, Non-Supported Pool - BitHopper - High Stales/Rejects is not applicable to what we are doing, we are just concerned with a setting up a worker(s) and using them as a backup role, right?  

Also, just create a test file in bitHopper named "pools-custom.cfg" and copy/paste a pool from pools.cfg into it and save after you make your changes.

**Comment by c00w** [comment]
Just add them to pools.cfg.

**Comment by Locky7** [comment]
Word...  https://github.com/c00w/bitHopper/pull/641 not much info though...

Thanks c00w!
