### ISSUE TITLE
btcnet_info dir is empty.. it works better with stuff in it both linux and windows

### ISSUE THREAD

**Issue by joulesbeef** [c00w/bitHopper#597]
doing a git update for some reason doesnt add the btcnet_info files, so it breaks the newest hopper.
you can manually download and place the files and it works

**Comment by c00w** [comment]
Um, they should be downloaded by the script. did you install pythongit?

**Comment by c00w** [comment]
Or you can do git update --recursive.

**Comment by joulesbeef** [comment]
ahh we need pythongit? that must be my problem then

as now the thing is complaining i dont have the git module.

**Comment by joulesbeef** [comment]
ok I should have read teh read me...but now I have a different issue
