### ISSUE TITLE
api_strip not implemented in json

### ISSUE THREAD

**Issue by Gnaget** [c00w/bitHopper#60]
simple fix modify pool.py:

<pre>
        if server['api_method'] == 'json':
            info = json.loads(response)
            for value in server['api_key'].split(','):
                info = info[value]
            if 'api_strip' in server:
                strip_str = server['api_strip'][1:-1]
                info = info.replace(strip_str,'')
            round_shares = int(info)
            self.UpdateShares(args,round_shares)
</pre>

I added in the api_strip check, this works for me

**Comment by c00w** [comment]
I added it when I saw it on the forums.
