### ISSUE TITLE
httplib2 ?

### ISSUE THREAD

**Issue by Transisto** [c00w/bitHopper#602]
"Removed httplib2 since we are no longer embedding it and btcnet uses it also "

I'm getting :
 root@new:~/bitHopper# ./bitHopper.py
Traceback (most recent call last):
  File "./bitHopper.py", line 34, in <module>
    import work
  File "/root/bitHopper/work.py", line 10, in <module>
    import httplib2_7_2 as httplib2
ImportError: No module named httplib2_7_2

Seems like I have httplib2 installed : 
root@new:~/bitHopper# pip install httplib2

Requirement already satisfied (use --upgrade to upgrade):

root@new:~/bitHopper# pip install --upgrade httplib2

Downloading/unpacking httplib2
  Downloading httplib2-0.7.2.tar.gz (87Kb): 87Kb downloaded
  Running setup.py egg_info for package httplib2
Installing collected packages: httplib2
  Found existing installation: httplib2 0.7.2
    Uninstalling httplib2:
      Successfully uninstalled httplib2
  Running setup.py install for httplib2
Successfully installed httplib2

**Comment by c00w** [comment]
Shoot.

**Comment by c00w** [comment]
Fixed.
