### ISSUE TITLE
Fix __init__() got an unexpected keyword argument 'disable_ssl_certificate_validation'

### ISSUE THREAD

**Issue by littleant** [c00w/bitHopper#605]
I just updated bitHopper and now get these errors:

16:17:17|api: arsbitcoin api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: btcg api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: mtred api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: asspenny api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: bcpool api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: bitchomp api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: bitfarms api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: bitp api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: bitpenny api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: btcmine api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: btcserv api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: coinotron api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: guildminers api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: itzod api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: masterpool api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: namebit api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: nmcbit api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: nofeemining api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: ozco api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: yourbtc api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: slush api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: triple api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: deepbit api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: bitclockers api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: bithasher api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: bloodys api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: digbtc api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: kiwipool api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'
16:17:17|api: simplecoin api error:**init**() got an unexpected keyword argument 'disable_ssl_certificate_validation'

I tried to solve it myself, but Google isn't very helpful with this error.

Could this be a httplib2 version incompatibility? I've followed the README, though. I've Ubuntu 11.10.

**Comment by c00w** [comment]
Yes it is. I modified the readme which should hopefully fix it. You probably don't have ssl libs installed.

**Comment by littleant** [comment]
Thanks, I did
sudo pip install gevent setuptools gitpython httplib2 --upgrade
and it solved the issue!
