### ISSUE TITLE
socks error 10053 / 10054

### ISSUE THREAD

**Issue by Clipseza** [c00w/bitHopper#607]
So this issue still persist, I reported on this a while ago so I have to run my farm on 3 hopper setups which is pretty flakey and obviously feel unneccesary/impractical unless you could figure out why winsock is closing connections, same thing occurs on windows and linux setups.

Just some random explaination around these error codes:

http://geekswithblogs.net/Lance/archive/2005/06/16/WinsockError10053.aspx
http://geekswithblogs.net/Lance/archive/2007/08/07/Winsock-Error-10054.aspx

**Comment by c00w** [comment]
You shouldn't be getting winsock errors on linux. Can you show me the error traceback? winsock errors are windows socket errors.

**Comment by Clipseza** [comment]
Yeh sorry explained it wrong, only windows its winsock related and on linux it actually had a different error but of similar nature (ye this doesnt tell you much) 

I need to fire up the linux setup with latest version and see what the exact error is, sorry.

**Comment by c00w** [comment]
If you can show me the traceback for the windows error as well I might be able to figure out what is going on. Often these errors either appear because stuff breaks between us and the pool or us and the miner. It shouldn't take down bitHopper however.

**Comment by Clipseza** [comment]
Yeh Ill do that, not on the win machine atm but as soon as I am will try log the error again.

I think the biggest windows issue right now is since moving to gevent and the lagging of servers, should prob take priority to get resolved maybe that would even be something that solved the winsock issue considering I could never get latest gevent version to run long enough to test if it will fail with winsock.

**Comment by Clipseza** [comment]
Yo c0w, can you get back to me on the email I send you. shoto :)

edit: Do you have a different email I can contact you on, seems the mail I send to the email in your profile on github is rejecting email.

**Comment by c00w** [comment]
I got your email.

**Comment by c00w** [comment]
Closing this issue as it is fixed.
