### ISSUE TITLE
No valid pools configured, although my user and pool.cfg are good

### ISSUE THREAD

**Issue by vcaxx** [c00w/bitHopper#613]
With the last update I get:

bitHopper: Fatal Error, No valid pools configured!
..
..
..
..

16:29:18|pool: Please configure some pools
16:29:18|pool: Please configure some pools
16:29:18|pool: Please configure some pools
16:29:18|pool: Please configure some pools
16:29:19|pool: Please configure some pools
16:29:19|pool: Please configure some pools
16:29:19|pool: Please configure some pools

and bitHopper stays there, repeating in the loop.

My pools.cfg and user.cfg worked with the last version, and I cannot see any diferences in the new default cfg files.

Am I missing something in configuration, or this is a bug?

**Comment by c00w** [comment]
Go to localhost:8337/worker

**Comment by vcaxx** [comment]
Does it have to be 8337? My bitHopper is on a remote machine at port 9595. It seems that it doesn't start (or go far enough) to load the port configuration.

In short, I don't see anything on mymachine.com:9595/worker so I can not set anything. 
Can this be set in config files? Can worker page be redirected to a specific port?

Just to add, that there is nothing on mymachine.com:9595/stats nor /lpworkbench - and those two  show stats and workbench ;)
with the previous version

**Comment by c00w** [comment]
Um. There should be something there... You can also just manually edit worker.cfg
ex:
[slush]
user1:pass1
user2:pass2

**Comment by vcaxx** [comment]
Aren't those the same user passwords already present in user.cfg? Why the redundancy?

And, I am positive that there is nothing on 9595 port - it is set in bh.cfg. At this moment I cannot check if there is anything on 8337. I will check it in few hours.

**Comment by vcaxx** [comment]
OK. I fixed it by manually setting user:pass values in worker.cfg

/worker page now available on port 9595 - if you could fix it so it appears on the configured port no matter if workers.cfg is set or not would be nice.

What is the idea behind multiple workers on a pool? Can they be forwarded to  the bitHopper workers with the same name? Otherwise, how one uses the multiple workers?

Thanks!

**Comment by c00w** [comment]
We automatically distribute between the workers. The old configuration system couldn't handle this so I rewrote it and gave it a nicer user interface.

**Comment by c00w** [comment]
Also I rewrote the error message so it makes a little more sense.

**Comment by c00w** [comment]
I opened another issue so I'm going to close this issue and use that one as the placemarker for this bug.
