### ISSUE TITLE
Mining on an info pool

### ISSUE THREAD

**Issue by vcaxx** [c00w/bitHopper#619]
The version I got from git yesterday spent a couple hours mining on bitcoinpool.com although it is set to info role.
Let me know if you changed anything in the current version (I just got it) which would fix this.
Right now bitcoinpool is on disabled list.

**Comment by c00w** [comment]
Hmmm. If it was the only pool that had a username and password then it would default down to it.

**Comment by vcaxx** [comment]
It shouldn't have been. However, I noticed that two last updates overwrite my workers.cfg so I had to get it from the backup or otherwise I would have to manually add workers. So this may have happened

I think workers.cfg should not be updated with every pull request. Maybe change it to workers.cfg.default in master?

**Comment by c00w** [comment]
Now we don't overwrite. And we have a new system for selecting pools that should fix this.
