### ISSUE TITLE
please add default_row to your server list

### ISSUE THREAD

**Issue by flower1024** [c00w/bitHopper#62]
so i have the possibilty to add this to the stats page:
- disable/enable of backup server
  - better support of mine_slush, mine_btc and mine_nmc

(atm they all will go to mine if you enable them)

**Comment by c00w** [comment]
What would default_row be? The role they started with?

**Comment by flower1024** [comment]
i mean like that:

[poolmunity]
role:disable
default_role:mine

[bitcoin.cz]
role:mine_slush
(optional) default_role:mine_slush (optional means, just the same as role)

that way the green enable button in the frontend could always switch to the default_role instead of "mine". which is useful as you had mine_nmc, mine_btc and mine_slush built in now.

**Comment by c00w** [comment]
Okay. I'm going to add a default_role in the pool data but It won't be in pool.cfg. It will equal the role they started with so it may be disable.

Would you like me to have it be mine instead of disable in that case?

**Comment by flower1024** [comment]
mine would be better :)
i'll make the html changes tomorrow.

i could do the changes in pool.cfg.py for you - i just don't want to mess with the parser.

thanks

**Comment by c00w** [comment]
Its implemented.

**Comment by c00w** [comment]
Oh and I added a users data api piece which gives you share count per user. If you could add that it would be awesome.

**Comment by flower1024** [comment]
i'll add it it too, thank you

**Comment by c00w** [comment]
Oh and there is now an expected_payout which takes into account difficulty. we should probably change it to be used for the payout scheme. If you don't add it I can, but I'll wait until your latest changes so as not to screw up your merging.

**Comment by flower1024** [comment]
no problem, i'll do it.
yesterday i considered a direct connection o bitcoind (for getting payout). but its not easy to do this pure-client-side (security cross domain policys) (and you would have to made accounts in bitcoin with the same name as in pool.cfg).

so i thought about adding a small proxy to your python code (which just proxy the http request to a specified ip+port) [i guess i could write that mysqlf]

what do you think about that?
i am not sure if this isn't better in bitHopper itself (but my python skills are still not that good)

**Comment by c00w** [comment]
I can write the interface to bitcoind pretty quickly. But the issue is how to figure out which account belongs to which pool. it would have to be either web or hardcoded which would be annoying. I'm still thinking about it.

**Comment by flower1024** [comment]
i used the pool.cfg account name in bitcoin comment field. so its just a simple match ({"jsonrpc": "1.0", "id":"js", "method": "getaddressesbyaccount", "params": ["mtred"] }.
another additional difficulty is that one account name (eg mtred) could have multiple addresses.

bitcoin json rpc api (if you don't know yet):
https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_Calls_list

**Comment by c00w** [comment]
Yeah I know the api. But I wanted it to be a little more slick. But if thats all you want I can write up a bitHopper module tommorow which serves that info and updates every pool.

**Comment by c00w** [comment]
And pushes it to the payout column in the data for you and caches it in the database.

**Comment by flower1024** [comment]
^^ of course :)

if you have a better idea regarding bitcoin connection just tell me.... i don't want to have my own fork (too much work and hazzle)

btw. i am at work now... means you can change what you want until the next ten hours. i'll merge your changes before i start

**Comment by c00w** [comment]
I should be sleeping for the next ten hours. I'll only make clientside changes though. So your html/ecmascript is safe.

**Comment by c00w** [comment]
When I start working in about 10 hours.

**Comment by c00w** [comment]
Its implemented. Good luck.
