### ISSUE TITLE
mine_LP not working

### ISSUE THREAD

**Issue by vcaxx** [c00w/bitHopper#621]
Shares on those two keep rising the last day and half. I did a pull in the meantime but they are still only going up.
Furthermore, in lpworkbench there are few blocks detected as owned by deepbit, but that did not affect shares.

On the other hand, bitclockers shares are reseted - so far it seems correctly...

**Comment by c00w** [comment]
I found a bug in the LP system. Can you update to the latest and see if it fixes this?

**Comment by vcaxx** [comment]
I updated from the repository. After a couple of hours lp detecting is still not working for deepbit and the rest of Prop pools.

Even, the previously working, bitclockers seems suspicious, as it started from 100% and kept growing - though it might be that the percentage was close to 100 so I can am not sure about it.

**Comment by vcaxx** [comment]
OK with the latest update it seems that lp is working again.  So far confirmed only on deepbit, but let me run it for a day and I will close the issue if other pools work as well.

**Comment by vcaxx** [comment]
UPDATE: So far only deepbit is mined through LP. However I still can not point the finger at bitHopper as there is problem with detecting block owners at bitcoinwatch as well.

It seems that lpworkbench is pulling the owner data from there. Is that right?

I would wait till the situation with block owners is resolved before closing this bug.

Don't know if related, but for some blocks lpworkbench page gives -1330297494.5084 as the offset time for detection by some of the pools.

**Comment by vcaxx** [comment]
OK, it is still not working.
Deepbit is again at 3000+%, out of the others just once hopper switched to bitlc but I believe it had more than one block, as it might be seen in verified blocks in lpworkbench.

The huge negative number still appears constantly as the pool LP delay in lpworkbench. I suspect this might be the reason for bad lp detection.

**Comment by c00w** [comment]
Ok I'll take a look.

**Comment by vcaxx** [comment]
I found a workaround. 
lpworkbench has been showing that 80+% of blocks are found by bitparking.net
So, I disabled bitparking for BTC (all others are already disabled) and now lp seems to be working properly for the last few hours. I hope this helps in finding the bug.

**Comment by c00w** [comment]
Hmmm. I wonder if bitparking is screwing something up. I'll take a look at their LP's.

**Comment by c00w** [comment]
I'm going to close this issue as it is working but tuning is difficult.
