### ISSUE TITLE
No warnings about bh.cfg and user.cfg

### ISSUE THREAD

**Issue by MobiusL** [c00w/bitHopper#622]
xx@xx:~/bitHopper$ ./run-bithopper.sh 
10:07:09|btcnet_wrapper: Trying to initialize btcnet_info repo
10:07:09|btcnet_wrapper: Checking if it has been cloned properly
10:07:09|btcnet_wrapper: It has been cloned properly
10:07:09|btcnet_wrapper: Updating btcnet_info
10:07:10|btcnet_wrapper: Done

**Comment by MobiusL** [comment]
There are no warnings that bh.cfg and user.cfg are missing

**Comment by c00w** [comment]
... Is btcnet_info not there? That seems to be the correct output.

**Comment by MobiusL** [comment]
Hi
I forgot to copy back the user.cfg, bh.cfg and pools-custom.cfg when I 
did a fresh install,

I noticed it did not give any notice that those cfg files were missing. 
It just started and then terminated with that msg

**Comment by c00w** [comment]
Okay. I'll see if I accidentally deleted them.

**Comment by c00w** [comment]
Closed as we no longer use these files
