### ISSUE TITLE
Whenever a new block starts some servers start lagging

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#625]
Got a little problem, whenever a new block starts some servers start lagging and i get errors in the shell.

Does somebody know how to fix it? I am running a VM in Fusion (Ubuntu 11.10 x64).

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 390, in run
    result = self._run(_self.args, *_self.kwargs)
  File "bitHopper.py", line 185, in delag_server
    data, headers = self.work.jsonrpc_call(server, [])
ValueError: too many values to unpack
<Greenlet at 0x321d0f0: <bound method BitHopper.delag_server of <__main__.BitHopper instance at 0x3193cf8>>> failed with ValueError

13:30:10|website: Error in a wsgi function
13:30:10|website: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/ivan/bitHopper/website.py", line 275, in handle_start
    return use_site.handle(env,start_response)
  File "/home/ivan/bitHopper/website.py", line 284, in handle
    return self.bitHopper.work.handle(env, start_response)
  File "/home/ivan/bitHopper/work.py", line 181, in handle
    server, auth = self.bitHopper.getwork_store.get_server(data[0][72:136])
TypeError: 'NoneType' object is not iterable

(posted by callmeivan @ https://bitcointalk.org/index.php?topic=26866.msg760028#msg760028)

**Comment by c00w** [comment]
Those are two errors. I can fix one easily!

**Comment by c00w** [comment]
Figured out the second one. Both fixed.

**Comment by paraipan** [comment]
you rock c00w, like always :)
