### ISSUE TITLE
shares exp: x100 - decimal shift error

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#627]
owowo: o have a decimalpoint error
owowo: shares exp: x100?!
paraipan: lol
paraipan: did you open an issue on git ?
owowo: no
paraipan: easier for c00w to see
owowo: i have this in some old version and in the latest too
owowo: did not change anything, i just appeared

**Comment by c00w** [comment]
Ok.

**Comment by c00w** [comment]
Should be fixed in 0.3.2
