### ISSUE TITLE
LP Workbench (Owner undefined) / Deepbit share count doesnt reset itself

### ISSUE THREAD

**Issue by callmeivan** [c00w/bitHopper#628]
Deepbit share count doesnt reset despite being recognised as a deepbit Block.

LP Workbench doesnt recognise the owner.
http://i.imgur.com/s5rdG.jpg

03:54:40|lp: New Block: 0000000000000019257e811e879a2d9d0bcc45f295d9ffa962e6d060eb45d0ba
03:54:40|lp: Block Owner deepbit
Traceback (most recent call last):
  File "/home/ivan/bitHopper/lp.py", line 144, in add_block
    hook_start.notify(self, block, work, server)
  File "/home/ivan/bitHopper/peak/util/plugins.py", line 58, in notify
    for hook in self.query(_args, *_kw):
  File "/home/ivan/bitHopper/peak/util/plugins.py", line 68, in query
    yield hook(*args)
  File "/home/ivan/bitHopper/plugins/lpdump/lpdump.py", line 41, in on_block
    fd = open(self.file_name, 'brwa+')
ValueError: mode string must begin with one of 'r', 'w', 'a' or 'U', not 'brwa+'
03:54:41|lpbot: New Block: {deepbit} - 0000000000000019257e811e879a2d9d0bcc45f295d9ffa962e6d060eb45d0ba

**Comment by c00w** [comment]
Disable lpdump for now. Its dieing and breaking the setup stream. I'll take a look and try and fi xit.

**Comment by c00w** [comment]
This should be fixed. I changed the file write mode.
