### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by cuzzer** [c00w/bitHopper#634]
Followed all the instructions but when I run bithopper.py a dos box opens and then goes away.  Nothing on http://localhost:8337/ will connect. I'm assuming the program is not launching correctly or its a router issue. I'm using windows 7 64bit.

**Comment by c00w** [comment]
You didn't install one of the libraries correctly. That DOS window should stay open.

A way to get the error message is to do the following:
Hit windows+r, type cmd and hit enter
You are now at a command prompt.

If bitHopper is installed at C:\users\example\bithopper\bithopper.py

Type:
C:\python2.7\python.exe C:\users\example\bithopper\bithopper.py

Then hit enter. It should pop up some message about what failed.

**Comment by cuzzer** [comment]
Thx, I got it running now. It displays:

Please configure some pools!
go to localhost:8337/workers

It shows the proper list of pools on the workers page, with username
and passwords blank. I've tried filling them in. Does not seem to do anything. I've also
filled in the username and passwords on user.cfg and run "run-bithopper.bat" then restarted 
bithopper.py The correct list of pools shows up on the stats page. Not sure what I'm missing, I looked over 
the instructions several times.

**Comment by c00w** [comment]
You need to set up workers on backup pools. Something like arsbitcoin or eligius. Then restart.
