### ISSUE TITLE
Bitlc.net wrong API results

### ISSUE THREAD

**Issue by Endeavour79** [c00w/bitHopper#636]
Bitlc.net  API brings wrong stats for shares/round. Shares are much lower than real so much more work is send to Bitlc.net.

**Comment by c00w** [comment]
bitlc.net is actively trying to spoof bitHopper. Don't hop it unless you know what you are doing and have the time to stay on top of it. I'll try and switch them to something else.

**Comment by Endeavour79** [comment]
Thanks
