### ISSUE TITLE
BTC Difficulty set at 1,000,000

### ISSUE THREAD

**Issue by Locky7** [c00w/bitHopper#644]
on 0.3.2 and whatevercoin.cfg has recent_difficulty = 1379647.43921, but the difficulty diplays a cool million...  When back in versions and I think it happens on installs that require online update/install of dependencies (gevent?.)

**Comment by c00w** [comment]
run pip install btcnet_info. Also the work isn't quite finished yet. At all.

**Comment by Locky7** [comment]
Back on 3.1.5, ran pip install btcnet_info, still stuck at a million:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 325, in run
    result = self._run(_self.args, *_self.kwargs)
  File "C:\Python27\Lib\site-packages\bitHopper\diff.py", line 38, in update_difficulty
    for coin in btcnet_info.get_coins():
  File "C:\Python27\Lib\site-packages\bitHopper\btcnet_info__init__.py", line 29, in get_coins
    return local_api.get_coins()
AttributeError: 'NoneType' object has no attribute 'get_coins'
<Greenlet at 0x2c257b0: <bound method Difficulty.update_difficulty of <diff.Difficulty instance at 0x02C66AF8>>> failed with AttributeError

**Comment by c00w** [comment]
Rerun it. The previous pip install version was broken.

EDIT:
run:
sudo pip install --upgrade btcnet_info

**Comment by Locky7** [comment]
Worked, thanks!
