### ISSUE TITLE
bitcoin difficulty off by .030

### ISSUE THREAD

**Issue by netxshare** [c00w/bitHopper#645]
the current diff is 1496978.595025, I am trying to figure out why bitHopper reports it as 1496978.625.

Anyone have any ideas?

**Comment by netxshare** [comment]
from what I have gathered it seems to be getting that diff from this page http://allchains.info/calc.html

**Comment by c00w** [comment]
Yes. Its not a huge bug.

**Comment by c00w** [comment]
As the difficulty has moved on we are closing this issue.
