### ISSUE TITLE
Greenlet error

### ISSUE THREAD

**Issue by Endeavour79** [c00w/bitHopper#651]
14:44:59|pool: pools-custom.cfg not found.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 325, in run
    result = self._run(_self.args, *_self.kwargs)
  File "C:\bithopper\diff.py", line 38, in update_difficulty
    for coin in btcnet_info.get_coins():
  File "C:\bithopper\btcnet_info__init__.py", line 29, in get_coins
    return local_api.get_coins()
AttributeError: 'NoneType' object has no attribute 'get_coins'
<Greenlet at 0x28c6ad0: <bound method Difficulty.update_difficulty of <diff.Diff
iculty instance at 0x0291EEE0>>> failed with AttributeError

**Comment by c00w** [comment]
Did you install btcnet_info using pip? In that case you want to update it using:
sudo pip install --upgrade btcnet_info

**Comment by Endeavour79** [comment]
Hi. I'm using Windows and followed the instructions in readme. Didn't install any btcnet.

**Comment by c00w** [comment]
Ok. Due to the weird way that btcnet is installed in the current version I would recommend deleting the bitHopper folder and re-downloading it. That should fix your problems.
