### ISSUE TITLE
Ninjacoin is dead

### ISSUE THREAD

**Issue by Locky7** [c00w/bitHopper#652]
08:39:34|node: https://www.ninjacoin.com/
08:39:34|node_handle: Potential type error None, Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\btcnet_info\node_handle.py", line 205, in duration
    duration += float(result.group(index)) \* prefix_multiplier(prefix)
TypeError: float() argument must be a string or a number

**Comment by c00w** [comment]
Removed from btcnet_info
