### ISSUE TITLE
no pools configured 

### ISSUE THREAD

**Issue by cuzzer** [c00w/bitHopper#655]
When I run bithopper.py it displays no pools configured. I configured several pools in user.cfg including backup pools like ars and eligius. http://localhost:8337/stats# seems to show the correct list of pools. Cgminer will not connect to localhost:8337 either. Not sure what I'm doing wrong. I will give a 5btc reward to the person who gets this working correctly for me. 

btw, I'm using windows 7.

**Comment by Locky7** [comment]
open http://localhost:8337/worker from firefox/chrome and enter a username and password for each worker per pool.  You can change localhost for a specific IP if you are configuring bH from a different computer on your network.  Hit "Restore Config" from http://localhost:8337/stats to load the new workers (I only needed to do it once, auto loaded new workers after)  

workers will be stored in worker.cfg and you can edit the list in notepad+ or use the + - buttons on http://localhost:8337/worker 

workers configured in user.cfg are not used in bH v.3+  however is used in 2.7 and below.

2.7 or before - 1 worker per pool
3.1.5 - up to 10 workers per pool...c00w Akbar (c00w is great)

฿itcoin Address: 133jRYb6dbdnZe5TQFoYXnoaK6SXSS4S81

detail are outlined in README, open it in notepad+

**Comment by cuzzer** [comment]
When I enter pool information into the workers page and hit the button. Nothing seems to happen. Also, workers.cfg is still blank.

(update)
I copied the contents of user.cfg to workers.cfg and it seems to be working. Hard to believe they could be the same thing.

**Comment by Locky7** [comment]
What browser are you using? 

Here is the format for worker.cfg:

[asspenny]
MartyChubbs.0 = vikings
MartyChubbs.0 = vikings

[gpumax]
4f55057921fd407c300337e3 = abc123
4f54edc021fd4028e20cc682 = abc123

[donation]

**Comment by c00w** [comment]
@cuzzer Copying them won't work. It'll generate users but they are invalid so you won't get any payout...

**Comment by c00w** [comment]
Also cuzzer the workers page only works in chrome. This will be fixed in 0.3.2

**Comment by cuzzer** [comment]
Got it working with crome, I was trying to do it with firefox.
