### ISSUE TITLE
custom pool

### ISSUE THREAD

**Issue by cuzzer** [c00w/bitHopper#656]
Is it difficult to add a custom backup pool? What files need to be modified?

**Comment by Locky7** [comment]
Create a text file in the bitHopper folder named "pools-custom.cfg" and copy/paste a pool from pools.cfg into it,  make your changes and save.

**Comment by cuzzer** [comment]
I put the following in pools-custom.cfg, I don't see that it did anything. Worker information is all I have on the pool, no api key.

[custompool]
coin:btc
name: custompool (PPS)
mine_address: 216.231.138.132:9332
api_method: re
api_key: code
url: http://project2.tygrr.com
payout_scheme: pps

**Comment by c00w** [comment]
Give it an api method of disable. Not code. Should fix it.

**Comment by cuzzer** [comment]
I changed it, it didn't show up on worker list or stats page. Also I have let the program run a couple hours and never seen it switch from the backup pool. Deepbit is mine_lp and slush is mine_c role. I was assuming those were the main to pools for hopping.

**Comment by c00w** [comment]
What you supplied is another backup pool. If you have others configured it's probably not going to do much with this one. Try disabling all other backup pools.

**Comment by cuzzer** [comment]
It's two problems. If I disable all the backup pools it starts using deep or slush. I wanted to set up a more profitable custom backup pool but I also noticed it doesn't seem to be hopping.

**Comment by c00w** [comment]
Hmmm. Thats very wierd. Did you also give it some users?

**Comment by c00w** [comment]
It didn't show up on the workers page? I think I know the problem... Let me check something.

**Comment by c00w** [comment]
Okay, I think I know part of the problem. You need to add a manual entry to worker.cfg such that it looks like:

[custompool]
username: password

**Comment by Locky7** [comment]
I set up "Project 2", please test since I am waiting for access.

https://github.com/c00w/bitHopper/pull/659

I put the pool in user.cfg, so it will be added to worker.cfg on startup...

**Comment by cuzzer** [comment]
I got the custom backup pool working now, thanks. I'm still trying to figure out why its only using backup pools though. It should switch to deepbit or slush often right?

**Comment by c00w** [comment]
Um, no. It only switches when those pools are valid to mine. The slush pool only happens every so often and deepbit takes some fine tuning of the internal engine to make it work for some people. It all depends on your network latencies.

**Comment by Locky7** [comment]
3 pools? one mine_lp, one mine_c, and a backup?  It works.  Please delete your custom pool or custom-pools.cfg and download the latest version from the master (3.1.5-60?) and start from scratch...  I already added project 2 so you can just enter the info in user.cfg and/or worker.cfg and you should be good. 

See how I set up Project 2?  Next time, just copy a similar pool from pools.cfg and place it in custom-pools.cfg, change the info between the [poolname] , mine address, api address, api method for the pool named in [poolname].  Then, create an entry in user.cfg and/or workers.cfg under the same [poolname] as custom-pool.cfg.
You CAN,  create new pools under pools.cfg, however, they will be over-written if you download a new version.
