### ISSUE TITLE
High number of open connections, 1600+ with 20Ghs

### ISSUE THREAD

**Issue by Transisto** [c00w/bitHopper#660]
When I look at the connection list in my router it show ~1500 connection to the mined pool ,  BTCmine in this case 88.214.194.226

Is this normal ?

**Comment by c00w** [comment]
I'm not sure whats going wrong. What version of bitHopper are you using?

**Comment by c00w** [comment]
There should be a pool limiter which stops it from making to many connections. How many of the connections are in the CLOSE_WAIT state?

**Comment by Transisto** [comment]
they're in TIME_WAIT state, I'm using latest with ubuntu.

**Comment by c00w** [comment]
Hmmm. Thats really wierd. And not normal. It means that they are waiting for a little bit before closing. I'm not sure what's up with that. I'll poke around httplib2 and see if they are leaking sockets somewhere.

**Comment by c00w** [comment]
Can you try with the latest version? This should be fixed.

**Comment by Transisto** [comment]
The version from ~1 hrs ago has the same problem.

I've installed on a new OS, next will have to restart my config from scratch to see if it help.

**Comment by c00w** [comment]
Hmmm.

**Comment by c00w** [comment]
So there are two separate issues. Connections between bitHopper and remote servers have been fixed. There were some interesting bugs and we should now be down to <100 sockets.

The other half is connections between bitHopper and mining clients. If you have a high powered rig and you are running out of sockets you need to use uwsgi as a server and bitHopper as a pluggable wsgi module.
