### ISSUE TITLE
BTC Difficulty incorrect

### ISSUE THREAD

**Issue by asdlsd** [c00w/bitHopper#662]
BH ver. 3.1.5 (from git). Difficulty=1,378,647

**Comment by c00w** [comment]
Did restarting fix the problem?

**Comment by MobiusL** [comment]
I'm using v0.3.1.5-66-gd1c0c9a and I have not been able to get the current diff - shows as 1,000,000, I have restarted multiple times, this occured after a fresh install.

**Comment by asdlsd** [comment]
"Did restarting fix the problem?"
no, and reinstalling too

**Comment by c00w** [comment]
pip install btcnet_info --upgrade?

**Comment by asdlsd** [comment]
i did - no result

**Comment by asdlsd** [comment]
i do again and got this

Found existing installation: gevent 0.13.6
    Uninstalling gevent:
      Successfully uninstalled gevent
  Running setup.py install for gevent
    building 'gevent.core' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c gevent/core.c -o build/temp.linux-x86_64-2.7/gevent/core.o
    gevent/core.c: In function ‘__pyx_pf_6gevent_4core_12active_event_1add’:
    gevent/core.c:5220:13: warning: variable ‘__pyx_v_timeout’ set but not used [-Wunused-but-set-variable]
    gevent/core.c: In function ‘__pyx_pf_6gevent_4core_6buffer_7readline’:
    gevent/core.c:7765:13: warning: variable ‘__pyx_v_size’ set but not used [-Wunused-but-set-variable]
    gevent/core.c: In function ‘__pyx_pf_6gevent_4core_6buffer_8readlines’:
    gevent/core.c:8109:13: warning: variable ‘__pyx_v_hint’ set but not used [-Wunused-but-set-variable]
    gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions build/temp.linux-x86_64-2.7/gevent/core.o -levent -o build/lib.linux-x86_64-2.7/gevent/core.so
    Linking /opt/bitHopper/build/gevent/build/lib.linux-x86_64-2.7/gevent/core.so to /opt/bitHopper/build/gevent/gevent/core.so

**Comment by c00w** [comment]
Hmmm. So it looks like btcnet_info isn't working for you. I'll poke around and see whats broken there.

**Comment by asdlsd** [comment]
realties that you need from me...

**Comment by c00w** [comment]
Can you type pip freeze and show me the output?

**Comment by MobiusL** [comment]
here is mine:

aa@BHP:~$ pip freeze
BeautifulSoup==3.1.0.1
Brlapi==0.5.5
CouchDB==0.6
GitPython==0.3.2.RC1
GnuPGInterface==0.3.2
Mako==0.3.4
MarkupSafe==0.9.2
OcempGUI==0.2.9
PAM==0.4.2
PIL==1.1.7
Pyste==0.9.10
SOAPpy==0.12.0
Twisted==12.0.0
Twisted-Conch==12.0.0
Twisted-Core==12.0.0
Twisted-Lore==12.0.0
Twisted-Mail==12.0.0
Twisted-Names==12.0.0
Twisted-News==12.0.0
Twisted-Runner==12.0.0
Twisted-Web==12.0.0
Twisted-Words==12.0.0
adium-theme-ubuntu==0.3
apt-xapian-index==0.39
apturl==0.4.1ubuntu7.1
argparse==1.1
async==0.6.1
btcnet-info==0.1.2.11
ccsm==0.8.2
command-not-found==0.1
configglue==0.9pre1
decorator==3.3.2
distribute==0.6.24
fpconst==0.7.2
fusion-icon==0.1.0
gevent==0.13.6
gitdb==0.5.4
gnome-app-install==0.4.7ubuntu2
greenlet==0.3.4
httplib2==0.7.4
importlib==1.0.2
jockey==0.5.10
jsonrpc==0.01
launchpadlib==1.6.1
lazr.restfulclient==0.9.20
lazr.uri==1.0.2
louis==2.0.0
ltc-scrypt==1.0
mercurial==1.6.3
numpy==1.3.0
nvidia-common==0.0.0
oauth==1.0a
onboard==0.94.0
papyon==0.5.1
pefile==1.2.9.1
pexpect==2.3
protobuf==2.3.0
py==1.4.5
py-rrdtool==0.2.1
pyOpenSSL==0.10
pyPdf==1.12
pyasn1==0.0.11a
pycrypto==2.0.1
pycups==1.9.51
pycurl==7.19.0
pygame==1.9.1release
pyinotify==0.8.9
pymssql==1.0.2
pyopencl==0.92
pyserial==2.3
pysmbc==1.0.8
pysqlite==2.6.0
python-apt==0.7.96.1ubuntu11.2
python-debian==0.1.16ubuntu1
python-virtkey==0.60.0
pytools==2011.5
pyxdg==0.19
rdflib==2.4.2
scipy==0.7.2
screen-resolution-extra==0.0.0
sessioninstaller==0.0.0
simplejson==2.1.1
smmap==0.8.2
speechd==0.3
speechd-config==0.0
system-service==0.1.6
ubuntu-sso-client==1.0.9
ubuntu-tweak==0.5.14
ubuntuone-storage-protocol==1.4.0
ufw==0.30.0-1ubuntu2
unattended-upgrades==0.1
usb-creator==0.2.23
vboxapi==1.0
wadllib==1.1.4
wsgiref==0.1.2
wxPython==2.8.11.0
wxPython-common==2.8.11.0
xkit==0.0.0
zenmap==5.21
zope.interface==3.6.1

**Comment by asdlsd** [comment]
root@Debian-60-squeeze-64-minimal ~ # pip freeze
GitPython==0.3.2.RC1
async==0.6.1
btcnet-info==0.1.2.10
distribute==0.6.25
gevent==0.13.6
gitdb==0.5.4
greenlet==0.3.4
httplib2==0.7.4
smmap==0.8.2
wsgiref==0.1.2

**Comment by c00w** [comment]
I found some bugs and updated the starting value in btcnet_info.

Run:
sudo pip install btcnet_info --upgrade

**Comment by asdlsd** [comment]
yes. it works )
thanks and litle donation )

PS. what command to update correctly from git? git merge git://github.com/c00w/bitHopper.git?

**Comment by c00w** [comment]
Just type git pull from inside the bithopper folder.
To update the polling type
sudo pip update btcnet_info --upgrade
