### ISSUE TITLE
wrong difficulty after change difficulty

### ISSUE THREAD

**Issue by asdlsd** [c00w/bitHopper#663]
today difficulty was 1,626,627. 
after restart BH is 1000000
after pip install btcnet_info --upade is 1,626,553 again (

**Comment by c00w** [comment]
It takes a little time for bitHopper to sync with the current difficulty. I'll take a look at making it better or perhaps offering better hooks on difficulty updates.

**Comment by asdlsd** [comment]
I not completely understood. difficulty in my BH will corect over time?

**Comment by c00w** [comment]
Yes. It sometimes takes a bit for it to synchronize properly.

**Comment by asdlsd** [comment]
3 days ago and not synchronize... statistic and effectivity will be incorrect (
it's for all or only fo me?

**Comment by c00w** [comment]
1,626,553 vs 1,626,627 is a very small difference. It probably is due to various sources disagreeing slightly.

**Comment by asdlsd** [comment]
not small difference. in may BH is 1,626,553, but realy is 1,577,913.

**Comment by c00w** [comment]
I've updated btcnet_info.

sudo pip install btcnet_info --upgrade

**Comment by asdlsd** [comment]
it works. thanks. I hope it is not until next change difficulty )
