### ISSUE TITLE
No module named geventhttpclient on latest update

### ISSUE THREAD

**Issue by MobiusL** [c00w/bitHopper#666]
Occurs on both Ubuntu 10.10 and 11.10

Traceback (most recent call last):
  File "bitHopper.py", line 34, in <module>
    import work
  File "/home/aa/bitHopper/work.py", line 14, in <module>
    import geventhttpclient
ImportError: No module named geventhttpclient

**Comment by Transisto** [comment]
Same

**Comment by c00w** [comment]
Update again. Those versions were unstable. I was trying to fix socket leaking at high ~100GH/s load.
