### ISSUE TITLE
work: Not in pool

### ISSUE THREAD

**Issue by Delta1977** [c00w/bitHopper#668]
I get the message: work: Not in the pool.

 Where does the message and what effect does this?
 How do I get the fix?

**Comment by c00w** [comment]
Have you configured workers on http://localhost:8337? You need to configure a worker on a valid backup pool such as eligious. If you are getting work then you can ignore the message. 0.3.2 has this fixed but isn't production quality yet.

**Comment by Delta1977** [comment]
That was the problem. I've  three active pools and no backup pool.
 Once I have a backup pool there is no longer the message.
