### ISSUE TITLE
No module named gevent

### ISSUE THREAD

**Issue by enmaku** [c00w/bitHopper#670]
I've installed gevent (and all other dependencies) from the links in the README but when attempting to launch bitHopper.py I get

You need to install greenlet and gevent. See the readme.
Traceback (most recent call last):
  File "C:\c00w-bitHopper-651a759\bitHopper.py", line 15, in <module>
    raise e
ImportError: No module named gevent

This is under Win7 x64 with Python 2.7.2

**Comment by c00w** [comment]
@enmaku It looks like you didn't install gevent. Try: http://gevent.googlecode.com/files/gevent-1.0b2.win32-py2.7.msi

**Comment by c00w** [comment]
Also make sure you only have 32 bit python installed.

**Comment by enmaku** [comment]
I've installed gevent and the other dependencies and it's been a while since I installed python but I'm fairly certain it was 2.7.2 win32. I'm uninstalling and reinstalling now just in case it was the 64 bit version.

**Comment by enmaku** [comment]
I apparently had an old python 2.6 install that all of my paths somehow got pointed back at. Uninstalled all and reinstalled python 2.7 win32 and it appears to be working. Haven't actually configured any workers or started mining but it's at least executing. My apologies for the false alarm.

**Comment by c00w** [comment]
Its ok. Also make sure you configure some backup pools like eligius with the current version.
