### ISSUE TITLE
BH not hopping

### ISSUE THREAD

**Issue by TimLinton** [c00w/bitHopper#672]
My miner just sits on bitcoinpool. It never moves to any other pool to mine on. Just BCPool... If I disable it then it just mines on Mt.Red... And never anything else. then if i disable Mt.Red, then it mines something else forever.. and so on.
Is it not updating the difficulty? Or is it supposed to do this?

**Comment by c00w** [comment]
It is mining on backup pools. It looks like the difficulty updates take about 45 seconds to update. I'll tweak bitHopper to poll more rapidly.

**Comment by TimLinton** [comment]
The problem is it has mined BCPool for days now.. It never moves to anything else.

**Comment by c00w** [comment]
Update btcnet_info. http://pypi.python.org/pypi/btcnet_info

**Comment by TimLinton** [comment]
I'm sorry but its still staying on the same pool.
Maybe im doing something wrong? I don't know..

**Comment by c00w** [comment]
Do you have the username and passwords set up for a pool which is hoppable? Otherwise its just going to sit on backup pools and not do anything.

**Comment by TimLinton** [comment]
It doesn't sit on backup. I have every single one logged in. I recently checked every one of the log ins in my list.

**Comment by c00w** [comment]
bcpool is probably faking their stats again. Don't use them.

**Comment by TimLinton** [comment]
You are correct. After I disabled BitcoinPool, MTRed, and NMCBit, its hopping all over the place.
Thanks
