### ISSUE TITLE
TypeError: float() argument must be a string or a number

### ISSUE THREAD

**Issue by Endeavour79** [c00w/bitHopper#674]
10:34:27|lpbot: Connect returned
10:34:27|node_handle: Potential type error None, Traceback (most recent call last):
  File "C:\bithopper\btcnet_info\node_handle.py", line 210, in duration
    duration += float(result.group(index)) \* prefix_multiplier(prefix)
TypeError: float() argument must be a string or a number

**Comment by c00w** [comment]
This is a btcnet_info error. I'll take a look but it shouldn't effect anything.

**Comment by c00w** [comment]
Is this still showing up? Its not appearing on the latest btcnet_info.
