### ISSUE TITLE
Blocks being Mislabled as deepbit blocks

### ISSUE THREAD

**Issue by JustaPeriod** [c00w/bitHopper#684]
Seems like lpworkbench is labeling every block deepbit even if it isn't actually their block, and it begins hopping deepbit regardless.

**Comment by JustaPeriod** [comment]
http://i.imgur.com/uJwIU.png

**Comment by c00w** [comment]
You have to manually tune the delays. in 0.3.2 We're going to switch to an autotuning method using a DHT. It's not ready yet though.

**Comment by c00w** [comment]
Its sort of ready now.
