### ISSUE TITLE
Stop sending work option

### ISSUE THREAD

**Issue by iopq** [c00w/bitHopper#685]
As you may know, p2pool is unique in that it has a super high amount of long polls and requires really low latency

if p2pool doesn't work well with bithopper, why not allow bithopper to send shares to pools that are worth hopping and if there are no pools that are worth it... just stop sending shares? That way I can configure cgminer to mine bithopper as pool 0 and p2pool as pool 1 and a backup pool as pool 3 (in case bitcoind crashes) and when bithopper stops sending me work it will switch to p2pool
when bithopper sends me work it will immediately start mining bithopper (because it would send a long poll)

is it possible to make an option for bithopper to stop sending work instead of using one of the pools as a "backup" when there is no "backup"?

**Comment by c00w** [comment]
in 0.3.2 that is what happens.

**Comment by iopq** [comment]
I just tried 0.3.2 and I'm mining slush at 33% with mine c and c=300
I should have already hopped off to mining nothing
but instead I switch between deepbit and slush

**Comment by c00w** [comment]
In 0.3.2 deepbit is treated as a backup pool for now.

**Comment by c00w** [comment]
Also p2pool now works with bitHopper.

**Comment by c00w** [comment]
I found another bug, p2pool now works with bitHopper and you don't get insanely high rejects

**Comment by c00w** [comment]
And we now use deepbit as a hoppable pool
