### ISSUE TITLE
bitlc switching to PPLNS soon

### ISSUE THREAD

**Issue by iopq** [c00w/bitHopper#686]
https://www.bitlc.net/blog/pool-switch-to-pplns-reward-system-5?utm_source=twitterfeed&utm_medium=twitter

someone else monitor this so we can update when it happens

**Comment by Locky7** [comment]
Thanks for the update!

**Comment by Locky7** [comment]
Well, 2 weeks becomes months...

**Comment by c00w** [comment]
Haven't switched yet

**Comment by c00w** [comment]
And they are dead now.
