### ISSUE TITLE
penalty should also effect submitted share stats

### ISSUE THREAD

**Issue by JustaPeriod** [c00w/bitHopper#688]
The shares you submit should be multiplied by penalty too. Say you submit 4 shares and have the penalty of the pool set at 2, it should be written on that stats page as 8.

**Comment by c00w** [comment]
I honestly can't remember what the penalty system in 0.3.1 does. But its meant to help sort pools in case they charge fees.

**Comment by c00w** [comment]
On thinking about this more, I'm pretty sure that penalty is not meant to change the share submission stats. I think that if we start mucking with the recorded shares based on penalty its going to make it too complicated.
