### ISSUE TITLE
BUG: ajax updates move scroll 

### ISSUE THREAD

**Issue by Gnaget** [c00w/bitHopper#69]
When scrolled to the bottom of the page, the ajax calls are causing the page to scroll up a few pixels.  Just enough to be annoying.

Firefox 5.0

**Comment by c00w** [comment]
Huh. I'll look into it.

**Comment by c00w** [comment]
Should be fixed in latest changes by sdogi.

**Comment by c00w** [comment]
Its not.

**Comment by c00w** [comment]
Well this page is not in 0.3.2 so I'm closing the issue.
