### ISSUE TITLE
cant add worker in 0.3.2

### ISSUE THREAD

**Issue by Delta1977** [c00w/bitHopper#690]
i install bithopper 0.3.2 on a fresh Ubuntu 11.10.
with
 sudo apt-get install python2.7 git python2.7-dev python-setuptools python-pip libevent-dev
git clone git://github.com/c00w/bitHopper.git
cd bitHopper
sudo python setup.py install
python run.py

i got the error :

22:47:08|ServerLogic|rebuild_servers: No valid pools configured
22:47:13|ServerLogic|rebuild_servers: No valid pools configured

on the worker page i see only a black screen with the text Workers... nothing else..
I can't add a worker..

What do I Wrong?

**Comment by aaferrari** [comment]
See https://github.com/c00w/bitHopper/issues/671#issuecomment-7478095 for solution

**Comment by Delta1977** [comment]
I Solved my problem_

If I Run Bithopper as root, i get blank/black Pages.
If I run Bithopper as a normal user ist all ok.

**Comment by c00w** [comment]
Okay. Thats rather wierd.
