### ISSUE TITLE
Swepool, resurrection or scam?

### ISSUE THREAD

**Issue by aaferrari** [c00w/bitHopper#692]
Maybe this is not the best place to say it, but although Swepool closed in September 2011, recently I discovered in its home page that displays the following text:
<i>Welcome to Swepool, Swedens official Bitcoin p2pool: Connect miner to: swepool.net:9332 - Use your btc-address as username - 0,95% to the server and 0,05% to p2pool-developers.</i>
In BitcoinTalk no announcement about it, so, has anyone ever tested to check if this is legitimate or a scam? I ask because, in addition to that not show stats, do not think it so difficult to buy the domain of a dead pool, install a web page and make it look like authentic so people waste your time mining there.

**Comment by c00w** [comment]
Good point. I think we should just delete it.

**Comment by c00w** [comment]
Hmmm, if its actually a p2pool endpoint though thats interesting. I'm going to just delete them for now

**Comment by c00w** [comment]
It looks like they are already deleted.
