### ISSUE TITLE
'module' object has no attribute 'add_pools'

### ISSUE THREAD

**Issue by littleant** [c00w/bitHopper#693]
This is what I get when I want to run bitHopper after updating to the newest version:

$ python run.py
Traceback (most recent call last):
  File "run.py", line 47, in <module>
    bitHopper.custom_pools()
  File "/home/anty/bitHopper/bitHopper/**init**.py", line 80, in custom_pools
    btcnet_info.add_pools(filenames)
AttributeError: 'module' object has no attribute 'add_pools'

(Ubuntu 12.04)

**Comment by c00w** [comment]
You need to install a newer version of btcnet_info
On linux:
sudo python setup.py install
On windows:
run python.exe setup.py install from the command line

**Comment by littleant** [comment]
That worked, thanks.
