### ISSUE TITLE
Some Pools don't work

### ISSUE THREAD

**Issue by Delta1977** [c00w/bitHopper#694]
Some Pools configured with worker e.e. Deepbit, ABC works good.
Other like EMC dont work .

**Comment by c00w** [comment]
If you tell me which pools don't work I can take a look.

**Comment by Delta1977** [comment]
Ee eclipsemc, Eligius and the missing Option to configure the p2pool Node

**Comment by c00w** [comment]
The p2pool node isn't embedded within bitHopper. Its an interface to a local host p2pool if needed.

**Comment by c00w** [comment]
I'll take a look at the others.

**Comment by Delta1977** [comment]
Ok. 
It wold be nice, if we can configure  the ip and the Port for the p2pool Node. in the Old config i can do iit :-)

**Comment by c00w** [comment]
I should probably move p2pool out of btcnet_info and put it in custom_pools. That way it is simple to configure it otherwise.

**Comment by c00w** [comment]
p2pool is now in the custom_pool directory in bitHopper. This should make it much easier to modify the port

**Comment by c00w** [comment]
Just modify the file and change the mine_address

**Comment by Delta1977** [comment]
the p2pool part works properly.

Thank you

**Comment by c00w** [comment]
Eligius appears to have a bug relating to stratum support.
