### ISSUE TITLE
rejects in the db

### ISSUE THREAD

**Issue by rkozola** [c00w/bitHopper#73]
the user is not used when logging rejects into the db.  they are go under a null user.

**Comment by c00w** [comment]
True. I'll add in per user rejects soonish. But I wanted to get shares done first. And I need to clean up db anyway.

**Comment by c00w** [comment]
Added in bleeding edge bitHopper. If it doesn't work open an issue. And it wasn't very soonish.

**Comment by rkozola** [comment]
does not seem to work.  also appears it broke shares_time and hash_rate.

**Comment by c00w** [comment]
Shoot. I'll take a look.
