### ISSUE TITLE
mine_slush again

### ISSUE THREAD

**Issue by organofcorti** [c00w/bitHopper#76]
Still not working for me. In scheduler.py:

```
     elif info['role'] == 'mine_slush':
        shares = info['shares'] * 4

if current_role == 'mine_slush':
     difficulty = self.bh.difficulty.get_difficulty() * 4
  if current_pool['shares'] > (difficulty * self.difficultyThreshold):
```

Doesn't this mean _both_ shares and difficulty to hop are increased by a factor of 4? So that your time to hop is

shares_4/difficulty_4 = shares/difficulty = default? So instead change difficulty to difficulty_0.25 or shares to shares_4 but not both?

Please excuse me if I'm wrong.

**Comment by c00w** [comment]
No you are right, I'll fix it.

**Comment by c00w** [comment]
Should be fixed.

**Comment by organofcorti** [comment]
I'll give it a go and see. Might take a while to catch it in action though.  Thx so much for such a speedy fix!

**Comment by c00w** [comment]
I'm closing. If its not fixed tell me and I'll try again.
