### ISSUE TITLE
various ideas

### ISSUE THREAD

**Issue by flower1024** [c00w/bitHopper#8]
hi,

what do you think about the following:

1) every pool gets a "from" - "to" share counter

e.g. 
btcguild: from=0 to=difficulty_0.4
minecoin from=difficulty_1.6 to 1.1

and select the pool thats "nearer" the from - in a prozentual view.

2) i use deepbit pps as a failover to eligius.
could your update_server function just skip servers without an api address and iterate through all configured pools? so we can add pools without changing this function (i am sure python has a way to include the update function's name in the servers list itself too. - i am just not an python dev)

3) don't lag the server on the first error. i added an "prelag" feature which means only when a server call fails twice betwenn a delag call its really lagged - this made me very lucke in btcguild 28secs round

4) an option how long to stay at a pool at minimum would be nice (eg. as i understand your code you only switch if the current pool has more than 0.4 shares - i would like to have that configurable - as i prefer switching as soon another pool has found a block - so i would set this option to zero)

if you are interested: a few of this i have implemented in an older version of yours. but you are just that fast that i have no way to followup :)

i really appreciate your good work

**Comment by c00w** [comment]
The delager wait is a good idea. I'll add it in.

 Deepbit? I really dislike using their service. Plus I haven't found any statements that they are actually hopper proof. I think I'm going to use btcmine if it ever comes up, or arstechnica if I can ever log in.  If you want to use it as a backup server just add it and put 'role':'backup' in the server dictionary.

With regards to the from - to counter. Um. I don't understand how that would increase payouts. Or what a prozentual view is.

How long to stay at the pool minimum? You are right the conditional check is wrong. I'll update it to switch if min_shares < .90 \* current shares

**Comment by c00w** [comment]
Oh and we only switch if the current pool has > difficulty \* .40 or a pool has shares which are less than the current pool \* .90. In the latest revision. The 28 second btcguild round is really just luck.

I hit it on bipt.it where I have 800% efficiency.

**Comment by flower1024** [comment]
what i meant with prozentual view (excuse my english) is the following:

btcguild  0 -  diff_0.4
bitclockers  0 -  diff_0.2
minecoin diff \* 1.6 - diff*1.1

that means when btcguild has just found a block it's as "good" as minecoin when minecoin is at diff*1.6 (not sure about the numbers yet) - so it is possible to profit from minecoin like pools also.

what i want to archive also is that i have a way to prioritze pools. in he above example it would stay longer on btcguild than on bitclockers

**Comment by flower1024** [comment]
because the luck:
as i modified your source to switch as soon as a block is found i think my chances are higher (thats why i wanted an option for that).

**Comment by c00w** [comment]
Huh. And if a pool has found a block and has 0 shares, or close to zero shares, we switch to it.

``` python
if pool.get_entry(pool.get_current())['shares'] > diff.difficulty * .10:
        for server in pool.get_servers():
            if pool.get_entry(server)['shares'] < min_shares:
                min_shares = pool.get_entry(server)['shares']

        if min_shares < pool.get_entry(pool.get_current())['shares']*.90:
            select_best_server()
            return
```

**Comment by c00w** [comment]
And I didn't see the if pool.get_entry(pool.get_current())['shares'] > diff.difficulty \* .10: tag.

Removed it.

**Comment by flower1024** [comment]
you are right...i didnt check your current version.
the old version i used sticked with a pool until it lagged or reached 0.4

**Comment by c00w** [comment]
I'm closing this issue for now.
