### ISSUE TITLE
Increase threshhold for mine_slush & decrease mine_nmc

### ISSUE THREAD

**Issue by timonex** [c00w/bitHopper#96]
Not sure of the easiest most compatible way of going about this. Getting disconnected from slush after 5% or so and I'd like it to be around 15%. Also I'd like mine_nmc to disconnect much sooner. Also mine_nmc shows incorrect threshhold and stays connected seemingly forever.

I'm sure this would be easy for someone that reads Greek. It ain't me...unfortunately. :(

**Comment by c00w** [comment]
Um with slush you should be getting disconnected once the threshold crosses 10%. I'll take a look at mine_nmc

**Comment by timonex** [comment]
Thanx c00w, I think I muddled my way into a fix to get nearer the thresholds I was looking for.

**Comment by c00w** [comment]
All of the servers currently have a penalties option as well. So if you want you can just modify the penalties. I'm closing the issue for now.

**Comment by timonex** [comment]
Thanx most excellent doodman! Donation heading yer way...

**Comment by c00w** [comment]
The penalties is a multiplier on the shares.

**Comment by timonex** [comment]
Very nice. A bit more refined than my brutal approach to scheduling changes:

```
     elif info['role'] == 'mine_nmc':
        shares = info['shares']*((difficulty / nmc_difficulty) + 7)
```

The new build was jumping all over the place at first, but I refreshed the stat page and began messing with penalties and reined it in right quick. Now it's purring like a kitten. :)

**Comment by c00w** [comment]
It tries to slice in 30 second blocks. I should add an option to change it to a higher slice.

**Comment by timonex** [comment]
Any idea what happens if I stagger penalties on backup servers? I've been using phantom stale share entries to accomplish this, but penalties or priorities would be far more elegant. Working great so far, but I haven't been out of targets for awhile so I haven't seen what happens to my backup server list. Good "problem" to have. :p

**Comment by c00w** [comment]
I don't think we did anything with penalties for backups. It autoselects based on reject rate. If you want to use a specific backup then have the others disabled. If you want a backup and a backup fallback set the first one as backup_latehop and the second one as backup.

**Comment by timonex** [comment]
DOH! Forgot about the latehop thing. That should work out perfectly. Hmm...all was going well with the slicer, until bitparking found a nmc block then the slicer got borked and began putting out screens filled with this:

[Failure instance: Traceback (failure with no frames): <class 'twisted.internet.
error.DNSLookupError'>: DNS lookup failed: address 'http' not found: [Errno 1100
4] getaddrinfo failed.
]
[15:10:55] LP Call http://test.bitparking.com:8082/longpoll
[15:10:55] received lp from: bitparking
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 388, in e
rrback
    self._startRunCallbacks(fail)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 455, in _
startRunCallbacks
    self._runCallbacks()
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 542, in _
runCallbacks
    current.result = callback(current.result, _args, *_kw)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1076, in
gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1020, in
_inlineCallbacks
    result = g.send(result)
  File "C:\Python27\Lib\site-packages\c00w-bitHopper-5b8cc32_NEW_FAIL\work.py",
line 66, in jsonrpc_lpcall
    lp.receive(None,server)
  File "C:\Python27\Lib\site-packages\c00w-bitHopper-5b8cc32_NEW_FAIL\lp.py", li
ne 30, in receive
    response = json.loads(body)
  File "C:\Python27\lib\json__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 360, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
exceptions.TypeError: expected string or buffer

I reverted for now.

**Comment by timonex** [comment]
Possible to disable the slicer and keep the penalty functionality on the stats page?

**Comment by c00w** [comment]
Um maybe... The functionality is in all the pools but the olddefault uses macboy's website.
